### ISSUE TITLE
[Improve Request] Content File Sorting

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#10]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Current behavior:**
Folders and pages are sorted only one dimensional, alphabetical order. It will get messy when the site gets to medium sized. 
![image](https://user-images.githubusercontent.com/14123790/35252987-df561ef2-0047-11e8-8007-955153813d60.png)

**Expected behavior:**
I feel that different file types should be separated. In this case, the files should be sorted by 
1. File types
2. Alphabetical 
3. Or just implement manual sorting by numbers 

So the default output should be:
**Blog
Folder
Settings
Home
Marketing**

This is up for discussion. Inputs will be appreciated.

**Comment by onefriendaday** [comment]
Sorting of the content item can be done already by clicking on "Move" in the submenu. Would that satisfy your requirement?:

![Alt text](https://monosnap.com/file/fNPtRjtltjLgO60MTvmtYKXQNJCq2z.png)

**Comment by pxwee5** [comment]
Oh yea, I didn't notice that. However, are the posts sorted accordingly in the api array when you move it like that? 

Personally I am familiar with sorting my own posts, either alphabetically by the `title` property or numerically by the `sort` property in the api object.

**Comment by onefriendaday** [comment]
Yes they are sorted by in the api calls by default by the position field. You can also explicitly sort by position asc and desc and limit by tree levels. Examples:
https://api.storyblok.com/v1/cdn/stories/?version=published&token=Suj60m3KVc37T3zlgeYQfAtt&sort_by=position:asc&level=1

Or you can use the Links API to get the position parameter to create a navigation tree:
https://api.storyblok.com/v1/cdn/links/?version=published&token=Suj60m3KVc37T3zlgeYQfAtt
