### ISSUE TITLE
Icon or Screenshot in Schema Config is not visible

### ISSUE THREAD

**Issue by deepsoul** [storyblok/storyblok#101]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
When adding an icon or screenshot in the schema configuration, the selection of the component is now buggy and flickers

**Expected behavior:**
I want to see the screenshot or icon when i select a component

**Steps to reproduce:**
add an icon or screenshot in the schema config and then select this component

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Would you be able to provide the Space ID + Component you see the flickering so we can test that?
