### ISSUE TITLE
Add possibility to block access to image editor in custom roles

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#102]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

**Expected behavior:**

In some cases it can be very useful to restrict the access of the image editor to prevent several modified version of images popping up in the assets manager when those aren't necessary.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/image-editor-permission
