### ISSUE TITLE
add Possibility to define a home story at / in the root of the content respository

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#103]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with Ruby on Rails apps and the params[:path] is empty one can request the "home" story but links will still point to the "/home" slug. Directing to the root "/" isn't possible yet but would prevent content duplication.
**Expected behavior:**

With the possibility to set the slug for home to "/" in the root one could redirect to it and get the home story without additional issues and a too complicated logic that would be hard to maintain.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by altryne** [comment]
This is something I've stumbled on as well. 
Is there not way of showing home content under `/` right now with storyblok? 
There's no ability to preview the home content as well as it adds the slug automatically to every page in the preview iframe. 
Setting the feature to "root" folder shows me this error
![image](https://user-images.githubusercontent.com/463317/67222760-35fabe00-f3eb-11e9-9867-2fc2680ce7f4.png)

**Comment by DominikAngerer** [comment]
Added an `if` statement that checks on the `home` slug would be the way forward, the reason for that is that if we allow a base `/` as slug you would no longer be able to consume the `stories/` endpoint itself and load collections. To overcome this we've introduced the real-path feature for you which also got added in the Content Delivery API: https://www.storyblok.com/cl/real-path-added-to-content-delivery-api

**Comment by mattpilott** [comment]
For me and others who trip on this, simply set the `Real Path` to `/`

**Comment by rkyoku** [comment]
`Real Path` is not an option for multilingual sites as the language slug isn't prepended to the page slug like it however is for all other pages (not relying on `Real Path`)

I'm not sure to understand why having a page pointing to `/` isn't possible. It's the first page of each and every website.

How could a webpage URL impact an API in any way?

Sorry if these questions are stupid. I would love to better understand the caveats behind the original request, as I also find myself in that situation (I already circumvented it SSG-side by using URL rewriting, but it breaks the preview in Storyblok).
