### ISSUE TITLE
Add option to restrict changing names of stories and creating stories for custom user roles

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#104]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When configuring a custom role for editors with limited access it is still possible for the editor to modify the name of a story and create stories what isn't desirable in all cases if only the content should be editable.
**Expected behavior:**

Adding the option "deny modifications of story names" and "deny creating stories" can help to protect the integrity of the web apps and their implementation when they're relying on the story name.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
You should rely on the story slug instead of the name and use the setting "Deny changing the slug of a story".
