### ISSUE TITLE
Selective shared components

### ISSUE THREAD

**Issue by onefriendaday** [storyblok/storyblok#105]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently the shared components app lets you only use all components of the parent space at once.

**Expected behavior:**
It should be possible to selectively choose specific components that are shared.

**Comment by jbertel2** [comment]
To clarify further: Our ultimate expected behaviour would be that all components of the parent space are shared with the child space, but we can still manage components in the 'child' space as well. 
i.e. shared components live in the parent space; specific components live in the child space.

**Comment by onefriendaday** [comment]
We looked further on that use case and recommend you to use the cli or management api to manage a mixture of components. In the master space you can have one set of components and in the child space another. If you use then the cli https://github.com/storyblok/storyblok#pull-components to transfer the components from one space to another you will have still the customized components.
