### ISSUE TITLE
Add published_at field to links endpoint

### ISSUE THREAD

**Issue by oscargullberg** [storyblok/storyblok#106]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
The links endpoint (https://api.storyblok.com/v1/cdn/links/) response doesn't include `published_at` for link objects. 
**Expected behavior:**
`published_at` is included in the link objects response. This would make it possible to include the `<lastmod>` tag when using the links API to generate a sitemap, as suggested [here](https://www.storyblok.com/tp/how-to-generate-sitemap-headless-cms).

**Comment by onefriendaday** [comment]
The links endpoint was made to be as lightweight as possible to get a fast response. To generate a sitemap we recommend you use an hourly or daily cronjob that generates the links from the stories endpoint. With Storyblok's Javascript SDK you can easily do that using the getAll method: https://github.com/storyblok/storyblok-js-client#method-storyblokgetall
