### ISSUE TITLE
add the source type "tag" to single option / multiple options in field definitions

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#107]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Tags are not available in single-option/multiple-option to select from `Source`. Currently `Self, Stories, Datasource, External Source..` is available

It would be great if `Tags` would be added additionally to the selector. This would make an own plugin redundant.

<img width="562" alt="Screenshot 2019-10-17 at 11 15 38" src="https://user-images.githubusercontent.com/489221/66975099-f15fe180-f0cf-11e9-9c25-a7c441669b51.png">

**Comment by onefriendaday** [comment]
We want encourage the use of a plugin here. It's also now possible to publish plugins in the app store via the partner portal and earn money with it in the future.

**Comment by dohomi** [comment]
@onefriendaday @DominikAngerer  I would like to raise attention to this again. As I currently using a plugin to have this feature in place everything seemed to work. But after you added the feature of updating and list tags the plugin does not update the references. That means the plugin I wrote breaks as soon tags being renamed. It would be great if there would be a solution to it.

**Comment by troyer** [comment]
For the project I'm working on I would also love to have this feature implemented.

My use cases :

- I have a page/story with Blocks. One of the Block is a related content Block. I want to select a tag from the list of tags so then I can pull content using that tag selected.
- For a story/article, I would like to set one of specific tag from the list of existing tags as a primary tag.

**Comment by sam-g-roberts** [comment]
Tags as a source of data would be very useful
