### ISSUE TITLE
Search not reseting when navigating into a folder

### ISSUE THREAD

**Issue by nielsbosma** [storyblok/storyblok#108]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behaviour:**
Search for a folder then click on the folder.

**Expected behaviour:**
I expect to navigate to that folder and the search query to be reset so all item in that folder is shown.  Search isn't applied to the items in the folder either. 

**Steps to reproduce:**
Search for a folder then click on the folder.

**Related code:**

**Other information:**

**Comment by onefriendaday** [comment]
has been fixed
