### ISSUE TITLE
internal link does not infinitely fetches all pages of a specific slug

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#109]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Content element "internal link" in the backend is limited to 25 search results without fetching more results while scrolling all the way to the bottom

**Expected behavior:**
Internal links should fetch the next 25 records until the end that all pages will be found. This is very important for SEO relevant slugs which are given to many pages in the pagetree.

**Steps to reproduce:**
Having more than 25 pages lets say with the starting slug "/marketing**" it will be not able to find the exact page "/marketing" because there are too many newer pages where the slug consist marketing

**Other information:**
It would be useful if the link list is a infinite search over all pages exist inside of the backend.

**Comment by dohomi** [comment]
<img width="371" alt="Screenshot 2019-10-23 at 09 34 25" src="https://user-images.githubusercontent.com/489221/67348699-53a95e00-f578-11e9-9fde-1cd51f737b26.png">

**Comment by onefriendaday** [comment]
Infinitive scrolling has been already implemented.
