### ISSUE TITLE
Author Name in Story API Object

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#11]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   
- [x] *api.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Current behavior:**
Currently there isn't an author property in the story api object. 

**Expected behavior:**
I would think that the author is can be selected or automatically selected from the user's first and last name to fill the author property in story api object. But that isn't the case. 

Not sure what was the approach behind this, but if you could explain why the author is not included into the story api object that'll be great!

I suppose for now the only solution for this is to create a list of authors and then select authors using the single option field. Correct?

**Comment by DominikAngerer** [comment]
> I suppose for now the only solution for this is to create a list of authors and then select authors using the single option field. Correct?

Thats correct. The reason we're not adding the author directly to the story object is that you would not be able to extend the User with additional data as you may need it. By creating your own content type for authors you're free to extend that with additional fields as you may like. To create that reference to another author you can either use the Link type or use the storyloader plugin which will allow you to reference to other content entries as a single choice / multiple choice.

**Comment by pxwee5** [comment]
Got it! Thanks for the explanation. 

However, seems a bit redundant to have to re-enter the token again using the story-loader. 
I would think it's easier to extend link field to support "starts_with" for the internal links.

**Comment by DominikAngerer** [comment]
Great point - we got that already on the backlog! :)
