### ISSUE TITLE
add additional functions to richtext field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#110]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Feature descriptions:**

It would be useful for many use cases to have following functions available in the richtext field:

1. The possibility to limit the amount of text.
2. The possibility to paste components copied from somewhere in the story.
3. A button to paste text with formatting or paste without formatting.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/max-length-in-richtext
