### ISSUE TITLE
Add possibility to change the display name of components / nested block elements

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#111]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is only possible to add a text field inside of a nestable block component which will be shown in the preview to be able to distinguish the individual components from each other when they are used several times.
The actual solution would look like this:
![Bildschirmfoto 2019-10-24 um 10 38 25](https://user-images.githubusercontent.com/12159917/67492588-05b25a00-f64d-11e9-8f64-706fb108ce6c.png)

**Expected behavior:**

With the ability to change the displayed name it would improve the clarity of the purpose of those components and save some time when searching a specific one.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
We've added a custom preview option, the name however will still stay: https://www.storyblok.com/cl/custom-block-preview
