### ISSUE TITLE
Add the ability to search blocks within a story

### ISSUE THREAD

**Issue by altryne** [storyblok/storyblok#112]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Searching through the main for a block shows the story that block is in, but not the block itself. 
We have created a `redirects` story that has 100+ records of redirects, and the users will need to search a specific one because they sometimes change. 
Hard to find a specific block in this case

**Expected behavior:**
Adding a search for blocks with their content on the story editing page (even for stories with a LOT of blocks) will be very helpful here

**Steps to reproduce:**
Create a story with 10 blocks, try to find one specific one

**Related code:**

```
insert any relevant code here
```

**Other information:**
We discussed this with @Slackman2015 and based on his advice tried to change the arrangement to use nested stories per redirect. this way they are searchable, but the UI only shows the story name, and the blocks UI we can customize to show from/to options of the redirects and it works much better

**Comment by onefriendaday** [comment]
We recommend to use a preview template to show the necessary information in the block preview: https://www.storyblok.com/docs/schema-configuration#options
