### ISSUE TITLE
Use display name for editable block outline/highlight

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#113]
**The issue occurs while working with:**
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently `_editable` field includes the technical name of field.
This is used by the editor interface when highlighting the blok.

**Expected behavior:**
It would be nice if the name was mapped to the display name to be consistent with the field name the editor sees.

**Steps to reproduce:**
See `type-editors-note` on left and `Editor's Note` on right
![Screen Shot 2019-10-25 at 4 12 07 PM](https://user-images.githubusercontent.com/932566/67604819-42ac4880-f742-11e9-8fba-b9901cec733b.png)

**Comment by cswebdev** [comment]
at least it would be nice if we have the possibility to have that feature optional by a setting

**Comment by onefriendaday** [comment]
The JS bridge has been updated to show the display name.
