### ISSUE TITLE
Search for references to content

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#114]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

My editors would like to be able to search for places an story is used / linked too.

@slackman2015 said this was possible by referencing the UUID and field name in the search filters.
![bildschirmfoto-2019-10-24-um-1_xm0itd](https://user-images.githubusercontent.com/932566/67605402-e77b5580-f743-11e9-8140-a1bb036ab323.png)
However, my editors don't know what UUIDs are and they aren't shown to them in the UI (not that they should be shown).

I'm not sure they best UX way to provide this feature, but maybe a button/link to "find usages" of this story. Maybe that just prefills the filters?

Taking this one step further, the story may be referenced by multiple field names or more likely in dynamic content - i.e. links inside of rich text fields. It would nice if these could be located as well, similar to a full text search.

**Comment by onefriendaday** [comment]
Has been implemented: https://www.storyblok.com/cl/improved-content-filters
