### ISSUE TITLE
Search for stories by datasource entry name

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#115]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

We have a datasource, `projects`, and my editors would like to be able to search for stories that reference these datasource entry names
![Screen Shot 2019-10-25 at 4 35 15 PM](https://user-images.githubusercontent.com/932566/67606047-d29fc180-f745-11e9-8d35-f60ee07a6f78.png)

I'm guessing it would work something like this:
![Screen Shot 2019-10-25 at 4 36 18 PM](https://user-images.githubusercontent.com/932566/67606052-d7647580-f745-11e9-803e-5cdc31cfa86f.png)
Although I know that would cause complications because you would have to conditionally map that value to the datasource entry ID. Maybe a separate filter input is necessary...

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/improved-content-filters
