### ISSUE TITLE
Rich Text links do not copy/paste correctly

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#116]
**The issue occurs while working with:**
- [x] *app.storyblok.com (CMS - Interface)* 

**I'm submitting a ...** 
- [x] bug report  

**Current behavior:**
Links when copied/cut do not keep the destination & options when pasted.

**Expected behavior:**
The pasted link destination & options would be still be configured.

**Steps to reproduce:**
![](http://g.recordit.co/t4UtMZhmRl.gif)

**Comment by onefriendaday** [comment]
Has been fixed
