### ISSUE TITLE
Format/null bug from first published date on input event

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#117]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
`first_published_at` returns ISO date from the API, but the value from `input` event is formatted differently. Sometimes it's formatted as `yyyy-MM-dd HH:mm:ss` and other times it is just `null`.

**Expected behavior:**
The value should be an ISO datetime or null.

**Steps to reproduce:**
Have a first published at date set and preview the content.
Make a change so the new content comes through on the `input` event.
The field there will be null or incorrectly formatted.

BTW what should I be calling this? Is it the JS bridge? or editor events? or...?

**Comment by onefriendaday** [comment]
It is right. The first_published_at date is null if the content item has not been published yet and an iso date if it has been published. Example: "2018-11-24T17:16:00.000Z". We don't consider this as a bug and handling the null in your application is what we recommend.

**Comment by CarsonF** [comment]
I understand nulls are expected.
I was trying to report that value from the input event is _not_ ISO formatted. 
(Though I haven't check recently, maybe it's already been fixed.)
