### ISSUE TITLE
resolve_links does not affect links in rich text

### ISSUE THREAD

**Issue by CarsonF** [storyblok/storyblok#118]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
`resolve_links=story/url` does not return story objects for internal links inside of rich text links.

**Expected behavior:**
Rich text internal links should have story objects based on `resolve_links` query parameter.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/resolve-links-in-richtext-field
