### ISSUE TITLE
CLI push-components does not push component groups

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#119]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* CLI
**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
The CLI does not add the component_groups created if using push-components command. 

**Expected behavior:**
If component groups are used for component blok whitelists it should be added in the CLI command as well.

**Comment by onefriendaday** [comment]
Sorry for the late reply. The feature has been released in Dezember: https://github.com/storyblok/storyblok/commit/c40258a645b65c64fc9430c91ec46f0455f96470

**Comment by dohomi** [comment]
@onefriendaday @DominikAngerer issue is still present with the most current CLI (v 2.7.0). I have component groups and neither `sync` nor `push-components` is respecting the component groups

**Comment by samuells** [comment]
@onefriendaday can we double-check this?

**Comment by onefriendaday** [comment]
We double checked it. Executing pull-components and then push-components syncs the groups correctly. But the implementation in the "sync" task would be a new feature request.
