### ISSUE TITLE
Rich Text allow multi-select and reorder of class names

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#121]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently class names are single select only. After creation its not possible to reorder or re-arrange the class names. Also with lot of class names the editor starts to get uneasy to use due to the very long list of class names.

**Comment by onefriendaday** [comment]
The class names can be sorted here:
![https://a.storyblok.com/f/52813/480x312/a151baabc4/screenshot-2020-04-06-at-09-52-25.jpg](https://a.storyblok.com/f/52813/480x312/a151baabc4/screenshot-2020-04-06-at-09-52-25.jpg)
