### ISSUE TITLE
Single-option default hides empty option

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#122]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**

A single-option field has always an empty selection, even if the `default` is set to be one of the option.  

**Expected behavior:**

If the `default` value matches one of the value in the options' list, do not create the empty selection.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/hide-empty-option
