### ISSUE TITLE
Date/Time component uses 00:00 when time selection is disabled. This causes problems when parsing the date in another time zone.

### ISSUE THREAD

**Issue by invatom** [storyblok/storyblok#123]
**The issue occurs while working with:** (check one with "x")   
- [ X ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ X ] feature request  
- [ ] question

**Current behavior:**
Date/Time component uses 00:00 when time selection is disabled. 
This causes problems when parsing the date in another time zone.

Selecting a date outputs "2019-10-01 00:00" to the field.
This creates problems when parsing this date into a JS datetime object.

var foo = new Date('2019-10-01 00:00');  // the environment here is set to UTC+2 which is used by the js runtime.

Depending on the time zone the output will be for example:

foo.toISOString()
> "2019-09-30T22:00:00.000Z"

**Expected behavior:**

No time included, OR it should be set to 12:00

Using 
var foo = new Date('2019-10-01') 
output via foo.toISOString()
> "2019-10-01T00:00:00.000Z"

**Comment by onefriendaday** [comment]
Has been fixed
