### ISSUE TITLE
Renaming dialog opens in the background when inside of the assets manager

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#124]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When going into a story and opening the asset manager using the asset manager button 
![Bildschirmfoto 2019-11-01 um 14 48 07](https://user-images.githubusercontent.com/12159917/68044751-b60c0800-fcb6-11e9-8e28-724669a49298.png) and trying to use the renaming button 
![Bildschirmfoto 2019-11-01 um 14 50 37](https://user-images.githubusercontent.com/12159917/68044931-2581f780-fcb7-11e9-9ac8-6770846d7b18.png) it will open the dialogs in the background. When the asset manager gets closed the dialogs are visible:
![Bildschirmfoto 2019-11-01 um 14 52 50](https://user-images.githubusercontent.com/12159917/68045015-55c99600-fcb7-11e9-9008-98ec6130b911.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
has been fixed
