### ISSUE TITLE
Can't edit embedded block element in Rich Text Field, only name appears

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#125]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When adding a component with an embedded block element it isn't editable inside of the rich text field. It will appear like the component at the bottom in the following image: 
![Bildschirmfoto 2019-11-06 um 08 04 06](https://user-images.githubusercontent.com/12159917/68293521-dba96080-006c-11ea-971a-c6a02faf6e14.png)
There appears only the name of the block element but looking at the JSON it seems to add the block element correctly: 
![Bildschirmfoto 2019-11-06 um 08 14 37](https://user-images.githubusercontent.com/12159917/68293846-90dc1880-006d-11ea-9366-350eee8e16e0.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Fixed
