### ISSUE TITLE
Date/Time picker saves wrong time when time selection has been deactivated

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#127]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

This report extends https://github.com/storyblok/storyblok/issues/123 by the part that the Date/Time picker saves the wrong time when selecting the disable time selection checkbox:
![Bildschirmfoto 2019-11-06 um 09 58 15](https://user-images.githubusercontent.com/12159917/68300213-15ce2e80-007c-11ea-9f08-8d2cecafedb5.png)

When for example the user profile has been configure with Central European Time the picker shows 02.01.2019 00:00 but in the component preview and the JSON it shows 01.01.2019 23:00, one hour less.

Another example:
When the profile has been configure with the timezone America/ Sao Paulo -02:00 the JSON contains Time:"2019-11-02 03:00" after saving with "2019-11-02 00:00".
![Bildschirmfoto 2019-11-05 um 06 17 10](https://user-images.githubusercontent.com/12159917/68302561-11584480-0081-11ea-94ef-61e3c83f8763.png)
![Bildschirmfoto 2019-11-05 um 06 18 21](https://user-images.githubusercontent.com/12159917/68302562-11f0db00-0081-11ea-8354-ec2d5ec861e3.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
has been fixed

**Comment by matovincetic** [comment]
I get this behavior even when the »Disable time selection« is not checked. Time picker shows one hour later then data.

TIME PICKER
<img width="323" alt="Bildschirmfoto 2021-02-24 um 12 11 30" src="https://user-images.githubusercontent.com/29774115/108992540-babdb200-7699-11eb-8872-0212b8a963d1.png">

DATA GENERATED FROM TIME PICKER
<img width="459" alt="Bildschirmfoto 2021-02-24 um 12 11 55" src="https://user-images.githubusercontent.com/29774115/108992558-bf826600-7699-11eb-8303-42b4a9ed2001.png">

**Comment by matovincetic** [comment]
Any updates ok this? I habe a site launch in a week and hope that this could be fix until then so that no work around is needed. :/
