### ISSUE TITLE
Adding import and export function to dimensions of datasources

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#129]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When exporting a datasource it isn't possible to export a selected dimension or dimensions with it.
**Expected behavior:**

With the function to be able to select the datasource and its dimensions for exporting and importing the usability would be improved greatly when used for external processing like automatic translation.
The function could be integrated in the marked section. It could show check boxes for the selection of the datasource and its dimensions.
![Bildschirmfoto 2019-11-10 um 08 23 04](https://user-images.githubusercontent.com/12159917/68543277-c77aa180-0393-11ea-99ae-8799d52badab.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/datasource-dimension-import-export
