### ISSUE TITLE
Stories aren't getting published when using publish function of a folder

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#130]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When using the publish function of folders the stories inside of the folder(s) aren't getting published but when checking the link objects it is visible that the folders are marked as published. The following video shows the issue from the frontend side: 
[Bildschirmvideo aufnehmen 2019-11-08 um 06.34.08.zip](https://github.com/storyblok/storyblok/files/3828388/Bildschirmvideo.aufnehmen.2019-11-08.um.06.34.08.zip)
Here is the part from the links API:
![Bildschirmfoto 2019-11-10 um 08 46 12](https://user-images.githubusercontent.com/12159917/68543515-c8610280-0396-11ea-8b4a-b9d4bada68f9.png)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/folder-publishing-unpublishing
