### ISSUE TITLE
add option choosing individual access right for folders/stories

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#131]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is possible to select the rights for a custom role based on a general base for all items in a space or limited by whitelists only.
**Expected behavior:**

In certain situations it can be useful to be able to choose the access rights based on a per items base for a custom user role when for example an editor should have the ability to publish articles but only save changes to the index story that need to be approved by an admin.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Good idea but our experience with other CMS showed that this can get very messy and difficult to manage for the users in the long term. We decided to make permissions as simple as possible
