### ISSUE TITLE
add new filters to the search in the frontend

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#133]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

This thread extends https://github.com/storyblok/storyblok/issues/114

**Current behavior:**

At the moment the search isn't easy to use because the correct usage requires that the user knows the field names and the UUIDs that he wants to search for when referenced with a single or multi options field. Searching for booleans doesn't work at the moment.
Another point is that the search result list doesn't contain important information like the slug and the values of the fields that are of the interest for the user.

**Expected behavior:**

A useful addition would be to allow the user to select the in the schema available fields for typing the search values into them like this example shows:
![image_11mxgq2](https://user-images.githubusercontent.com/12159917/68953021-c71d4480-079f-11ea-8b57-bedf2bd21c69.png)

The in the search selected but left empty fields could help the user when searching for a range of possible candidates. For example the user has a folder with products and knows the name and there are some variations of it available. The additional fields could show the characteristics of the results so that the user can find the correct item easily.
The available fields could be adopted depending on the content type of the folder.

Another important point is that references can only be searched by their UUIDs but those information aren't available for casual users who doesn't know what it is. It could be necessary to allow the user to search for references by their slugs/ids or anything that can be handled easily by non developers to make the search more intuitive.
A further step would be to allow to search for references in custom field types. Maybe a customizable search concept could help here out because the number of custom solutions for field types is increasing.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
References to "Customizable List Views" to have define and save filters that use `filter_query` to provide customized views.

**Comment by jajouka79** [comment]
the lack of custom columns in sbk has presented a bit of a problem regarding featured content.

we have added a featured boolean on the ctype, but from the client admin perspective they can't see from the list of content which is featured, how many are featured, no filter by featured etc.

**Comment by dlandmann** [comment]
Hi - we need a extended Listview in Storyblok. Is this possible?

Example: We have Contenttypes with more than 2000 entires. In Listview we can only sort by Name (and created at and so on). We need more Fields (our custom Fields from the Contenttype, e.g. Order) in the Listview.

| Name | Date | Order | and custom Field |
|------|------|-------|------------------|
| Name | Date | Order | and custom Field |
| Name | Date | Order | and custom Field |
| ... | ...  | ...   | ...              |

**Comment by Slackman2015** [comment]
Addition to this feature request:
Our customers need to be able to search for published, unpublished and stories that have been published but changed.

**Comment by dlandmann** [comment]
Hi - there is already a schedule for this feature. We will start with our new page (with Storyblok) next week and need the sorting and filtering options as soon as possible :-)

Can i support you somehow?

**Comment by onefriendaday** [comment]
Has been implemented: https://www.storyblok.com/cl/improved-content-filters

**Comment by DennisMaass** [comment]
> Addition to this feature request:
> Our customers need to be able to search for published, unpublished and stories that have been published but changed.

Has that also been implemented? I don't find that...
