### ISSUE TITLE
Add possibility to define a description for components/content types

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#135]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Desired behavior:**
Currently the field description is a `text` field but it would be nice it to be a `textarea` in order to begin able to write more descriptive content with new lines `\n` and possibly URLs (links).

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/multiline-field-descriptions
