### ISSUE TITLE
add functionality that resets the workflow stage of stories after publishing them

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#136]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with the "workflow stages" the user can choose between the preconfigured stages or when available in the plan configure an own workflow.
![Bildschirmfoto 2019-11-19 um 18 51 45](https://user-images.githubusercontent.com/12159917/69189768-bea96e80-0afd-11ea-8b65-496bb39f7b04.png)

**Expected behavior:**

What is missing at the moment is that the workflow gets reset to a neutral state after publishing. It would help to be able to configure this behavior to change by default to "none" after publishing and giving the possibility to the user to define an own standard state to which the state should be set to after publishing it. It could look like this: 
![Bildschirmfoto 2019-11-19 um 18 53 29](https://user-images.githubusercontent.com/12159917/69189872-fb756580-0afd-11ea-9d46-253d0976d5d4.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/workflow-after-publishing
