### ISSUE TITLE
Copy / Paste of Entry does not create new _uid for nested content

### ISSUE THREAD

**Issue by sean6bucks** [storyblok/storyblok#137]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**
When copy/pasting a block, the new copy and it's children will all have new `_uid`'s since they are a copy and not a reference to the same component, however when copying an Entry from the "content" dashboard the new copy does not update the content and it's children with new `_uid` values.

**Expected behavior:**
Copy and Pasting an entry should create a whole new record (which it does with new id and uuid) as well as creating all new content copies with new `_uid` values the same way copy/paste of blocks from the editor does. If I update one of the new entry's children, I don't expect it to update that value in the old page, however those two blocks/components share the same `_uid`.

**Steps to reproduce:**

1. Create new page/entry with content/components
2. Copy and paste entry to create another entry with new id and uuid
3. Inspect those pages' json and you will see their "content" and any children components share the same `_uid` values even after values are edited.

**Related code:**
<img width="519" alt="Screenshot 2019-11-20 at 09 56 53" src="https://user-images.githubusercontent.com/5891258/69224227-7715f780-0b7c-11ea-974c-481bf6814b66.png">
<img width="487" alt="Screenshot 2019-11-20 at 09 57 00" src="https://user-images.githubusercontent.com/5891258/69224228-7715f780-0b7c-11ea-9938-9cf46978d076.png">

**Other information:**
Have not tested with API's but I assume the results would be similar. IF this is the expected behaviour then not only should there be a copy change "COPY" => "DUPLICATE" but also the content and children components should be linked if any changes made related to that _uid (but I dont think you guys want that)

**Comment by DominikAngerer** [comment]
This is expected behavior, as this allows for merge/override features for alternate versions or tree like translations using the dimensions, since this will keep the context of the entries. The `_uid` for each component is unique only in the context of one story object. The combination of the stories `uuid` + `_uid` gives you a fully unique identifier. Copy and pasting gives you a fully unique and new record, identified by the `uuid`.
