### ISSUE TITLE
Adding a feature to undo and redo changes while editing

### ISSUE THREAD

**Issue by abrambailey** [storyblok/storyblok#138]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The following is from a chat I had in Storyblok. The agent suggested I opened an issue, and I'm short on time, so here's the chat copy and pasted! 

> I love storyblok, but one of my biggest issues is not having a simple "undo" button.
> 
> I find the "restore" option very confusing and undoing that very last action should not be so difficult...
> Like, I just deleted an image... but if I look back at the most recent restore point, it is completely nonsensical
> 
> I don't really understand why it is so hard to just be able to click undo a few times rather than try to understand this... 
> 
> To be honest, I have never used restore because I do not have confidence in what I am restoring to... 
> 
> Also, it seems like it should be easy to launch a preview window to actually view any restore point by sending the previous json from the restore point to be rendered in the preview
> 
> I literally cannot even copy and paste what is in the diff for the restore point as it's disabled
> so I have to review the restore point diff in that tiny window

**Comment by DominikAngerer** [comment]
Added *feature request* information:

Adding an global "Undo" and/or "Redo" button inside one content entry to allow to add/remove changes made in the entry before leaving. Currently the versions feature allows to only restore from previous published and saved versions but does not allow to undo a small change, eg. removal of one image back or similar. Feature request: add a undo/redo functionality in edit mode stored upon leaving the entry (dialog for keep changes/discard changes already exists).

**Comment by abrambailey** [comment]
Please clarify. Are you saying the new undo button would allow me to undo a change even if I have NOT saved the previous version? That would be the desired behavior.

It seems that there should be a running changelog that stores the json diff even between saves...

**Comment by DominikAngerer** [comment]
Correct - changes that are not previously saved would be able to undo/redo.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/undo-and-redo
