### ISSUE TITLE
add filter option "component" name to stories source selector

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#139]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Path to folder can be selected to filter stories

**Expected behavior:**
Add filter option to specific component types of stories. That would be very useful in case of a category type or referenced content type.

<img width="451" alt="Screenshot 2019-11-22 at 09 34 07" src="https://user-images.githubusercontent.com/489221/69390791-82e3f400-0d0b-11ea-8138-13c68a7c25da.png">

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/restrict-option-field-to-content-type
