### ISSUE TITLE
Restrict Content Type & Show Content Type In Lists

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#14]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

### Restrict Content Types
**Current behavior:**
Cannot restrict content types for folder, hence all content types are shown, even "setting" contents (app-nav). This feature is needed to prevent a "content" folder from adding "setting" contents. 
![image](https://user-images.githubusercontent.com/14123790/35494969-32256824-0523-11e8-995b-319033e9d30c.png)

### Show Content Type In List
**Current behavior:**
Content type not showing in content list

**Expected behavior:**
There are lots of space on the list, we might as well add some form of information so that there's no need to click on the content to figure out what content type it is. Content type should be colored in "unimportant" colors so that it's not confused with the title. 
![image](https://user-images.githubusercontent.com/14123790/35495112-2677a2ca-0524-11e8-8a89-5f1a75b5f0e0.png)

**Comment by DominikAngerer** [comment]
Hey there.

On Folder creation (or by clicking on "Setting" of that one folder) you can currently define a "default" content type for that. By doing so - the selected content type will be pre-selected for new content entries in that folder. 

<img width="415" alt="bildschirmfoto 2018-01-29 um 09 43 41" src="https://user-images.githubusercontent.com/7952803/35501039-f3aed3fe-04d8-11e8-83a1-baa4ef5b0fcf.png">

However I've added this feature request to our backlog and will add new information as soon as it's scheduled for development.

Best,
Dominik

**Comment by pxwee5** [comment]
Yup, I'm well aware that there's the default function. But I don't think it is as useful as setting restrictions to content types, similar to the restrictions to the block content. 

Perhaps the first item (in content type restriction) can be used as default if the feature is added in the future.

**Comment by DominikAngerer** [comment]
https://trello.com/c/bMpYzeeD/30-restrict-content-types-folder

**Comment by onefriendaday** [comment]
The suggestion is to use the option "Deny changing content type" in the folder settings and define a default content type. To handle multiple content types you should create a subfolders. This fits better in the long term plan we have with content structure.

**Comment by kb1995** [comment]
Hello, how can I create a folder page for my content and restrict to only a maximum of one document?
