### ISSUE TITLE
Sort field-level translation languages

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#140]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**
After adding a language using the field-level translations, you cannot sort the languages in `Settings > Languages`.

**Expected behavior:**
I would expect to be able to sort the languages the same way I do with datasources.

**Comment by DominikAngerer** [comment]
https://github.com/storyblok/storyblok/issues/72
