### ISSUE TITLE
add a more detailed summary about data traffic to dashboard and account area

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#141]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual information about the usage found on the dashboard of a space covers the count of requests per day and the data traffic on a per day basis.
![Bildschirmfoto 2019-11-26 um 06 41 18](https://user-images.githubusercontent.com/12159917/69618985-96e46a00-1019-11ea-945e-69a098cedcd8.png)

**Expected behavior:**

In some cases the users need to have a summary for month, week, separable traffic information by API calls and assets and a history to be able to see their traffic usage.

Additionally an overview of all spaces in the left menu in the account area would help to keep track of traffic usage.
![Bildschirmfoto 2019-11-26 um 06 55 32](https://user-images.githubusercontent.com/12159917/69626157-d36a9280-1026-11ea-8861-58e593b6a159.png)

A helpful feature for accounting could be to be able to generate a pdf with some additional information to be able to identify the related space(s) easily.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Detailed statistic has been released: https://www.storyblok.com/cl/detailed-traffic-statistics 

For a list of most downloaded files please contact support. Overview of multiple spaces are available for enterprise plans in the organisation area.
