### ISSUE TITLE
add an option for copying the assets of a space when copying a space

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#142]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When copying a space the assets aren't getting copied together with the content. The fields are still containing references to the original assets of the original space.

In the case that the user isn't aware of this he can suffer a data loss if the data hasn't been backed up recently before deleting the original space with its assets.

**Expected behavior:**

Being able to copy the space with its assets and the references in the new space set to the new copies would save a lot of time.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Doing that would result in extreme cases of redundancy and results in unbelievable long duplication processes. What is the issue with referencing your other space? What are you trying to achieve?

**Comment by Slackman2015** [comment]
When copying a space the original space can undergo a lot of changes when the development continues and assets can get deleted by accident even when they are still needed in the copied space.

**Comment by Slackman2015** [comment]
Another possibility to resolve the "redundant copies" problem could be to introduce global assets that can be shared between spaces. When uploaded per assets manager in the space they are getting assigned only to the space and when the space gets copied there won't be the need to copy the assets physically and to change their references everywhere. They just need to be assigned to the spaces to be available.

**Comment by onefriendaday** [comment]
We recommend to use a sync script in this case. You can get an idea of how this works at the following repo: https://github.com/onefriendaday/accross-region-sync-script

**Comment by ArturDziedziczak-TomTom** [comment]
@onefriendaday is this script working with v2 of storyblok? 

I can't find any documentation which describes process of how to move assets from one space to another. Without this feature of content migration scripts between spaces does not really make sense. Is there any solution to that other than writing own custom migration scripts to migrate assets?

**Comment by gpeires** [comment]
https://www.npmjs.com/package/@kworq/storyblok-space-cloner - this will migrate components, stories and assets from one space to another.
