### ISSUE TITLE
Field Level Translation: Locale fallback

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#143]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**

All languages fallback to `Default` and there is no possibility to setup a per-locale fallback.

**Expected behavior:**

Begin able to specify to which locale should it fallback instead of `Default`.

**Example:**
Space languages:
`Default` `Master English`
`en-us` `English (United States)`
`es` `Master Spanish`
`es-mx` `Spanish (Mexico)`

If a field is translated for `es-mx` any empty field will fallback to `en` content while we would like it to pick up `es` instead.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/custom-fallback-language

**Comment by vabatta** [comment]
Just wanted to report that this is not working anymore: content gets automatically to `null` when using the fallback parameter.
