### ISSUE TITLE
When pasting an URL into an embedded link field the URL gets pasted into the text area of the richtext field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#144]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When having a component inside of a richtext field with a link field and pasting a link into it the link gets pasted above the component and link field into the text area.
[screencast2.zip](https://github.com/storyblok/storyblok/files/3902689/screencast2.zip)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
