### ISSUE TITLE
add function to resolve links and relations in live preview mixin

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#146]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working within the live preview and having relations/links resolved in the data can result in that the data doesn't get resolved again when a change gets registered and the story reloads and disappears.

**Expected behavior:**

When using the live preview with for example a Nuxt.js project it would be a great addition to see the resolved data even after new changes of the content.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
In Nuxt - instead of reloading you can use a router refresh to reload your page and load the data as from the API. The bridge won't be able to add that functionality as it only has access to the current context (the current story itself) which is passed as event data from the main window to your website rather than going through the API logic. You can trigger that refresh like this, which will execute the API requests as you would on your first visit - that would work when pressing "save" and would not use the event data itself:

```
export default {
  mounted() {
    this.$storybridge.on(['published', 'change'], (event) => {
      if (!event.slugChanged) {
        // Reload the page on save events (publish, save button or autosave)
        this.$nuxt.$router.go({
          path: this.$nuxt.$router.currentRoute,
          force: true
        })
      }
    })
  }
}
```

**Comment by pmcp** [comment]
This solution wasn't ideal for me, so i wrote a helper function. When a user is working in a page most of the time the resolve_relations don't need to be updated, so I just removed them from the update.

`     sb.on('input', (payload) => {
        if (this.story && payload.story.id === this.story.id) {
          payload.story.content = sb.addComments(payload.story.content, payload.story.id)
          // Check for resolve_relations
          if(resolveRelations) {
            Object.keys( resolveRelations ).forEach( key => {
              if(payload.story.content.component === key) payload.story.content[resolveRelations[key]] = this.story.content[resolveRelations[key]]
            });
          }
          this.story = payload.story;
      


        }
      })`

Don't know if it helps someone, but here ya go ❤️
