### ISSUE TITLE
add possibility to define number of levels that the links/story API delivers

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#147]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is only possible to get all link objects of a folder and its subfolders without being able to limit the delivered data to a certain level.

**Expected behavior:**

It would help our customers to be able to choose the number of levels they can retrieve link objects for. The advantages would be that the complexity of the code would decrease and the flexibility of the API increase. Other positive side effects are faster loading times because the payload size would be smaller and the time for processing the data would decrease also what could be an important factor when the project has grown a lot after some time.

It could look like:
https://api.storyblok.com/v1/cdn/links?version=your_version&token=your_token&depth=0

0 for the same level as chosen
example :  items from root "/"
delivers just this
![Bildschirmfoto 2019-12-03 um 09 01 57](https://user-images.githubusercontent.com/12159917/70049520-a03a7d00-15ab-11ea-929a-dfdf5c7ca58e.png)

1 for the root and the next level below
example: beginning from root "/"
![Unbenannt](https://user-images.githubusercontent.com/12159917/70050131-04aa0c00-15ad-11ea-989d-6770c78d323c.png)

Together with starts_with this can be a good feature to get only data of certain directories and their subfolders.

**Maybe this can be of use when available in the stories API as well.**
https://api.storyblok.com/v1/cdn/stories?version=your_version&token=your_token&depth=0
and
https://api.storyblok.com/v1/cdn/stories?version=your_version&starts_with=your_folder&token=your_token&depth=0

**Other information:**

**Comment by onefriendaday** [comment]
Unfortunately this is technically not possible. We recommend to get the links and cache them somewhere.
