### ISSUE TITLE
Real path field doesn't appear when a new story is being created with realpath app installed

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#148]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When creating a new story the field for the real path isn't being shown. It appears only when the dialog is being closed by saving the data and then the new story selected and clicked on settings.
![Bildschirmfoto 2019-12-03 um 11 47 26](https://user-images.githubusercontent.com/12159917/70063283-43988b80-15c6-11ea-9d9b-8f34f3966b3f.png)

After opening the settings of the new story:
![Bildschirmfoto 2019-12-03 um 12 13 45](https://user-images.githubusercontent.com/12159917/70063391-70e53980-15c6-11ea-8337-e9ec93e19331.png)

**Expected behavior:**

When the advanced paths app is installed it would be a helpful to be able to add a real path to the new story in one step instead of selecting it again.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
