### ISSUE TITLE
add information to text fields about actual and left symbols that can be written when input limit has been set

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#151]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Like in the image below visible there is no visual indication when the count for symbols has been limited. In the case that an editor is using the frontend he won't know if there is a limitation to the length of the input.

**Expected behavior:**

It would be helpful that the editor could see how much space is left for content in the specific text field with an indicator below the textfield that shows the actual and the left count of chars.
![Bildschirmfoto 2019-12-09 um 07 04 43](https://user-images.githubusercontent.com/12159917/70427151-fa778a00-1a52-11ea-8795-2cc75224b1d5.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/character-limit-counter
