### ISSUE TITLE
Shows if translated content already exists in the list overview

### ISSUE THREAD

**Issue by silcky** [storyblok/storyblok#152]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**
Currently, it's not possible to see if there is any translation within a content item.

![image](https://user-images.githubusercontent.com/316247/70632580-61ea3100-1c2f-11ea-8fc5-4d00962aeec2.png)

**Other information:**
It would be great to see an indicator (icon) for each language.

**Comment by onefriendaday** [comment]
Unfortunately we do not track the information whether the language exists. What we could show is if a language has been published. Would that help in your case? If yes we can create another feature request for that.
