### ISSUE TITLE
Add possibility to use the (undocumented) cache function of Netlify to the nuxt client

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#153]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Assuming that a developer has a big project and needs to rebuild only one page or a handful of  about 2000 pages it can take a very long time to apply even small changes to it. The build time can already sum up to 8 minutes for a page that has 200 pages.

**Expected behavior:**

There is an undocumented cache function in Netlify mentioned here https://twitter.com/stefanjudis/status/988196530820698113 and a project for Gatsby uses it already https://github.com/axe312ger/gatsby-plugin-netlify-cache
The build cache function could use the by the webhooks delivered information about story id to identify the changed pages and regenerate only from changes affected parts of the project.

The speed improvements would be immense when used in large projects and could save a lot of time and when a build fails at some point the build could be continued at the point where it failed without the need to rebuild everything.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
You could use the new published_at filter to make delta updates: https://www.storyblok.com/cl/new-date-queries
