### ISSUE TITLE
add possibility to exclude specific folders/stories from links API responses

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#154]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is only possible to get all link objects of a folder and its subfolders without being able to limit the delivered data to a certain level.

**Expected behavior:**

Additional to the issue https://github.com/storyblok/storyblok/issues/147
It would help our customers to be able to exclude folders and stories by their slugs in a comma separated list. The advantages would be that the complexity of the code would decrease and the flexibility of the API increase. Other positive side effects are faster loading times because the payload size would be smaller and the time for processing the data would decrease also what could be an important factor when the project has grown a lot after some time.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Unfortunately this is technically not possible. We recommend to get the links and cache them somewhere.
