### ISSUE TITLE
Multi-Assets field not firing all events?

### ISSUE THREAD

**Issue by gregorybolkenstijn** [storyblok/storyblok#155]
I have a Multi-Assets field with images and I'm listening for changes as per multiple examples:

`this.$storybridge.on(['input', 'published', 'change'], (event) => {...`

The handler is only called on the 'published' action, not when I change the order of the images. I would expect that to be a 'change' event. 

How can I listen for changes to a Multi-Assets field?
And is this documented somewhere?

**Comment by onefriendaday** [comment]
The issue has been solved.
