### ISSUE TITLE
add possibility to fetch localized content with relation and link resolving (option fields)

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#156]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it isn't possible to get the localized stories when using relations in localized setups based on field level translations.
The actual way of working around this is to fetch the localized stories by their uuids that are stored in the option fields.

**Expected behavior:**

A big improvement would be to be able to fetch automatically the localized story that has been set into relation and if not available the default language.
In some cases it might be useful to be able to set a fallback language like the parameter "fallback_lang" already allows to do with calls to fetch stories.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
This has been fixed.
