### ISSUE TITLE
add possibility to define several source folders for option fields by slug and/or regex

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#157]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual limitation to set only one source folder in option fields limits their usability in the way that if there are several folders to choose stories from it needs more than one field or it shows too much stories in one when leaving the "Path to folder of stories" field free. This can lead to confusion and errors when the wrong stories are getting selected.

**Expected behavior:**

To be able to select more than one folder would make these fields more flexible and allows a more convenient usage when it comes to content creation.
Additionally it would be a useful feature to be able to use REGEX to select various folders with the same name but different slugs

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by Slackman2015** [comment]
Furthermore it would be useful to have the possibility to show only the stories in the selected folders instead of the sub-folders as well. This would make the work for editors easier.

**Comment by kamilvanbuuren** [comment]
@Slackman2015 Thanks for opening the feature request. I agree with your last comment about the subfolder. Although I wouldn't want to lose the option of including the subfolders as well (just to be sure :-) )

**Comment by onefriendaday** [comment]
You can now define multiple folders: https://www.storyblok.com/cl/multiple-folders-for-option
