### ISSUE TITLE
Deleted component field is present in API response and is shown on story overview page

### ISSUE THREAD

**Issue by vasya-kudriashov** [storyblok/storyblok#158]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

Deleted component field is still shown in component's overview area on the story page (in "Form only" edit mode) and is present in API response.

**Expected behavior:**

Deleted component field is not shown in component's overview area on the story page (in "Form only" edit mode) and is not present in API response.

**Steps to reproduce:**

1) Create a new component field
2) Fill this component field in story
3) Save and publish the story
4) Delete this field from component
5) Check the story in "Form only" edit mode:
- This field is not shown in component field list (which is correct), but is still shown in component overview area:

![image](https://user-images.githubusercontent.com/12901404/71088211-366ec580-219e-11ea-9fa7-e937e6d49063.png)

- and is still in API response:

![image](https://user-images.githubusercontent.com/12901404/71088307-674efa80-219e-11ea-8229-927554b8273f.png)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Currently we do not remove content immediately to prevent user errors of accidentally deleting fields of components. Inside the component you will see an area "Fields outside of schema" which you can remove.

@onefriendaday should we allow an option/setting in a space to get around that and start a migration to remove that field for all existing components of that type?

**Comment by onefriendaday** [comment]
1. You can show a different field in the preview by clicking the eyesymbol
2. To delete it completely you need to use the management api
