### ISSUE TITLE
add blacklist option for Folder/Content-item permissions instead of only a whitelist

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#159]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual limit of 100 entries in the whitelist doesn't fit in some use-cases when the owner needs to limit the access to only a few folders and needs to add all allowed Folders/Content-items what exceeds the limit.

**Expected behavior:**

Instead of adding the allowed folders when the count is very high it would help to be able to blacklist only the not allowed Folders/Content-items.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
It's now possible to set unlimited entries for the whitelist. https://www.storyblok.com/cl/improved-role-management

**Comment by mikelange-revium** [comment]
This "whitelist only" format is not properly scalable - what if a client/user adds their own folders, you have to go and add them to this token whitelist.

This * really * needs an exclusion list, MUCH easier to manage especially when dealing with a single protected folder, whilst allowing 'everything else'.
