### ISSUE TITLE
While duplicating a space the content tags are not duplicated.

### ISSUE THREAD

**Issue by bonmedi** [storyblok/storyblok#16]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
While duplicating a space the **content tags are not duplicated**/copied.  

**Expected behavior:**
Everything including tags should be duplicated.

**Steps to reproduce:**
Create a new space. Add a tag to a content entry like a page. Save/Publish. Create a second space and choose the first space as a source in the advanced options of the New Space dialog. Look in the newly created Space if the tag got copied.

**Comment by DominikAngerer** [comment]
Fixed with Release of the Release and Branches feature.
https://www.storyblok.com/cl/branches-and-releases
