### ISSUE TITLE
Richtext link links to page structure instead of specified slug.

### ISSUE THREAD

**Issue by andredewaard** [storyblok/storyblok#161]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When using a Rich Text component and want to link to an internal page which you specified a different slug than where it is located in the folder structure. The link will go to the page where it is located inside the folder structure instead of the slug you specified on the page itself.

**Expected behavior:**

Link to the slug you specified on the page instead of the structure of the folder.

**Steps to reproduce:**

The page i try to link to is 'our-service' and sits inside a subfolder `en` for the english language. but i gave it an 'slug' and 'real path' of `our-service` so the 'en/our-service' is changed to 'our-service'.

**Other information:**

**Comment by onefriendaday** [comment]
The bug has been fixed.
