### ISSUE TITLE
Separate`toggle` for hiding items of blocks

### ISSUE THREAD

**Issue by MarvinRudolph** [storyblok/storyblok#162]
**The issue occurs while working with:** (check one with "x")

- [X] _app.storyblok.com (CMS - Interface)_
- [ ] _api.storyblok.com (CMS - Content Delivery API)_
- [ ] _mapi.storyblok.com (CMS - Management API)_
- [ ] _capi.storyblok.com (Commerce - API)_
- [ ] _Commerce - Interface_
- [ ] _Other_ 

**I'm submitting a ...** (check one with "x")

- [ ] bug report
- [X] feature request
- [ ] question

**Current behavior:**
Currently it's not possible to temporarily deactivate items of a block - I need to delete them completely.

**Expected behavior:**
Add a separate checkbox beside the `delete` icon to toggle the visibility.

**Comment by DominikAngerer** [comment]
We would recommend to use a custom boolean field in the component itself and skip while rendering. You can use the component preview to show the state "visible yes/no". You can add a "tab" for those as well so it won't interfer with your content fields.

**Comment by jony1993** [comment]
Hi @DominikAngerer 

I don't know if this should really be handled in frontend.
This also has some disadvantages:
- Increases the API response unnecessarily
- Repetitive task to add a boolean to every component in storyblok (or is there a way to add a property/boolean to every component?)

Maybe there are already other possibilities, which I do not know or have missed?

Thanks.

**Comment by SmokinB** [comment]
This feature would be really useful. If I want to prepare a section on the site for e.g. a voucher campaign or something similar.

**Comment by mediabeastnz** [comment]
Could this be re-opened? I agree it shouldn't be done after the data has been consumed via an API call.

Content authors often disable blocks for short periods and turn it back on later.

**Comment by pmrok** [comment]
I would also like this feature. Show/hide on content blocks would be beneficial to my workflow.
