### ISSUE TITLE
groups are missing if space is getting cloned

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#165]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Clone a space copies all components but does not copy groups. This resolves in undesired behaviour as soon some components depending on groups. 

**Expected behavior:**
If groups are copied over to the cloned space all components will work as expected. 

**Steps to reproduce:**
Clone a space and click into components. There will be no groups even the cloned space set them up.

**Other information:**
I don't know if this is either a feature or bug, but for me it feels more natural that groups will be cloned as well. Especially if groups are used as component blocks.

**Comment by onefriendaday** [comment]
Has been fixed.
