### ISSUE TITLE
Field plugin method `initWith` is called multiple times with wrong data

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#166]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
The method `initWith` of a custom field plugin is called multiple times, and if compiled using the [plugin template](https://github.com/storyblok/storyblok-fieldtype) the first call has `this.options === undefined` which should not be the case.

**Expected behavior:**
The method to be called once with correct state.

**Steps to reproduce:**
Test it in the plugin editor.

**Comment by onefriendaday** [comment]
You should use the method `pluginCreated` to initiate your plugin code. 
Example:
```
pluginCreated() {
  this.$nextTick(() => {
    console.log(this.options)
 })
}
