### ISSUE TITLE
Add possibilty to restrict access to components' tabs using roles

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#167]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**
It is not possible to use Role to restrict access to all fields within a specific tab of a component but groups only.

**Expected behavior:**
In the role editor having an option to select components' tabs to hide / deny access for the selected role.

**Other information:**
A common use case is that we create a `Styles` tabs under each component, containing styles settings such as colors and spaces, and they should be controlled only by designers and admins but not by editors.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/improved-role-management
