### ISSUE TITLE
add app that adds the possibility to put rulesets for user-roles together (add modularity to user role managment system)

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#168]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the present moment the user role management system offers the possibility to create custom roles and to assign 2 predefined user roles (admin and editor).
The custom role configuration is being made with a set of options that can't be reused and reassembled to new custom roles nor can an existing basic configuration be extended by a new set of rules/settings.

![Bildschirmfoto 2020-01-09 um 17 28 43](https://user-images.githubusercontent.com/12159917/72102359-9112c180-3305-11ea-9e87-c9d08c170132.png)
![Bildschirmfoto 2020-01-09 um 17 28 49](https://user-images.githubusercontent.com/12159917/72102360-9112c180-3305-11ea-9c10-dde0cbaeaff2.png)

**Expected behavior:**

Adding the possibility to split the configuration into separate building blocks can make working with it an easy and fast process when building more complicated roles.

Modularity can come in handy when working with large white lists of directories that can contain a fixed set of directories but between the different custom roles only differ the allowed language. In this case it would be possible to reuse the list and only modify the differences and save a bunch of time.

As the user-role management system evolves and possibly more options are being added the modularity adds flexibility and can help to keep the overview about the options that have been already applied to a custom user role.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Good idea for an app for advanced role management.
