### ISSUE TITLE
stories with required fields can be published in the folder view without filling the required fields out

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#169]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

The frontend allows the user to publish stories that have unfilled required fields.
![Bildschirmfoto 2020-01-10 um 06 28 49](https://user-images.githubusercontent.com/12159917/72142006-922e0800-3372-11ea-84dc-a44a0c2516cf.png)

![Bildschirmfoto 2020-01-10 um 06 23 03](https://user-images.githubusercontent.com/12159917/72141580-e2f13100-3371-11ea-90da-293e1fff04b2.png)

**Expected behavior:**

For security reasons it shouldn't be possible to publish a story with as required defined fields that are empty because it can break the implementation or cause undefined behavior.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by samuells** [comment]
You can replicate this through following steps:
1. Define schema of page with required field
2. Create somewhere this page - it is not possible to save, but it is created
3. Go back to content viewer - the page is there - unpublish
4. Publish page from there content viewer 

The field will be not present in published json

**Comment by onefriendaday** [comment]
Unfortunately we can not check the required field on that level. The required attribute is meant to be a help for the content editor and does not pass through a serverside validation. But you can additional security here with the workflow feature. Setting up a default workflow stage will prevent the user from publishing without going though review stages.
