### ISSUE TITLE
when changing the link type of the multilink field from asset to link and back the cached_url stays

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#170]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When creating a multilink field and setting it to asset (choosing an asset) and then to URL with saving it between the steps the cached_url stays and can be copied.
Here is an example:
![Bildschirmfoto 2020-01-10 um 16 55 48](https://user-images.githubusercontent.com/12159917/72182397-224b6c00-33ca-11ea-8aef-33bad65610f2.png)
![Bildschirmfoto 2020-01-10 um 17 12 24](https://user-images.githubusercontent.com/12159917/72183340-7b1c0400-33cc-11ea-86e1-0d3cca942c71.png)

**Expected behavior:**

The cached_url should be reset when changing to the asset link type so that the old data in the cached_url property doesn't stay and produces unpredictable behavior under certain circumstances.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
