### ISSUE TITLE
add more options for predefined sorting orders to the folder/story view

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#171]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The sorting possibilities are limited to:
- default sorting
the following ascending and descending
- creation date
- last updated date
- name
- slug 

**Expected behavior:**

Some users are asking for the two additional options:
- first published date
- published date
This gives a better overview when searching for the recently published stories or stories that are already older and need to be updated for example when additional fields are getting added or removed.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by samuells** [comment]
+1

**Comment by onefriendaday** [comment]
Has been released:  https://www.storyblok.com/cl/new-publishing-dates-sorting
