### ISSUE TITLE
When setting the "Workflow stage" back to "none" the story can't be published

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#172]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When working with the workflow feature and returning to the "none" state the following happens after clicking on the publish button:
![Bildschirmfoto 2020-01-14 um 06 21 29](https://user-images.githubusercontent.com/12159917/72367216-93e12e00-36da-11ea-92a0-80dd14979fef.png)

Unfortunately resetting the state doesn't reset the blockage for publishing the story.
I've tested this on Firefox 72.0.1 (64-bit) and Chrome 79.0.3945.117

**Expected behavior:**

Setting the state back to "none" should allow to publish like expected.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
That's intended behaviour. Otherwise somebody could bypass the "Allow publishing" rule.
