### ISSUE TITLE
Show warning/notification if linked content is deleted/unpublished

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#173]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Storyblok CMS doesn't notify user, if he is deleting or unpublishing content wich is used in other content/page.

**Expected behavior:**
Would be nice to get warning and notification about this consequence:
1. Ask user if he really want to do it.
2. Show user where is the content linked in.

**Note:** No need to solve the situation - user will be able to solve it on his own - just warn about it.

**Comment by onefriendaday** [comment]
You now get a warning when deleting content items. For searching references of items that are getting unpublished you can use the "Containing content item" filter. https://www.storyblok.com/cl/deleting-items-referenced
