### ISSUE TITLE
cached_url is not updated when actual url changes

### ISSUE THREAD

**Issue by cuongtranx** [storyblok/storyblok#174]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [X] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When changing a page/folder's slug in the UI, CDN doesn't update its `cached_url` to reflect the changes

The endpoint being used is https://api.storyblok.com/v1/cdn/stories/4547623?token=token&page=1&cv=always-changed&resolve_links=url

The payload return is: 

```
{
    "story": {
        ...,
        "content": {
            "_uid": "b7875fa7-fade-4727-abe5-1df262b6aa00",
            "body": [
                {
                    "Pin": [
                        {
                            "Link": {
                                "id": "b642ea0e-e9b3-4ccf-972d-96a601421760",
                                "url": "",
                                "linktype": "story",
                                "fieldtype": "multilink",
                                "cached_url": "we_org/en-CA/we-stories/pinned-stories-1",
                                "story": {
                                    "name": "pinned-stories",
                                    "id": 5289312,
                                    "uuid": "b642ea0e-e9b3-4ccf-972d-96a601421760",
                                    "slug": "pinned-stories-1",
                                    "full_slug": "we_org/en-CA/we-stories-new-slug/pinned-stories-1",
                                    "url": "we_org/en-CA/we-stories-new-slug/pinned-stories-1"
                                }
                            },
                            "_uid": "6eb5a050-ae1f-47a1-85fb-0e3b930a5567",
                            "component": "Link"
                        }
                    ],
                    "_uid": "0d91fd15-717e-4e49-a493-20a00f51b3ba",
                }
            ],
        },
        ....
    }
}
```

**Expected behavior:**

As you can see, `cached_url` is different from the story's updated URL, and we expect it to be updated when the slug's changed.

Besides, some of the questions/concerns we have are:
 
- How long until the `cached_url` is updated to reflect the changes? So far, we haven't seen anything yet even with invaliding cache on every request with the `cv` param
- We could possibly use `resolve_links` options, but there's a limitation on 100 links per story, which I believe we might have exceeded.

**Steps to reproduce:**

- Create an internal link object of story-A to (story-B)
- Change the slug of that story-B
- Check the Content API with the endpoints: https://api.storyblok.com/v1/cdn/stories/story-A-id?resolve_links=url&cv=1

**Related code:**

```
insert any relevant code here
```

**Other information:**

This probably relates to #170, but I'm submitting a different bug report since the product/steps to reproduce are different.

**Comment by samuells** [comment]
@cuongtranx thx for reporting this issue. 

We had already few discussion in the team about exactly this behaviour. The property `cached_url` is there because of the historical reasons and I would recommend to use `link.story.url` as this is always up to date url. This was added later and as we don't want to break some older implementation built on the Storyblok CMS we keep also `cached_url`.

check also this link pls : https://www.storyblok.com/cl/url-resolving

cc @DominikAngerer @onefriendaday do you want to something added to this?

**Comment by cuongtranx** [comment]
Thanks for the response, 

The issue we do have right now is we have more than 100 links per page, so resolve them wouldn't be possible.

What we'll probably be doing, for now, is aggregating the list of Links using the `/cdn/links` endpoint (which's several API calls due to pagination), then substitute the URL in wherever we use `cached_url`

**Comment by samuells** [comment]
I discuss it with our dev team and your approach is correct. 💪So no more to say ;)

**Comment by timomayer** [comment]
@samuells thanks for the solution. Is there any plan to increase the resolve limit for this? Imho its not very "user friendly" that you have to collect that information evertime with an additional API call when you have a bigger page with a lot of links, I consider pages with many links something very usual.

**Comment by samuells** [comment]
Hi @timomayer we are not considering pushing this limit atm. Anyway, I will share your input with the dev team. They should be aware of it.

**Comment by samuells** [comment]
Hi @timomayer ... I have good news. This request is/will be addressed in Content Delivery API v2. We have already working on it and we have a working beta. If you would like to try it, write me DM on Discord, please. 😇
