### ISSUE TITLE
add possibility to change the root for clone/merge actions of the dimensions app

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#176]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When using the dimensions app the stories can be copied and merged into the folders inside of the root of the content structure. After the following example it is only possible to copy from one to the other of these folders.

Example Content structure:
/Webpages/....
/Categories/....
/GlobalComponents/.....

**Expected behavior:**

Some data structures need the possibility to set the root for the clone and merge actions into a sub-diretory for example "/Pages". You see that there are different localized versions of the web pages inside. When able to achieve this the content creator can maintain a good structured and embed the multi-tree approach into his site structure without the need to build around it. The actual article about the two main approaches is available here: https://www.storyblok.com/docs/internationalization

Example Content structure:
/Webpages/{region}/....
/Categories/....
/GlobalComponents/.....

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Technically not possible to change.
