### ISSUE TITLE
add passing the actual selected language/translation of a story to plugins

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#178]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Plugin System* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with plugins and changing the language the plugin isn't aware of such switches and can't react based on the locale.

**Expected behavior:**

For being able to create locale aware plugins it is needed to pass the actual language code to the plugin so it can use this information for specialized actions base on languages.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by samuells** [comment]
@Slackman2015 Does this mean to translate the labels in plugin or the plugin is not aware of the current lang version of content?

**Comment by Slackman2015** [comment]
The 2. is the case. The plugin can't access the information which language is being shown in the editor because this information isn't being made available at the moment.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/current-language-in-plugin
