### ISSUE TITLE
Update the link references to page after slug changed

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#179]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
If the slug of the page/content is changed, this change will not propagete into the links on other pages. There is still the old value.

**Expected behavior:**
Update all references of the updated page.

**Comment by onefriendaday** [comment]
Having a website with millions of pages this will introduce a very long background process.
 
That's why there are two solutions we provide:
1. Using resolve_links=url
2. Using the links api to grab an cache alls links that can then be mapped to resolve the link on the client
