### ISSUE TITLE
add possibility to search in multi asset field with the search_term and the filter_query parameter

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#180]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When using the search_term & the filter_query parameters the search doesn't return a result when the search string has occurrences in multi asset fields.

**Expected behavior:**

It would be good to be able to search in the fields of multi assets when search for example pdf files or other assets' occurrences in stories.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
The indexing has been improved so that this fields are included. To reindex please use the management api to save every content item.
