### ISSUE TITLE
add a free text search to the filter menu of the UI

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#182]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The filter menu in the UI allows to search for occurrences of specific components, content types, tags and content type values in stories. The actual way to search for assets requires the user to know the exact name of the field as it is in the JSON data of the stories and the exact search string for example: 
![Bildschirmfoto 2020-01-22 um 07 19 08](https://user-images.githubusercontent.com/12159917/72885868-871a9680-3ce7-11ea-8290-86de84db6145.png)

Image with the actual filter menu - showing the options available:
![Bildschirmfoto 2020-01-22 um 07 05 14](https://user-images.githubusercontent.com/12159917/72884845-926cc280-3ce5-11ea-9306-79bfd48e446f.png)

**Expected behavior:**

For our customers to be able to search easier in their content it would be a great help to have the free text search available because it doesn't require the knowledge how the JSON fields are named and the complete search string looks like.

The free text search needs that the issue https://github.com/storyblok/storyblok/issues/180 gets solved too so that the user can search for assets in the multi asset field as well.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
You can now select from a list of content type values in a dropdown.
