### ISSUE TITLE
add possibility to restore story to last published version without the need to publish it again for being shown as published

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#183]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When the user wants to get back to the last published state of a story because the content has been change in a wrong or not desirable way he needs to choose the version from the last publish action with the light blue dot after its name.

The issue here is that the story will be shown as unpublished and that can be interpreted in a wrong way. For example can the user think that the story hasn't been restored, he needs to publish the story again and build the pages from new or simply gets confused and thinks that he took the wrong story from the list as the states don't match.

**Expected behavior:**

It would be helpful for our customers to see that the actual state matches the state of the story he reverted to.

Additionally I observed that the timestamps used in the version history and the "published at" in the story status menu aren't exactly the same. It seems that the one is from the activation of the publishing process and he other one from the moment the publishing got finished.
To prevent confusion if someone orients himself with those numbers highlighting the latest published version to ensure that the customer picks the right one even when it is the latest one in the list as it is a good orientation in a long list.
It is only a visual amplification for the user to click on the right one. 

![Bildschirmfoto 2020-01-22 um 08 36 21](https://user-images.githubusercontent.com/12159917/72891847-eda5b180-3cf3-11ea-9251-dd2bf1645d16.png)
![Bildschirmfoto 2020-01-22 um 08 36 38](https://user-images.githubusercontent.com/12159917/72891849-ee3e4800-3cf3-11ea-9ffe-968420c20f9d.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
There is no issue here. If restoring to a published version he needs to republish again.
