### ISSUE TITLE
RichText editor is missing new link types.

### ISSUE THREAD

**Issue by SimeonC** [storyblok/storyblok#187]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
In the link (multilink?) field type there is now an option for selecting "email", "asset" type of link.
In the link popup in the RichText editor there is only the option for "Internal Link", "URL" or "Asset".

**Requested behavior:**
I want to be able to select "Email" in the link popup of the rich text editor like I can in the "Link" field type.

**Comment by onefriendaday** [comment]
Has been released
