### ISSUE TITLE
add showing deleted asset folders in trashbin of the assets 

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#188]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When organizing the assets the folders are coming in handy when the count of assets grows. Sometimes there are changes in the organization that needs to be made.
In the case that an editor clicks too fast through the folders list and deletes the wrong folder he needs to start again with organizing the assets into the before deleted folder.

**Expected behavior:**

To avoid the need to invest time into creating the folder(s) from new and organize all the items it would be useful to be able to recover the folder from the trashbin like it is possible with the assets themselves.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
This feature is not planned at the moment.
