### ISSUE TITLE
add possibility to access parent components properties like the this.model attribute

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#189]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Plugin API* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

For being able to access the properties of a parent component the developer needs to fetch the complete content of the actual story and search inside of it using this.uid of the parent component.

**Expected behavior:**

A shortcut to the parent component would help to speed the process of development and the working speed of the plugin itself.
The shortcut could look like this.parentModel or something similar.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
You can get the context like this:

`
pluginCreated() {
  console.log(this.storyItem)
}

// OR by emitting the get-context event
this.$emit('get-context')
this.$onGetContext(() => {
  console.log(this.storyItem)
})
`
