### ISSUE TITLE
add a possibility to manage the tags of stories from one central menu

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#190]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When adding tags to stories so they are easier to find and the count rises to a big number it can be a tedious task to delete them manually per story.

**Expected behavior:**

It would help a lot if there would be a menu that allows to delete them for all stories at once.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

This feature request is based on a community question --> https://forum.storyblok.com/t/where-can-i-manage-the-internal-tags/176

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/tag-manager
