### ISSUE TITLE
Are there any plans for improving multilingual content support?

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#191]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**

When working with links of any type the users need to manually switch to the correct language when redirected to another story. Also those links doesn't contain the actual slug of the translated content. 

**Use-Case from our forum:**

In Storyblok we have the languages DE and EN and we’re using translated slugs.
So far we’re using Storyblok for our blog. So we’re writing our articles in DE and EN.
Sometimes we have to link to other blog articles in the text content (Richtext field, or Markdown field). These links are made via the link selection browser, where you can select the blog article you are referring to. When I create the link in our main language (DE), everything is fine. The link is inserted with the DE slug of course. When I’m switching to the EN version and create the link there, the link is also inserted in DE. As I’m doing the linking by using the link selection browser, I would assume, that the link is inserted in the proper language.

For a few blog articles we could fix it by hand, by just replacing the DE slug with the EN version. URLs are not changing, so this is fine. But we are investigating to use Storyblok for the whole website content with many, many links. It would be too error prone to let the editors fix the links in by hand. Especially if more languages will be supported.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

The question and the use-case are from our forum: https://forum.storyblok.com/t/how-to-link-to-translated-stories-via-link-selection-browser/163/5

**Comment by onefriendaday** [comment]
With this feature https://www.storyblok.com/cl/resolve-links-in-richtext-field you can now use resolve_links=url to include a story object with the local link.

**Comment by fcisio** [comment]
Hi, I am fairly new to Storyblok and using it along with Gatsby and its gatsby-source-storyblok plugin.
I can't figure out how to use API parameters such as this 'resolve_links'.

Any pointers on how to take advantage of this would be greatly appreciated.

Essentially, I'm using translated slug and I want to be able to reference pages with both the link type and links inside richtext, both should include the default slug and the translated one.
