### ISSUE TITLE
add position information of stories &  position of their parent to their JSON

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#192]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When having a lot of items that need to be ordered and filtered and additionally with several levels of folders it is a not very easy task when the data is coming from two different sources.

**Expected behavior:**

With the position of the story and the position of its parent available directly inside of the stories' JSON the code complexity can be decreased by a not unimportant degree.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

This feature request is based on a community discussion:
https://forum.storyblok.com/t/include-a-parent-folder-position-key-in-the-story-object/166
The thread contains additional thoughts of the user and maybe valuable information for this feature request.

**Comment by onefriendaday** [comment]
This will be only possible getting the position from the links api.
