### ISSUE TITLE
strange behavior of the "first published date" field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#193]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

Bug description from the customer:
We noticed a weird behaviour of the “First published date” field.
We have set our timezone to “Europe/Vienna +1”.
Let’s say we have a story and set the date to 2020-02-03 00:00:00.
First (minor) issue: The input field shows “CET” as timezone, although we set it to “Europe/Vienna”. Probably because both has a timezoneOffset of +1.
Second issue: Switching between “Content” and “Config” causes a wrong date to be displayed -> with every switch, “First published date” gets reduced by 1 hour.
First screenshot shows the initial state. Second screenshot shows the state after switching to “Content” and then “Config” again.

A screen record showing how the issue can be reproduced:
[Bildschirmvideo aufnehmen 2020-02-14 um 14.39.08.zip](https://github.com/storyblok/storyblok/files/4205854/Bildschirmvideo.aufnehmen.2020-02-14.um.14.39.08.zip)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

The bug has been reported on our forum: https://forum.storyblok.com/t/wrong-date-in-first-published-date-field-when-switching-between-config-and-content/167

**Comment by onefriendaday** [comment]
1. CEST is the shortcut for central european time which is the right timezone for Europe/Vienna.
2. Second issue has been fixed.
