### ISSUE TITLE
automatic update of asset references

### ISSUE THREAD

**Issue by tppeneva** [storyblok/storyblok#194]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
The assets replace option is not working properly and does not replace the selected file. 
It is possible to upload several files with the same name.
There is no information displayed, regarding where the file has been referenced.

**Expected behavior:**
The replace option should change the file and update the reference links automatically. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
Working on a client project, after a short demo, we got the following feedback for the editors flow: When replacing a file in the assets folder (image/pdf), the file should be automatically updated, as long as the newly uploaded version has the same name. At the moment it seems that the files are not being updated. 
If a new file is uploaded and the content editor does not know well enough the website, they will not know on which pages they need to update the references. It would be helpful to display information where/on which pages/ this particular file has been referenced.

**Comment by onefriendaday** [comment]
References can now be shown: https://www.storyblok.com/cl/show-asset-references
