### ISSUE TITLE
add component presets dropdowns

### ISSUE THREAD

**Issue by tppeneva** [storyblok/storyblok#195]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Component presets are displayed as a list.

**Expected behavior:**
For a large number of component presets, the list should be displayed as a drop down list.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
On the current project, we have a large number of components with at least 10-20 presets for each component. This results in a long list of presets, that the editors need to search and scroll through. We got the suggestion that it would be easier for work to have drop-downs for each component and have the presets shown only for the selected component.

**Comment by onefriendaday** [comment]
Thank you for that suggestion. We may use a new UI for the preset selection in a redesign and that's why we are closing this for now.
