### ISSUE TITLE
Add option for allowing custom user roles to create and edit presets

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#196]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it isn't possible for users below the admin to edit presets. That means that only a handful of people can create presets when they are needed as a preparation for new content and changes but the most work of maintaining the content is done by editors.

**Expected behavior:**

For better workflows without giving unnecessarily too much power away where it isn't needed it would be a very important feature to have the possibility to create a custom user role that allows when assigned to a user to do exactly that what he should and be able to do.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
For editors we recommend to use a content template page and just copy their personal "presets" via the copy and paste function. Copy and paste also works accross browser windows.
