### ISSUE TITLE
Add functionallity that the owner and/or his admins can remove the workflow completely from a story

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#197]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment the owner and his admins aren't able to remove an applied workflow to a story. The issue with this is that when the editors should be able to publish a story again and the state needs to stay on "ready to publish" and is marked in the item overview.

**Expected behavior:**

For usability and flexibility reasons it would be necessary that at least the higher ranked user roles can remove the workflow entirely from a story so that the focus isn't attracted from those stories where it isn't actually needed anymore.

A case for a conflict could be that an editor isn't allowed (story isn't in the white list) to edit a story but it stays marked as ready to publish for other custom user roles.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
The goal of workflows is that everybody sticks to the same workflow. The admin user needs to assign the content item to Draft again if he wants that the user edits a story. You can also create a workflow stage that allows more users to publish. For example "Ready to publish for all users".
