### ISSUE TITLE
Add functionality to upload table content to translatable-table field plugin from local storage

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#198]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When the user needs to enter data into the translatable-table field he has to enter the data manually or can use an external JSON as the source. This can be a problem when he as a lot of data to import and doesn't have the time to write a custom script for this task.

**Expected behavior:**

For saving time and an improved usability when maintaining the data of the translatable-table field it would be important to have an import function so it gets easier to get larger amounts of data into the table field.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
We recommend that the user creates a custom plugin with that functionality.
