### ISSUE TITLE
There is a problem when i want to resend confirmation email. No email coming to me.

### ISSUE THREAD

**Issue by kutluhann** [storyblok/storyblok#20]
**The issue occurs while working with:** (check one with "x")   
- [x ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x ] bug report  
- [ ] feature request  
- [ ] question

There is a problem when i want to resend confirmation email. No email coming to me.

**Comment by onefriendaday** [comment]
Hi! I just sent you an email with the log we found and you should now be able to login. It looks like a spam filter problem.
