### ISSUE TITLE
Keep clipboard content after pasting

### ISSUE THREAD

**Issue by FabianFinke** [storyblok/storyblok#200]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**
The clipboard gets cleared after pasting and contents can get lost if you cut & paste into a forbidden block.

**Expected behavior:**
Not clearing the clipboard would allow pasting components multiple times and it would be in line with the copy & paste functionality in almost any other app. Additionally you wouldn't have the risk of losing content when cutting & pasting.

**Steps to reproduce:**
Copy & paste a component

**Comment by DominikAngerer** [comment]
You can use the Clipboard History app – the history will than be available in the "Tools" tab: https://www.storyblok.com/apps/clipboard

**Comment by FabianFinke** [comment]
I know. The clipboard history has it's own problems though. Its hidden inside the tools tab and it only shows the name of the component (which makes it a guess game if you copied multiple text components for example). But most of all it doesn't allow pasting multiple times either without going back and forth.

What I'd suggest is to ditch the clipboard history app and integrate the functionality into the blocks. Don't clear the clipboard after pasting and add a "Paste" button beside the "Add block" button instead of replacing it. Next to it could be an arrow which triggers a dropdown with the last 5 history items with the name and the preview field.
