### ISSUE TITLE
Add option to user role rights management to make component fields/tabs read-only but still visible

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#202]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is only possible to hide component fields in the "Component field permissions" list field.

**Expected behavior:**

In some cases it is needed to be able to see such components and complete tabs with the component fields inside still so the users that aren't able to edit but to check them if anything is wrong with their content.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
To create a read only field we recommend to use a custom field type.
