### ISSUE TITLE
Issues with updating the link types URL + internal Link inside of a rich-text field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#203]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

Case 1: 
When marking a text and apply the option Link to it and choosing the link type "internal Link" it is not possible to change the target anymore:
[Bildschirmvideo aufnehmen 2020-02-21 um 14.29.30.zip](https://github.com/storyblok/storyblok/files/4237284/Bildschirmvideo.aufnehmen.2020-02-21.um.14.29.30.zip)

Observation: While testing I perceived that I couldn't see the data that has been saved in the second Link in both Rich Text 1 and 2 fields. The links have been created by copying the links before. This issue has been reported partly by the following report https://github.com/storyblok/storyblok/issues/116 but additionally the data is existing in the JSON but not shown at all.
Here is the screen cast from my own test:
[Bildschirmvideo aufnehmen 2020-02-21 um 14.42.22.zip](https://github.com/storyblok/storyblok/files/4237348/Bildschirmvideo.aufnehmen.2020-02-21.um.14.42.22.zip)

Case 2:
When using rich-text fields inside of a blok field the link isn't changing generally when updating the value of the URL.
[Bildschirmvideo aufnehmen 2020-02-21 um 14.54.15.zip](https://github.com/storyblok/storyblok/files/4237374/Bildschirmvideo.aufnehmen.2020-02-21.um.14.54.15.zip)

**Steps to reproduce:**

The space with the ID 73455 can be used for testing.
Case 1 relates to the field "Richt Text 1".
Case 2 relates to the field "Blok 1" and the embedded/nested rich text fields.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Solution: You need to select the whole text to set the link.
