### ISSUE TITLE
strange behavior of the link fieldtype when used in an in a rich-text embedded component

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#204]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When changing the type of a link field that is embedded in a blok and inserted into a rich-text field the data that has been written by the internal link remains partly in the JSON. This can be seen in the following image:
![Bildschirmfoto 2020-02-21 um 15 28 49](https://user-images.githubusercontent.com/12159917/75061237-0fdf4a80-54bf-11ea-9e1c-d337e2ae040f.png)

Additionally the radio buttons are acting strange. It doesn't suffice to click them once to see that they are already marked:
[Bildschirmvideo aufnehmen 2020-02-21 um 15.10.41.zip](https://github.com/storyblok/storyblok/files/4237477/Bildschirmvideo.aufnehmen.2020-02-21.um.15.10.41.zip)

**Steps to reproduce:**

The case has been reproduced in the space 73445 and the link to the story is:
https://app.storyblok.com/#!/me/spaces/73455/stories/0/0/5728293
The for testing used field is "Richt Text 4".

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
