### ISSUE TITLE
change standard setting from "Include associated alternates" selected to unselected

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#205]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with the dimensions app and deleting one of the alternates of a story the standard setting looks like this:
![Bildschirmfoto 2020-02-25 um 09 52 29](https://user-images.githubusercontent.com/12159917/75250227-a315ca00-57b6-11ea-9b27-e93031d4bdc3.png)
This makes it necessary to uncheck the option "Include associated alternates" when the user wants to delete only one alternate story and this is used in most cases.

**Expected behavior:**

For preventing  the unwanted deletion of important stories it would be a more secure way to offer the deletion dialog with the option "Include associated alternates" unchecked like in the image visible:
![Bildschirmfoto 2020-02-25 um 10 09 08](https://user-images.githubusercontent.com/12159917/75250393-0a337e80-57b7-11ea-8147-4fafaefa6c98.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Unselected alternates are now the new default.
