### ISSUE TITLE
add possibility to export users list of an organization and to add additional information about users

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#206]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

With growing size of projects the count of users in an organization grows as well and it isn't easy to distinguish between own staff, external workers or customers with company email addresses.

**Expected behavior:**

With the possibility to organize the users into groups and add additional information to single users to set them into context (commentary function) with any of those projects it would be easier to control the users access to company resources and remove them when they aren't needed anymore.

Additionally it would be helpful to be able to export the complete list for example to a pdf file that can be downloaded when generated.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
In this case we recommend to use SSO of your organization. You can export the users with the management api.
