### ISSUE TITLE
add possibility to freeze the content of a space for certain usergroups for maintenance reasons

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#207]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

In the case that the space needs to be locked so that only certain users or user-groups can make changes to the content and its structure it is needed to modify all the users by hand. This can be a time consuming task when there are a lot of users in the collaborators list.

**Expected behavior:**

The possibility to select user-groups or single users to prevent them from making changes to the content and its structure would be a very time saving feature that could help making maintenance much easier.
Additionally there wouldn't be the need to make alterations to any user-role and that prevents further issues.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/maintenance-mode
