### ISSUE TITLE
adopt the releases app for considering the data/changes from the dimensions app

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#208]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When using the dimensions app inside of a release the changes are applied to the structure of current and not to the actual release.

**Expected behavior:**

For a better work with both the releases app and the dimensions app it is important that the dimensions app applies changes only to the actual and selected release.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
The actions of the dimensions tab "Overwrite" and "Merge" are now applying changes only in the selected release. The "Create" action still applies to the "Current" structure as it is when you create a new content item.
