### ISSUE TITLE
change behavior for view settings of assets to be saved permanently or at least just for the session

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#209]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

1. When opening the assets manager by clicking on button of a field the setting which asset folder has been watched as is lost and the user needs to open the folder again.
2. When choosing a folder in the asset manager and leaving the asset manager and coming back the folder is still marked but the shown content is from the all folder. Same applies when trying to upload a new asset to the selected folder after coming back the new uploaded asset ends up in the "All" folder

**Expected behavior:**

It would be a time saver that at least for the time of the session the view settings would be saved in order to make it easier to work with the asset manager.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
