### ISSUE TITLE
Taglist Plugin doesn't work.

### ISSUE THREAD

**Issue by kutluhann** [storyblok/storyblok#21]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

Taglist Plugin doesn't work.

**Comment by DominikAngerer** [comment]
Hey there - the `taglist` plugin allows you to select Tags that are already created. To create tags, so they are available, you can navigate the the "Config" tab of one content entry create those you like and than, after saving it once those are available and will be shown as checkboxes.


## Config Tab:

![bildschirmfoto 2018-10-02 um 09 59 47](https://user-images.githubusercontent.com/7952803/46336106-151dca00-c62a-11e8-8cb8-96834d82738a.jpg)

## The Plugin:

![bildschirmfoto 2018-10-02 um 10 01 21](https://user-images.githubusercontent.com/7952803/46336128-2666d680-c62a-11e8-91e1-28921a829c69.jpg)

## Sourcecode

The Source code, if you want to custome the appearance. 

```
const Fieldtype = {
  mixins: [window.Storyblok.plugin],
  template: `<div>
    <label class="uk-margin-right uk-margin-bottom uk-display-inline-block" v-for="tag in model.tags">
      <input type=checkbox v-bind:value=tag.name v-model=model.tags class=uk-margin-small-right> {{ tag.name }}
    </label>
  </div>`,
  methods: {
    initWith() {
      return {
        plugin: 'your_plugin_name',
        tags: []
      }
    },
    pluginCreated() {
      console.log('plugin:created')
      this.api.get('cdn/tags', { version:"draft" }).then((res) => {
        this.model.tags = res.data.tags;
      });
    }
  },
  watch: {
    'model': {
      handler: function (value) {
        this.$emit('changed-model', value);
      },
      deep: true
    }
  }
}
```

**Comment by kutluhann** [comment]
Thanks a lot :)

**Comment by dohomi** [comment]
Just came across this issue and published a small plugin based on vue-multiselect, in case its of use for anybody else:
https://github.com/dohomi/storyblok-fieldtype-tag-select
