### ISSUE TITLE
add possibility to choose more than one content type for folders and that sub-folder inherit the configuration from parents by choice

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#210]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Currently it's possible to restrict folders to a certain Content Type, however it's only possible to set one and those settings aren't inherited by sub-folders.

**Expected behavior:**

It would be great if the user could set multiple Content Types for a folder. 

It would also be great if the Content Type restrictions could be inherited (or specifically be set to inherit). I.e. If I create a Folder 1, and set Content Type 1 and Deny Changing; when creating Folder 2 under Folder 1, this should automatically be able to inherit the restrictions from Folder 1 (either by default, or by choice on Folder 1)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
As an alternative we recommend to use the following new setting to at least be able to restrict which content type the user can select: https://www.storyblok.com/cl/component-creation-permissions
