### ISSUE TITLE
add the functionality to allow to set the standard mode for visualization to "form only" or "preview" in the folder settings but without locking it

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#211]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is possible to set the folder settings to "form only" to deactivate the view settings completely for the stories inside of a folder and show the stories only in form only mode. The other way is to set the the view mode accordingly for the needed mode but this can. 

**Expected behavior:**

In the case that the customer has many pages without the JS bridge installed and a few pages with the JS bridge integrated this can be a repetitive task that could be solved by adding an option to the folder settings to change default view setting to form only or preview of a folder instead of locking it only to form only. 

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
We recommend to use a different folder structure here to only put "form only" items in a specific folder.
