### ISSUE TITLE
add functionality to unpublish releases completely, scheduling for unpublishing of releases

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#212]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

With the releases app it is possible to schedule releases and modify the content to a certain time when the users wishes. Unfortunately it isn't possible to revert the changes easily in our UI

**Expected behavior:**

It would be a great functionality to be able to unpublish releases and to be able to schedule these too. It would be important to restore the former state of the stories to the one they had before (published/unpublished).
Such a feature can be useful when dealing with seasonal content that changes for only a few days or weeks.

Also the scheduled unpublishing feature of a release should offer an option to either delete it after unpublishing or keeping it.

Additionally it would be great to have the information available for how to control this feature with our management API.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Releases are not made for this use case. For scheduling content we recommend to use a scheduler component with an start and end-date or a content type with start and end-date.
