### ISSUE TITLE
add possibility to share plugins between usergroups that aren't in an organization and don't want to make plugins public to all users

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#213]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment it is only possibility to share the plugin in a space between the owner and the collaborators when the owner of a space publishes the plugin in the plugin settings under https://app.storyblok.com/#!/me/plugins
In the case that the user wants to share the code of the plugin or wants to share it with other users who aren't in a space with him it isn't possible without an external repository from where the users need to take the code of it and actualize it in the plugins page.

**Expected behavior:**

It would be a great thing when a user could select user to share a plugin with and eventually even be able to choose if the code should be exposed or not without the need to use external repositories anymore.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
You can now collaboratively work on plugins with a partner account http://app.storyblok.com/#!/partner-signup
