### ISSUE TITLE
BuildError on Bundlephobia

### ISSUE THREAD

**Issue by bdrtsky** [storyblok/storyblok#214]
**The issue occurs while working with:**
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* 

**I'm submitting a ...** 
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
`storyblok-js-client` doesn't build on Bundlephobia. It's a rare to see when library fails to build there. And I was curious how much it weights (I need just rich text builder, not realtime page preview, and looks like you don't ship it separately).
https://bundlephobia.com/result?p=storyblok-js-client

**Expected behavior:**
build on Bundlephobia

**Steps to reproduce:**
Go tot url https://bundlephobia.com/result?p=storyblok-js-client

**Comment by vabatta** [comment]
It does build and weights 79.7kB Minified and 26.1kB Minified + Gzipped.

**Comment by bdrtsky** [comment]
![Screenshot from 2020-03-26 23-54-08](https://user-images.githubusercontent.com/45076741/77700568-20527b80-6fbd-11ea-8418-c05b54fdaf82.png)
