### ISSUE TITLE
change behavior of UI for one getting back to the tab where a blocks field has been clicked on

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#215]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When clicking on a blocks field that is being located in a tab and trying to get back to the tab that has been selected first it leads to the "General" tab back when clicking on the back button of the browser. Demonstration: 
[Bildschirmvideo aufnehmen 2020-03-11 um 13.53.28.zip](https://github.com/storyblok/storyblok/files/4319576/Bildschirmvideo.aufnehmen.2020-03-11.um.13.53.28.zip)

**Expected behavior:**

For a better usability it would be nice to get back to the tab that has been selected before.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
We recommend to put "Blocks" fields only on the first tab here.
