### ISSUE TITLE
add possibility to sort with "sort_by" parameter using more than one field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#216]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When using the sort_by parameter it is possible to sort by just one field like for example the position, the created_at field etc

**Expected behavior:**

The usability of the sort_by parameter could be greatly improved by adding the possibility to sort by a list of fields like it is possible with the filter_query parameter.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/multiple-sort-by
