### ISSUE TITLE
add functionality to releases app to be able to select only needed folders of the root to create a release when having a multi project/tree setup inside of a space

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#217]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When using the releases app it is not possible to choose only parts of the content like a folder or even folders in the root of the preview branch to create a release.

When using this feature and a multi tree setup of any kind it can lead to following issues:
- previous changes in different parts of the trees can be accidentally overwritten when the wrong items are getting edited in the releases
- trees of the content structure can't be edited independently from each other as the complete content gets added to the releases
- another problem arises in the combination of multi trees + releases, the complete content gets into branches as well

**Expected behavior:**

There are different approaches that could help to solve the mentioned issues:
A) The user can choose the folders or stories to deploy manually from a release.
Pro:
- it is a very flexible solution
- the user doesn't need to configure many thing to use this

Contra:
- can be confusing to the user when there are many different
- problems can arise when accidentally something gets overwritten that should remain in one of the branches
- adding options to the user rights management to regulate the access to the trees releases can be tricky because there is no separation for the different trees

B) The user can create a release out of a selection from the content folders.
Pro:
- can prevent the issue with accidentally overwriting of content that has been change before when setup and used correctly
- better control about what can be edited in a release
- could be easier to control, adding options based on the releases could suffice to prevent harmful use

Contra:
- needs to be configured every time when a release gets setup
- takes more time to prepare

Addition to B)
--> because of the more complex nature it could be necessary to be able to reuse the configuration for the releases, maybe similar to presets of components

This feature request adds some new aspects to a previous request https://github.com/storyblok/storyblok/issues/212

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
This will need to more complexity. If the user wants to "release" only specific folders he should create a specific release for that and only work inside the folder. He can click "Show only items from this release" and look for items he doesn't want to publish and move them to another release by copying over the values and then click "Discard changes".
