### ISSUE TITLE
Prevent iframe width change after the width of sidebar is changed

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#219]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Any chance that iframe window of the content, would not refresh/reset to top, if the content sidebar width is change?

**Expected behavior:**
After the change of the sidebar width, the iframe will stay active on the same component as it was.

**Steps to reproduce:**
https://www.dropbox.com/s/kotv37r2ayh3x6s/Kapture%202020-03-17%20at%2013.50.12.mp4?dl=0

**Comment by onefriendaday** [comment]
Has been fixed.
