### ISSUE TITLE
add "display name" to the list of the components in the components tab in a second column

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#221]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with the field "display name" in the component's configuration can the technical name that can be much short and cryptic be hidden. Unfortunately that doesn't reflect in the components tab where it will be difficult for a user who only knows the display name to find the components quickly.

**Expected behavior:**

A second column for the "display name" in the components list could help to find a certain component much faster when a user is accustomed to the "display name" of the components.
![Bildschirmfoto 2020-03-18 um 07 07 47](https://user-images.githubusercontent.com/12159917/76949520-689bda80-68e7-11ea-8f2e-8c6505a4b296.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Released in https://www.storyblok.com/cl/improved-component-list-view
