### ISSUE TITLE
GraphQL introspection does not work

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#223]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* <!-- => gapi.storyblok.com

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
GraphQL Introspection doesn't work. Error is being thrown:
```
GraphQL Introspection Error
		A valid schema could not be built using the introspection result. The endpoint may not follow the GraphQL Specification. The error was:
		"Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was 'tab-179390ed-4cd4-47bd-bd94-8902f461c9bc'".

graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was 'tab-179390ed-4cd4-47bd-bd94-8902f461c9bc'
	at graphql.Assert.assertValidName(Assert.java:107)

```

**Expected behavior:**
Introspection should work

**Steps to reproduce:**
Create .graphqlconfig and add following content:
```json
{
  "schemaPath": "schema.graphql",
  "name": "StoryblokAPI",
  "extensions": {
    "endpoints": {
      "dev": {
        "url": "https://gapi.storyblok.com/v1/api",
        "headers": {
          "Token": "YOUR_TOKEN_ID",
          "Version": "draft"
        }
      }
    }
  }
}

```
This error happens in Webstorm most recent version, not sure if other IDE's are having the same issue

**Comment by onefriendaday** [comment]
Has been fixed. Could you please try again?

**Comment by dohomi** [comment]
@onefriendaday yes works again! Thanks for the fix 💯
