### ISSUE TITLE
Forward current usergroup into editmode view 

### ISSUE THREAD

**Issue by PhilippLupo** [storyblok/storyblok#226]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently there is no way to find out within your project and not the Storyblok interface which user is editing the current site. 

**Expected behavior:**
The current user, or atleast the usergroup of the user, which is editing the site should be forwarded to the application/project itself. For example within the "_storyblok_tk" Parameter.

**Comment by samuells** [comment]
Hmm, I am not sure if I understand expected behavior. Could you try to describe it a little bit more? Under the site you mean an entry?

Do you want that content editors are directly forward to the space/project you choose in the storybook app and they are not offer that spaces/project overview?

**Comment by PhilippLupo** [comment]
Hey, sorry for my weak use of Storyblok terminology. I will try to explain it:

The Storyblok interface loads within its editmode the website (application, project, site, environment, I am not sure how you may call it) via iframe. Therefore a request is made with following parameters
https://mysuperniceproject.com/en/?_storyblok=12345&_storyblok_c=ctype&_storyblok_tk[space_id]=12345&_storyblok_tk[timestamp]=12345&_storyblok_tk[token]=1234&_storyblok_version=&_storyblok_lang=default&_storyblok_release=0

This request forwards some parameters to my app, so that I can check for example, if my app is called from the Storyblok interface (editmode). What I would like to get, in best case also just as the other parameters, would be the user (or atleast the usergroup that is assigned to him) of the current user who is viewing this page via the Storyblok interface.

I hope that made it a bit more clear :)

**Comment by DominikAngerer** [comment]
This will not be implemented as this would couple your website with the Storyblok preview. For integration you can now use our App set-up instead: https://www.storyblok.com/docs/authentication-apps
