### ISSUE TITLE
Blacklist (or whitelist) nestable components from being selected depending on user roles

### ISSUE THREAD

**Issue by onefriendaday** [storyblok/storyblok#227]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently any user can insert any component.

**Expected behavior:**
Possibility to blacklist (or whitelist) nestable components from being selected depending on user roles.

**Comment by DominikAngerer** [comment]
related to #234

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/component-creation-permissions
