### ISSUE TITLE
Swap the component name and preview text in content editor.

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#229]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Current behavior:*
In the editor view is the component name - big prominent and preview value small gray text. There were multiple requests to swap this.

![image](https://user-images.githubusercontent.com/5185019/78226095-7fd3ee00-74cb-11ea-90ed-1281f5326259.png)

**Expected behavior:**
Preview text should be dominant (big black) and the name of the component should be secondary - smaller gray text.

**Comment by onefriendaday** [comment]
This has been discussed internally already and we think the description is the less important information. There are also sometimes components that don't have a description/preview.

**Comment by samuells** [comment]
Could we let decide the user who defines the component? I don't see a big implementation issue there. Maybe a simple checkbox which value should act big a which as small as I see use case for both approaches and this could vary from situation to situation.
