### ISSUE TITLE
Add ability to pass a custom value when executing a Task

### ISSUE THREAD

**Issue by programbo** [storyblok/storyblok#23]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Clicking the Execute button for a task calls a webhook 👍🏽

**_Desired_ behavior:**
It would be nice to have a prompt to add some extra data to the webhook URL at execute time. At the moment I have multiple tasks that do the same thing, but each passes a different `?confirmation_address=<custom email address>` query parameter at the end of the webhook URL to notify someone when their deployment has finished. Having a single URL with a placeholder that gets replaced at execution time would be much niftier.

**Comment by DominikAngerer** [comment]
Has been added: https://www.storyblok.com/cl/user-dialog-tasks-app we're using the actual payload rather than the URL as we're already sending posts.
