### ISSUE TITLE
Notification that another editor opened entry in editor view

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#230]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Expected behavior:**
It would be nice to have a pop-up notification with a warning that another content editor opened the entry and wants to edit it. Just notification would be nice for the beginning.

**Comment by DominikAngerer** [comment]
Invalid FR format. Please dont delete headlines.

**Comment by onefriendaday** [comment]
This enhancement will come in Q4: https://www.storyblok.com/features#storyblok-v2
