### ISSUE TITLE
Enable folder-specific sorting settings

### ISSUE THREAD

**Issue by alaehr** [storyblok/storyblok#231]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
I any one folder I can set a sorting. This affects all folders.

**Expected behavior:**
I want to set a standard setting in the project and be able to change it for specific folders. This setting should persist until I change it.

**Comment by onefriendaday** [comment]
We think it's more user friendly to have one central place to change the sorting. It may lead to more confusion if sorting changes in every folder.
