### ISSUE TITLE
Number field sorts alphabetically and not numerical

### ISSUE THREAD

**Issue by pbender87** [storyblok/storyblok#232]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [X] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Sorting by a field type of number does not work like expected. 
Storyblok / Javascript sorts alphabetically. This means that 10 is lower than 5, because 1 is lower than 5.
This results in an ordered list of 1, 10, 5

**Expected behavior:**
My expectation is an ordered list of 1, 5, 10

**Steps to reproduce:**
Create an input field of type number in the schema
Create some stories and fill in the numbers 5, 10, 1
Order by this number field

**Related code:**

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
