### ISSUE TITLE
Resolve nested relations in level 2 or deeper

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#236]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Expected behavior:**

Would be nice to have possibility to `resolve_relations` of already resolved relations.

```
story: {
  relations_level1: {
    relations_level2: {
      // this is currently not possible to resolve - only the level 1
    }
  }
}
```

**Comment by onefriendaday** [comment]
This is not possible to implement due technical reasons.

**Comment by dlhck** [comment]
@samuells we built a package for that: https://github.com/alpin11/storyblok-deep-relations-resolver

**Comment by samuells** [comment]
@dlhck that is really cool. @alexjoverm @manuelschroederdev is this something for you?
