### ISSUE TITLE
Editable content on staging "branches"

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#239]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
The content on branches is shown in editable fields, which is confusing as this content can be changed only in `preview` branch.

**Expected behavior:**
The input fields of branches other then `preview` should be disabled.

**Comment by onefriendaday** [comment]
The user can not save anything so I don't consider this as a bug. We could impliment read only fields but it would be a nightmare if every plugin editor would need to create a seperate "read-only" view.

**Comment by samuells** [comment]
The issue is that you can edit it and if you leave the entry you are even prompted by popup that you have unsaved changes.

**Comment by onefriendaday** [comment]
Right, that popup will be removed.
