### ISSUE TITLE
Any way to get localised links?

### ISSUE THREAD

**Issue by palmfjord** [storyblok/storyblok#24]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question
<strike>
**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
</strike>

**Other information:**

Is there any way to get localised/translated stories (ie. both `/home` and `/en/home`, translated using [Single tree and field level translation](https://www.storyblok.com/docs/internationalization#option-1-single-tree-and-field-level-translation)), from the links endpoint? As it seems now i can't see them in the `/v1/cdn/links` endpoint. Unsure if i'm doing something wrong, if this is a bug or a feature request :) Would be awesome to be able to get the translated stories into our sitemap at least.

Thanks for an amazing product, cheers!

**Comment by onefriendaday** [comment]
Hi!
As the stories using the field level translation are the same entity in all languages creating a sitemap is as easy as looping over the links and prepending the language code to the slug property.

For example:
```js
let allLinks = []
let languages = ['de', 'it']

languages.forEach((language) => {
  for (let link in links) {
    allLinks.push({
      slug: `/${language}/${links[link].slug}`,
      name: links[link].name,
      language: language
    })
  }
})
```

**Comment by palmfjord** [comment]
@onefriendaday Ah got it! Makes sense now :) thank you!

**Comment by awacode21** [comment]
But if you want to render you navigation links in page, ja have slugs for different languages, but the link name displayed stays the same language?? How to show translated navigation links to the user?

**Comment by DMouayad** [comment]
> But if you want to render you navigation links in page, ja have slugs for different languages, but the link name displayed stays the same language?? How to show translated navigation links to the user?

@awacode21 I'm sorry this's an old comment, but I'm trying to find a way to get translated slugs/names for the links. Did you manage to get it working?

**Comment by awacode21** [comment]
Translatable Slugs are not part of the free plan, you need to have at least the "Entry" pricing package to use them. As i am on free plan i cannot answer you how to use/get them working once you are on Entry plan.

With free plan you are able to translate your whole stories, but not the urls

**Comment by DMouayad** [comment]
@awacode21 oh Ok :) appreciate ur help any way. I guess the simplest option is making two requests: one to get "uuids" and the other to get the actual stories by uuids.

**Comment by awacode21** [comment]
May i did not understood your problem correct. Can you explain more your case and what i try to achieve?

**Comment by DMouayad** [comment]
@awacode21 yeah sure I was just about to explain it for anyone reading this in the future.
I wanted to get the links and names of certain stories and i only need those 2 fields so i decided to use the 'links' endpoint instead of fetching the whole Storyblok and now thinking again about this approach (after a long search if it's applicable for my use-case), I guess I'll use the 'stories' endpoint anyway.
