### ISSUE TITLE
Image service rotates images

### ISSUE THREAD

**Issue by claudio147** [storyblok/storyblok#240]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Sometimes if I upload an image which has a portrait orientation i check it with the assets url -> it looks ok. But when I open the same image with the "img2.story.." image service url the image has the wrong orientation. Looks like it's rotates the image automatic.

**Expected behavior:**
The image service should not rotate the image.

**Steps to reproduce:**
Upload an image (portrait) and check it's rotation in the image service. (I couldn't find the key why it's rotate, some images are working and some not – also with the exact same dimension).

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
It could be that your images have EXIF metadata with rotation information. You could save your images without metadata with a service like this https://www.verexif.com/en/ or use the image service rotate filter img2.storyblok.com/filters:rotate(90)/YOUR_IMAGE.
