### ISSUE TITLE
Webhooks for datasources

### ISSUE THREAD

**Issue by thomasbit** [storyblok/storyblok#241]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently no webhooks are available for changes to datasource entries. We are using datasources for a quite big amount of data which is not changed very often. (snippets, redirect urls, other..) The data is locally cached and we therefore have to periodically fetch all data even though 99% of the time nothing has changed.

**Expected behavior:**
It would be great if one could configure webhook endpoints which is triggered in case entries of a datasource are modified.
A minimal implementation could be, that a webhook is triggered as soon as any entry in a datasource is changed - whithout listing the specific entries.
This could be extended by providing the specific entries, which have been changed in the payload.

Thx :)

**Comment by Slackman2015** [comment]
Hello @thomasbit,

this feature has been implemented. You can find this webhook under "Datasource entry saved" as explained here https://www.storyblok.com/docs/guide/in-depth/webhooks#datasources

Best regards
Hannes
