### ISSUE TITLE
search_query for root fields like full_slug

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#245]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Only component fields can be filtered

**Expected behavior:**
Add possibility to use search_query over component root fields like `full_slug`

```js
filter_query: {
      'full_slug': {
        'not_like': '*demo-stuff*'
      }
    }
```

Usecase would be to fetch all items for a sitemap.xml or any feed.xml

**Comment by dohomi** [comment]
this would be especially useful if #94 would be implemented

**Comment by onefriendaday** [comment]
Putting the query possibility into the filter_query would not be compatible with existing implementations. If someone has full_slug defined in their content type it would conflict with the query.
 
What about using 
~~~
filter_query: {
  exclude_from_sitemap: {
    is: 'false'
  }
}
~~~
This filters all items that have exclude_from_sitemap unchecked or undefined.

**Comment by dohomi** [comment]
@onefriendaday thanks for your idea. The problem I was facing is, that I want to define a folder and all content of that folder should be ignored. `exclude_from_sitemap` would require to enter all content items and add the property.

If you would prefix root values with `__root:{/* ROOT_FIELDS */}` this might be non-breaking syntax? Just as an idea for moving away with `starts_with` syntax and combine it with other filters

**Comment by onefriendaday** [comment]
I think this new feature would help to solve your usecase: https://www.storyblok.com/cl/filter-by-multiple-slugs

**Comment by dohomi** [comment]
@onefriendaday thats great news. Is it possible to combine/use both `by_slugs, excluding_slugs` in one query statement? 
```js
by_slugs:'de/*',
excluding_slugs:'*demo-content*'
```
