### ISSUE TITLE
add 'presets' to storyblok CLI sync type

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#246]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* CLI

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
folders, components, roles and stories are available to be synced

**Expected behavior:**
add the possibility to sync `presets` as --type
```
$ storyblok sync --type components,presets --source 00001 --target 00002
```
Thanks for consideration

**Comment by onefriendaday** [comment]
Has been merged.
