### ISSUE TITLE
visualize / receive list of used components inside of a space 

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#249]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* CLI

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
It is currently possible to define components and use them in storyblok. But for nested components its unclear which component actually has been used/referenced inside of a space.

**Expected behavior:**
It would be great if its possible to see which components are actually being used by a space. This would be great either inside of the components list similiar like "Tags => Assigned Items". Alternatively a CLI command could be useful as well.

**Other information:**
This feature would come in handy, if many spaces are sharing the component list but not all components are being used by each space. This could give the developer an easy way of reducing the bundle size of each project to the minimum

**Comment by DominikAngerer** [comment]
Hey there!

With this script you can access a list of all unused components: https://www.storyblok.com/faq/how-to-get-all-unused-components

We've added a filter to the management API that allows for such a query option, currently an UI implementation is not available.

**Comment by dohomi** [comment]
@DominikAngerer nice I haven't seen that article 👍
