### ISSUE TITLE
Duplicate space via Management API is not working

### ISSUE THREAD

**Issue by jernejlipovec** [storyblok/storyblok#25]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [X] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [X] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
When duplicating a space with POST to /spaces and specifying space.dup_id, it seems that duplication is never done, but instead simply new empty space is created. It does not even work when I have "Make this space duplicatable by all users" enabled.

**Expected behavior:**
I would expect space.dup_id to be respected and space completely duplicated (as it is via UI panel).

**Steps to reproduce:**
Trigger a ["Duplicate a space"](https://www.storyblok.com/docs/api/management#core-resources/spaces/duplicate-space) request for a space you own.

**Comment by onefriendaday** [comment]
Hi!
Thanks for the bug report.
The issue is that the documentation is wrong.
dup_id needs to be at the root level.
I aleady created a hotfix for the documentation:
https://github.com/storyblok/storyblok-docs/pull/16/files

Cheers,
Alex

**Comment by jernejlipovec** [comment]
Thank you for your response! Your solution worked for me.
