### ISSUE TITLE
moving many pages from one folder to another results in unexpected errors

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#252]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Moving pages/content from one folder to another can result in error messages which are unexpected

**Expected behavior:**
All pages/content should move without error.

**Steps to reproduce:**
Select more than 5 (I don't know the current restrictions) pages to move from one folder to another. Some of the `PUT` requests are failing (for unknown reasons)
 
**Other information:**
```
Ups, there where some problems:
There was an error processing your request. Please check your query parameters and the payload.
```
It seems there are network restrictions of moving too many pages at once. But its not clear how many can be moved.

**Comment by ademarCardoso** [comment]
Hi @dohomi , thanks so much for submitting this bug, but could you give me more information or screenshots? Because I tried to reproduce the bug and I couldn't.

**Comment by dohomi** [comment]
@ademarCardoso I can't reproduce it all the time. It might be connected to network issues on client side.

**Comment by onefriendaday** [comment]
I also could not reproduce it. If it happens again please send us the space id and if you remember the folder you tried to move items from and to.
