### ISSUE TITLE
An easier way to import data

### ISSUE THREAD

**Issue by muhammedjenos** [storyblok/storyblok#253]
**The feature would affect:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
For users who want to migrate from other databases to Storyblok, importing large amount of HTML data (like blog posts for eg..) to Richtext field is not straight forward as the RTE only accept data in a specific json format. 

**Describe the solution you'd like**
I would like to get a full Nodejs method to import data with images. Common use case it uploading bulk data like blog posts or press releases which also has links to images which will not be resolved in Storyblok as the links are created dynamic. 

Let the application read a csv and upload the images (file names can be read from one of the column in csv), get the pretty_url back from the response and replace the filename in the converted csv and then post a stryblok story.

**Describe alternatives you've considered**
Right now, I am importing stories using fast-csv without image uploading, then going to each record and selecting the related images manually. Tedious.

**Additional context**

**Comment by onefriendaday** [comment]
For the feature request you described you can now use this new package to transform html and markdown to RTE:
https://github.com/storyblok/storyblok-markdown-richtext

**Comment by muhammedjenos** [comment]
What they described solution has anything to do with my original enhancement request ??? I am a bit confused here.
