### ISSUE TITLE
Schema definition - field type - single option - ability to add all options at once.

### ISSUE THREAD

**Issue by ravisankarchinnam** [storyblok/storyblok#255]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
Regarding schema definition - field type - single option:
Consider a case in which there are huge number of options needed to be added. It's too much time and effort consuming to add every option one by one, by clicking on ADD button each time.

**Describe the solution you'd like**
It would be helpful if we have an option:
1. To upload a json with a key/value pair. (or)
2. any specific format which can be copy/pasted in the input field.
which will be then auto formatted to options instead of adding manually one by one.

**Comment by onefriendaday** [comment]
We recommend you to use Storyblok's datasources for that. Datasources can be uploaded via CSV and used in multiple fileds.
