### ISSUE TITLE
Schema definition - field type - single option - tab key creates new option. 

### ISSUE THREAD

**Issue by 7sxzx** [storyblok/storyblok#256]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
Regarding schema definition - field type - single option:
Consider a case in which there are huge number of options needed to be added. It's so irritating to click on +ADD button every time to add a new option.

**Describe the solution you'd like**
Instead new option is created on pressing tab key.

**Comment by onefriendaday** [comment]
Has been released.
