### ISSUE TITLE
assets manager forgets to drop image in previously selected folder

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#258]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

When uploading new assets to the assets manager and marking a folder for the upload and changing to another tab in the menu and going back the next assets aren't being uploaded to the previously selected folder.
The compressed video capture shows the process in detail:
[Bildschirmvideo aufnehmen 2020-04-26 um 11.09.36.zip](https://github.com/storyblok/storyblok/files/4535466/Bildschirmvideo.aufnehmen.2020-04-26.um.11.09.36.zip)

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
