### ISSUE TITLE
add possibility to create internal anchor links to the rich-text field

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#260]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The functionality of being able to create internal anchors equally of the link field --> https://www.storyblok.com/cl/anchor-option-for-internal-link would be a great help when working with the rich-text field in a use-case like a glossary for example.
It would be a great advantage, make the work with it one more time easier and more flexible.

**Describe alternatives you've considered**

**Additional context**

**Comment by ullander** [comment]
I can't find documentation connected to this as I can't figure out how to use it on V2. 
Has it been added yet? @Slackman2015
