### ISSUE TITLE
Collision of apps - translated slugs vs advanced path

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#261]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
If you install both apps the translated slugs are not working and by changing the language in Visual Editor the path of the story will not change as it should change to translated slug with language code.

**Expected behavior:**
Where the "advanced path" is not defined the URL slugs should work as the advanced path wouldn't be installed.

**Steps to reproduce:**

1. Install translated slugs app
2. Enable 2 languages
3. Create story and translate it slug
4. Check the preview of URL - it should change in Visual Editor if you change language
5. Install advanced paths app
6. The point 4. doesn't work anymore.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by bstrdChronicles** [comment]
The Combination of both Apps is indeed needed to have the possibility to use the advanced path with multiple field level languages and still be able to always display everything in the correct language even in the visual editor!

**Comment by onefriendaday** [comment]
The advanced path app calculates the path always with the code you put in the path attribute of the content item with or without the translated slugs app installed. This is actually not a collision bug and a configuration issue. To include the language in the preview url you need to include the variable {{lang}} in the path field. Example: "{{lang}}/mystory". The api requests work on both the translated slug and the original so that you can always show the right content.

**Comment by bstrdChronicles** [comment]
@onefriendaday 

well... it works for simple pages e.g. home, but not for other cases:

Case:
Default Language: English
German: de

When I have a translated slug for a folder e.g. "components" -> "komponenten", and I add the advanced path here like that: 

![image](https://user-images.githubusercontent.com/24302245/84000570-34274000-a965-11ea-9822-bd79f9166ed2.png) 

Then it won't show the translated slug but the default language slug for the folder root page: 

![image](https://user-images.githubusercontent.com/24302245/84001175-61c0b900-a966-11ea-8edb-8f1329c16c7f.png)

Is that even achievable at the moment somehow in storyblok to have the actual path in the visual editor url that you are supposedly editing right now ?

**Comment by samuells** [comment]
@onefriendaday that may be true, what you said. But still, if I don't insert any code, it should work as before. IMHO

**Comment by johannesdz** [comment]
I have the same problem - exactly as shown in the screenshot. 
It would be great, if you could reopen this issue. 

Since i am able to set a locale slug, i would expect to pick it up.
Or you could provide a new variable {{folder.slug_translated}}

**Comment by onefriendaday** [comment]
To add a new variable is a good idea @johannesdz! Thanks! We added the new attribute {{folder.translated_slug}} to get the translated slug. Browser window reload is required to get the update.

**Comment by christina-grannas** [comment]
> To add a new variable is a good idea @johannesdz! Thanks! We added the new attribute {{folder.translated_slug}} to get the translated slug. Browser window reload is required to get the update.

This works for folders but how can I get the same effect on stories that are inside those folders?

**Comment by Maren-Osnabrug** [comment]
It's a little dirty IMO but I was able to make this somewhat work for my use case by adding the following in the Real Path of the story:

`{{if(options.lang == 'nl' && options.story.translated_slugs[0].lang == 'nl')}}{{story.translated_slugs[0].slug}}{{#else}}{{story.slug}}{{/if}}`

This uses a Dutch translated slug for the story if that is the first in the translated slugs array. 
I'm sure it can be improved upon so maybe modify for your specific case :) 
For the german case, just replace 'nl' with 'de'.

**Comment by christina-grannas** [comment]
> It's a little dirty IMO but I was able to make this somewhat work for my use case by adding the following in the Real Path of the story:
> 
> `{{if(options.lang == 'nl' && options.story.translated_slugs[0].lang == 'nl')}}{{story.translated_slugs[0].slug}}{{#else}}{{story.slug}}{{/if}}`
> 
> This uses a Dutch translated slug for the story if that is the first in the translated slugs array. I'm sure it can be improved upon so maybe modify for your specific case :) For the german case, just replace 'nl' with 'de'.

I'm afraid this would not work for me since there could be any number of translations in the site.

**Comment by Maren-Osnabrug** [comment]
If you need it to look through your translated slugs array to match based on lang: 

`{{if(options.lang != '' && options.story.translated_slugs.find(function(item) { return item.lang == options.lang }))}}{{ story.translated_slugs.find(function(item) { return item.lang == options.lang }).slug}}{{#else}}{{story.slug}}{{/if}}`

that matches any language to its translated slug if there is one. It's the best I can do until {{story.translated_slug}} becomes available :wink:

**Comment by christina-grannas** [comment]
> 

Wow that actually works! I didn't realize you could do that kind of advanced paths..! Thanks you!
