### ISSUE TITLE
add feature for creating an OAuth token that allows to limit the access level to certain functions

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#263]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
When developing a custom field type plugin there is actually no way to hide the OAuth token what makes it possible that it gets into the wrong hands and can be misused. This would open a data leak and that isn't desirable.

**Describe the solution you'd like**
If there would be the possibility to generate an OAuth token that can be configured to be read-only and limited to access certain endpoints it would make the usage of it in custom field type plugins, front-ends and back-ends more secure.
An example for its usage:
A customer wants to access the assets and just read the assets object. In this situation a white list for this would allow the access to read the asset objects and only that particular one for the generated OAuth token.

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
Currently the best way to handle this issue is to create your personal backend endpoint that uses the token on the server side and only exposes the asset endpoint to the plugin.
