### ISSUE TITLE
add "undo redo" feature to the "versions" function to be able to jump to older versions back but to the latest version as well as long as nothing has been modified

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#266]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
At the moment the history feature allows the following:
A user can revert to an older version of a story but after that can't access the newer versions anymore it he reverted to the older one.

**Describe the solution you'd like**
In the case that the user wants to revert to an older content version he should be able to come back to newer content versions as long as he doesn't modify anything.

It could be resolve like a customer suggested with a preview that shows the content of the content version in a preview of some sort before the choice is made to revert to a certain version and continue working on it.

It could be resolved in an App as well that extends the actual behavior of the functionality.

**Describe alternatives you've considered**

**Additional context**

**Comment by abrambailey** [comment]
Thanks for considering this enhancement 👍
