### ISSUE TITLE
Sign webhook requests cryptographically

### ISSUE THREAD

**Issue by jfix** [storyblok/storyblok#269]
**The feature would affect:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* **webhooks**

**Is your feature request related to a problem? Please describe.**
When accepting webhooks coming from you I cannot currently validate that they have indeed been sent from Storyblok and have not been tampered with during transit.

**Describe the solution you'd like**
I would like that you sign the payload you send cryptographically. There would be a shared secret that you use to sign, and I would use to verify the signature. As an example, I can point you to how GitHub does it: https://developer.github.com/webhooks/securing/#securing-your-webhooks

**Describe alternatives you've considered**
A potential solution to increase the probability that a request comes from you, would be to use restriction of the accepted IP address range. But I've just learned that your requests may come from anywhere in `eu-central-1` which is clearly too big to be useful. And it wouldn't actually help with the "tampering in transit" issue.

**Additional context**
I've been encouraged to create this ticket after a support chat with Hannes.

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/securing-webhooks
