### ISSUE TITLE
'Multi-Options' ordering is reset by the CMS interface.

### ISSUE THREAD

**Issue by cullenr** [storyblok/storyblok#27]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
'Multi-Options' ordering is reset by the CMS interface.

**Expected behavior:**
The CMS interface should respect previous ordering updates.

**Steps to reproduce:**
Multi-Options can be ordered if you select 'show only selected' in the web UI.
Reordering the list allows the underlying data collection to be re-ordered, this
can be verified by getting the data from the content API. If the CMS page is
refreshed the list is no longer shown in the correct order, subsequent
publishing of this page will result in the oredering being reset to this default
order even if the field is left untouched. This means that every edit to a Story
with ordered Multi-Options will require every Multi-Options field to be manually
set to the correct order in addition to the desired update.

**Other information:**

Present on Firefox on Ubuntu 18.10 & Chome on OSX

**Comment by DominikAngerer** [comment]
We've deployed a fix that resolves the sorting position before validating the data to remove deleted contents. Thanks for the report and sorry for the inconveniences!
