### ISSUE TITLE
subfolder not accessable when parent folder not in white-list for custom user role

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#271]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

When an admin create a custom user role he can't give access to a sub-folder only. He needs to give access to a parent-folder as well.

**Expected behavior:**

For usability reasons and for security it would be very helpful if it would be possible to give only sub-folders free for editors.

**Steps to reproduce:**

Here is an example for this configuration:
![Bildschirmfoto 2020-05-05 um 07 24 42](https://user-images.githubusercontent.com/12159917/81056776-84603d80-8ea1-11ea-9599-a83efe927d1e.png)

![Bildschirmfoto 2020-05-05 um 07 25 54](https://user-images.githubusercontent.com/12159917/81056861-b376af00-8ea1-11ea-9d11-93b5098d7a9c.png)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
It is possible to create two roles:

1. Define the permissions for the parent folder (only read access)
2. Define the role as above for the child folder.

Than assign both roles to one user.

**Comment by onefriendaday** [comment]
As Dominik described or you can uncheck "Hide folders if unauthorized".
