### ISSUE TITLE
add possibility to hide all back-listed folders/stories completely in the UI

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#272]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
When configuring a custom user-role the user can see still the folders and stories that shouldn't be visible as N/A but this can be still a little bit confusing and intimidating to some people. 
![Bildschirmfoto 2020-05-05 um 08 23 30](https://user-images.githubusercontent.com/12159917/81061144-3996f380-8eaa-11ea-8a91-a51f18e0aafa.png)

**Describe the solution you'd like**
It would be good to be able to hide those items completely as it isn't relevant to him to see what he can't access because it can be very screen filling in this case and doesn't contain any important information for him as the names don't appear.

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
Unfortunately it will not be possible to hide them because the access check can not be integrated into the search algorithm and there would be empty pages.

**Comment by ZnaaMiR** [comment]
Can we reopen this? It's quite annoying for our editors to just see a long list of content items they cannot access and they then still have to search for the content they actually have access to. Especially if it's only one story or folder they are responsible for. I understand you cannot remove the pages, but perhaps just hide them in the frontend? This is a recurring annoyance for our editors. It would contribute to a better user experience for sure :) (I know there's a favorite button, but no one are aware of it)
