### ISSUE TITLE
add functionality to add size of images to link on uploading time when using a link field (like in the image field)

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#274]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
When using a link field with the assets option activated the uploaded images don't receive the same link with containing the dimensions in it.
Here is a comparison for both link types and their generated links:
![Bildschirmfoto 2020-05-06 um 08 15 47](https://user-images.githubusercontent.com/12159917/81170997-06b83280-8f72-11ea-9645-d7c2c1cef12b.png)

**Describe the solution you'd like**
It would be helpful to be able to generate the same link structure when the assets option has been activated.

The actual use-case is that a user can upload an image or a video to a hero section. It would be possible to split this section into two parts but it would increase the possibility for mistakes and misunderstanding on the side of the editors.
Another important point is that lazy loading images that can rely on having the dimensions in the link available possibly won't work like with the in the image field uploaded images.

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
We added the dimension detection.
