### ISSUE TITLE
Story position property ignored when set through the Management API

### ISSUE THREAD

**Issue by afgno** [storyblok/storyblok#28]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
When creating a story via the Management API the position field is ignored and gets overwritten . This results in the incorrect sorting of the stories/folders on the Storyblok Interface and the wrong position value when accessing the story via the API. This also happens when trying to update the position field once the story has been created.

**Expected behavior:**
The position field should be set correctly when creating a Story via the Management API

**Steps to reproduce:**
- Create a story containing the *position* field via the the Management API .
- Fetch the story via Management/Content API. The field *position* will have the wrong value.

**Related code:**

```
const story = {
    name: 'test-story',
    slug: 'test-story',
    is_folder: true,
    position: 5,
}

const response = await Storyblok.post(`spaces/${spaceId}/stories/`, { story } )

```

**Other information:**

**Comment by DominikAngerer** [comment]
Hey @afgno !

You're right, the position property currently does not effect the actual position. I'll discuss that internally and come back to you with more information on that.

Thanks for the report!

**Comment by onefriendaday** [comment]
Has been released now: https://www.storyblok.com/cl/set-position-via-management-api
