### ISSUE TITLE
images are getting stretched when using the image editor and choosing an area for cropping

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#282]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *image editor* 

**Current behavior:**

When using the image editor the user is able to choose an area for cropping.
The original dimensions are being used for the cropped versions and that results in a stretched image like this one:
https://a.storyblok.com/f/83257/819x1024/d6d45acd33/xlarge5437435.jpg
The original image:
https://a.storyblok.com/f/83257/819x1024/f5a9b696c0/xlarge.jpg

Here is a video that shows the steps that lead to this behavior:
https://a.storyblok.com/f/83257/x/f8699b0f88/bildschirmvideo-aufnehmen-2020-05-13-um-09-02-23.zip

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
