### ISSUE TITLE
add information about the author to the stories

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#283]
**The feature would affect:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
At the moment the stories don't contain information about the author.
In the case that the user wants to use the author information directly from the story he has only the possibility to access those information using the management API.

**Describe the solution you'd like**
For saving time and making the access to this data easier it would be helpful to have this directly in the story.

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
Sorry but we can not deliver this information. As mentioned you can use the management api to get the author.
