### ISSUE TITLE
stories/undefined in API call to fetch Stories by JS API

### ISSUE THREAD

**Issue by kluplau** [storyblok/storyblok#29]
**The issue occurs while working with:** (check one with "x")   
- [x] *api.storyblok.com (CMS - Content Delivery API)*

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  

**Current behavior:**
The URL for requesting the API includes `stories/undefined` which doesn't work. It doens't append "undefined" with these settings for some reason.

```javascript
window.storyblok.get(
  {
    starts_with: "work/",
    version: "draft"
  },
  (data) => {
    console.log("this works", data);
  }
)
```

http://api.storyblok.com/v1/cdn/stories/undefined?by_uuids=684bdaf1-f145-43b3-b241-040c973193ff%2Ca2ba88e0-2fc8-4b33-bf3e-2011942521c0&cv=1556993370&token=_STRIPPED_BECAUSE_OF_PRIVACY_&from_release=

**Expected behavior:**
Not having undefined in url.

**Steps to reproduce:**
```javascript
window.storyblok.get(
  {
    by_uuids: blok.cases.join(",")
  },
  (data) => {
    console.log("this doesn't work as the URL has `undefined` in it", data)
  }
)
```

**Other information:**
I'm using the Storyblok Gatsby example, and I'm getting the error while trying to query related stories. I have to fetch more Stories, because I have a component that references other Stories, so the basic query for the current path in editor.js is not sufficient.

**Comment by kluplau** [comment]
You can fix it by adding `slug: "/"` to the query.

```javascript
window.storyblok.get(
  {
    slug: "/",  // adding slug "/" will make queries work again
    starts_with: "work/",
    version: "draft"
  },
  (data) => {
    console.log("this works", data);
  }
)
```

**Comment by DominikAngerer** [comment]
Hey @kluplau,

I would recommend switching to the our JS Client: https://github.com/storyblok/storyblok-js-client/

I'll also have our team review the delivered storyblok client in the javascript bridge to resolve the issue without you to have to add `slug: "/"` here.

Thanks!

**Comment by kluplau** [comment]
Alright. I'll try that..
