### ISSUE TITLE
ssi error on nginx "[an error occurred while processing the directive]"

### ISSUE THREAD

**Issue by Brotzka** [storyblok/storyblok#290]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* Editor and preview

**Current behavior:**

Running a site on Nginx with server-site-includes `on` it could happen, that the comment provided by StoryBlok is interpreted as [server-site-include](http://nginx.org/en/docs/http/ngx_http_ssi_module.html) statement.
```html
<!--#storyblok#{...}-->
```
Therefor Nginx tries to locate a file and fails. This is why this error message is displayed.

**Expected behavior:**

Nginx should ignore those comments.

**Steps to reproduce:**

```php
// Laravel

```

**Related code:**

The following code is from Laravel's template-engine  Blade. 
```
{!! isset($blok['_editable']) ? $blok['_editable'] : '' !!}
// outputs <!--#storyblok#{...}-->
```

**Other information:**
For a quick fix I modified my statement in order to add a whitespace at the beginning:
```php
{!! isset($blok['_editable']) ? str_replace("<!--#", "<!-- #", $blok['_editable']) : '' !!}
``` 

This way Nginx doesn't recognize the comment as ssi-statement.

**Comment by onefriendaday** [comment]
The rollout of a fix for this Nginx proxy configuration would break plugins like storyblok-vue and many others but we will consider this change in a major version upgrade of the api (v2).

But you could implement an helper for Laravel that does the same thing as storyblok-vue to solve this problem: https://github.com/storyblok/storyblok-vue/blob/master/storyblok-vue.js#L19

Your helper could take the _editable attribute and set the html attributes directly
```
<div {!! editable($blok['_editable']) !!}>
...
```
