### ISSUE TITLE
Slug in Page Config .php .html are invalid URL

### ISSUE THREAD

**Issue by vomnes** [storyblok/storyblok#291]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
When we try to change Slug on the entry configuration of the pages the values 'xxx.php', 'xxx.html' are considered as invalid "Ups, there where some problems: Slug is invalid".
If you use Apache for example to remote the extensions .php or .html it is working fine.

**Expected behavior:**
The extensions .php and .html should be accepted.

**Steps to reproduce:**

<img width="333" alt="Capture d’écran 2020-05-16 à 16 06 29" src="https://user-images.githubusercontent.com/10994414/82121746-9e4a2c00-978f-11ea-99e2-50a5ca65c332.png">

**Comment by DominikAngerer** [comment]
Slugs are used for the resource path and are we do not allow extentions in there. If you want to use the .php endings in the preview we advise to use the real-path to mimic that and configure it further down the configuration tab. The entry itself should still be not bound to an extention.
