### ISSUE TITLE
Boolean field is required value cannot be false

### ISSUE THREAD

**Issue by vomnes** [storyblok/storyblok#292]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
When you set a field boolean as required it value cannot be false.

**Expected behavior:**
Remove the required possibility for boolean type.

**Steps to reproduce:**
<img width="414" alt="Capture d’écran 2020-05-16 à 16 16 29" src="https://user-images.githubusercontent.com/10994414/82122010-35fc4a00-9791-11ea-8d85-83aac470edae.png">
<img width="1038" alt="Capture d’écran 2020-05-16 à 16 14 25" src="https://user-images.githubusercontent.com/10994414/82122012-372d7700-9791-11ea-9a8f-958228d304ab.png">

**Comment by onefriendaday** [comment]
The required setting on the boolean field is meant to be like a check if the checkbox is checked. It requires the user to check it intentionally.
