### ISSUE TITLE
add possibility to choose a list of content types that can be created in a folder

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#297]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
The actual option in the folder configuration allows to set the allowed content type to only one type.
![Bildschirmfoto 2020-05-20 um 09 42 43](https://user-images.githubusercontent.com/12159917/82449198-3c384200-9a81-11ea-8403-0eeb16c1c726.png)

**Describe the solution you'd like**
In cases where for example more than one content type is being used in a folder it would be helpful to be able to select more than only one type.
This would prevent that a user adds wrong types and breaks the implementation of an app and on the other hand it would make the work for the editor easier as they would see which types are available.

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
You can use component creation permission for that as mentioned in https://github.com/storyblok/storyblok/issues/210
