### ISSUE TITLE
add possibility to define aliases for components in the content view and hierarchy

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#299]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
When a user creates a hierarchy of components the result can be pretty complicated to look through when working which a large number of them and a deep hierarchy.
![Bildschirmfoto 2020-05-20 um 14 33 55](https://user-images.githubusercontent.com/12159917/82478234-027a3200-9aa7-11ea-8213-23092f645a17.png)

**Describe the solution you'd like**
By adding the possibility to give to every component instance an own alias that is being shown not only in the content view but also in the hierarchy would help a lot to make it a lot easier to identify single items when the same component type is used several times. 

**Describe alternatives you've considered**

**Additional context**

**Comment by samuells** [comment]
I talked with Peter about this FR and I need to clarify it a little bit. What he meant is the `breadcrumb` - they build their websites with a lot of generic nested components and that makes the visual editor experience worse as at the end you will see in the `breadcrumb` only something like this `wrapper > wrapper > wrapper > .... > wrapper`- in his sample `page`

What he would like to do is to just have alias field on the `blok` level to override the name of the blok and the visual editor would show `homepage > hero area > teaser > prose > title` and this would be possible to do by Editor - so the Person who creates content, not define schema of blok.

**Comment by bstrdChronicles** [comment]
That would indeed be helpful!
Got a similar situations where I would benefit a lot from some enhancements in that regard. :)

**Comment by onefriendaday** [comment]
The recommendation here is to flatten the structure a bit with components that are a bit more explicit. I would generally not recommend such a structure.

Instead of having wrapper -> wrapper -> wrapper the developer can create one component wrapper and make the options of this component more flexible. Or make a component that is really a "hero area", "teaser", etc.

**Comment by Slackman2015** [comment]
This topic seems to be a big one for some of our customers as it resolves some issues. An actual thread in our forum shows that:
https://forum.storyblok.com/t/alias-for-blocks-not-the-same/369

I think that it could be helpful to exchange the name in the breadcrumb navigation with the display name the users choose and in the block it could be more detailed and show the component name (technical name) and the display name like this:
![Bildschirmfoto 2020-09-23 um 07 03 59](https://user-images.githubusercontent.com/12159917/94000930-31165b00-fd6e-11ea-8ae0-131701af2229.png)
![Bildschirmfoto 2020-09-23 um 07 08 31](https://user-images.githubusercontent.com/12159917/94000958-38d5ff80-fd6e-11ea-9c05-36ba89c7acbb.png)
