### ISSUE TITLE
Selected content type is not visible.

### ISSUE THREAD

**Issue by thomkrupa** [storyblok/storyblok#30]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

https://cl.ly/4425b0d43111
The selected content type is not visible below the dropdown. Only the main "page" is working.
This modal appears when I want to add a new Entry.

**Expected behavior:**

Every selected content type should be visible.

**Steps to reproduce:**

We use shared components. 
1. Create a new content type component.
2. Try to add a new entry and select something other than "page" 

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Hey @thomkrupa !

Thanks for the report - a fix is already in review and will be available shorty.
You can still choose the content type even tho it wont show up.

Important: only happens for shared components.

**Comment by onefriendaday** [comment]
The bugfix has been deployed two days ago.
