### ISSUE TITLE
can't search for Boolean fields when the value is false

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#303]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

In the improved filter menu the user is able to search for stories by fields and their values. It is also possible to search for the Boolean field and define the checked state but it isn't possible to search for the unchecked/false state of it because the search string in the link that is being shown in the browsers address fields stays empty.
![Bildschirmfoto 2020-05-26 um 07 18 49](https://user-images.githubusercontent.com/12159917/82890089-07fdcf00-9f22-11ea-99fb-a9276eecd046.png)

**Expected behavior:**

It would be helpful to be able to search for the false state of the Boolean field as searches for it deliver all stories instead only those searched for.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
