### ISSUE TITLE
SSO for Authorization

### ISSUE THREAD

**Issue by StoryblokSascha** [storyblok/storyblok#309]
**The feature would affect:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [X] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
Using SSO-Methods for Authorization and defining User Roles and Entitlments.

**Describe the solution you'd like**
Use Case: Allocate Authorization from e.g. Microsoft AD to define Roles/Entitlements in Storyblok

**Describe alternatives you've considered**

**Additional context**

**Comment by onefriendaday** [comment]
https://www.storyblok.com/cl/azure-ad-group-roles
