### ISSUE TITLE
Sidebar in floating mode

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#31]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
On my current screen the editable/preview area is cca 1150 pixels, which sets the viewport to tablet mode, hence the preview is not very accurate.

**Expected behavior:**
Allow sidebar to be in a floating mode to provide enough space for the preview area to go full screen.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
We've launched several improvements for the form only and side by side editor. The preview can also go into "full screen" by pressing the preview link next to the save button. The sidebar has a floating option so you can resize it as you need, still keeping a min width tho as the open preview button exists. On the top right corner of the preview you will see two buttons: one for minimizing the preview and another one to size the preview frame width itself.
