### ISSUE TITLE
Markdown editor the "Enlarge" button is shown as checkbox also

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#311]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
In the markdown editor the "Enlarge" button is actually a "toggle rich text" button.
![image](https://user-images.githubusercontent.com/5185019/83175245-e5370a80-a11b-11ea-9abe-15d6a81eed92.png)

**Expected behavior:**
I guess the checkbox should be hidden and only the icons should stay?

**Other information:**
Reported on Discord - https://discordapp.com/channels/700316478792138842/700345807861317662/715581625236455424

**Comment by onefriendaday** [comment]
Has been fixed.
