### ISSUE TITLE
Initial state of Boolean field type attribute is not present in the content of JSON

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#312]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
If you define the boolean attribute "checkbox" and its value is "false" from beginning the attribute key-value is never in the content of the JSON deliver by the API. This is confusing behavior and potentially can lead to breaking changes as if I remember correctly it was there before removing the default value option from the attribute.

If you change the value to TRUE and save and then change to FALSE - the attribute is present in JSONs with FALSE value what is correct - only the initial state is buggy.

**Expected behavior:**
The boolean field type attribute should be always in the content of JSON and should reflect the current value from the FRONT-END. It would be nice to have also possibility to set-up default value to prevent this.

**Steps to reproduce:**
Define new attribute on the component of the boolean type and leave it on initial value (false) and it will not be shown up in the draft or published JSON.

**Comment by onefriendaday** [comment]
Storyblok doesn't force a strict schema on the content. If you want a strict schema you will need to use our GraphQL api. For the REST-API we will introduce a strict schema on a new endpoint v2 as this is a breaking change.
