### ISSUE TITLE
Add a way to store SB Applications data / settings

### ISSUE THREAD

**Issue by Blackslash333** [storyblok/storyblok#314]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Describe the solution you'd like**
Would it be possible to store custom SB application data / settings like fieldtypes do? I'm actually developping some apps and at the moment I store some basic JSON settings on my server. I feel like it could be really handy to have some kind of endpoint or something where we could store some app-related settings (so each space could have their own "space app data") directly on SB.

**Comment by bstrdChronicles** [comment]
would be nice out of the box, but on the other hand, you can already just create a settings story with a settings component you define including any fields you want and fill it with any data you want. Then fetch this data at the build or startup of the app.

**Comment by Blackslash333** [comment]
I did this for another app already and didn't feel like it was really handy (was just reading data from a story entry, not writing into it).

Also at the moment it doesn't seem like we can create / update any stories via the provided token / API (https://github.com/storyblok/nuxt-auth#usage):

> Not all features of Management API supported. Only GET supported in this beta.

**Comment by onefriendaday** [comment]
> I did this for another app already and didn't feel like it was really handy (was just reading data from a story entry, not writing into it).
> 
> Also at the moment it doesn't seem like we can create / update any stories via the provided token / API (https://github.com/storyblok/nuxt-auth#usage):
> 
> > Not all features of Management API supported. Only GET supported in this beta.

This message is already out of date and an error in the documentation. You can use POST, PUT and DELETE also with the latest version.

**Comment by Blackslash333** [comment]
Alright, thanks. Closing the issue for now as I'm going to try the story-data way.
