### ISSUE TITLE
Single Option Field Type - Empty String Value & Default

### ISSUE THREAD

**Issue by bstrdChronicles** [storyblok/storyblok#316]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
If you have a single selection field type in an component and give it some options, where one value in an option is empty -> which should result in an empty string as value, then the option is not selected in the select field of the component when you save and open the component again.
It just is displayed as if nothing was ever selected.

additionally you cannot set the empty string value as your default value apparently.

**Expected behavior:**
You should be able to create an option with an empty string as value, save a component with this value selected that and have it selected whenever you open the component again. 
Additionally you should be able to set the empty string value as default value for the component field.

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/24302245/83523357-5a228f80-a4e2-11ea-9a54-e0abc3cea06e.png)
![image](https://user-images.githubusercontent.com/24302245/83523376-64dd2480-a4e2-11ea-8f91-6de4739b8e16.png)

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
There is already an empty option in the select field by default. This is why you have the checkbox "Hide empty option". If you select "Hide empty option" you will have the behaviour you expect.
