### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#32]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**

I have cherry-picker your nuxt boilerplate into my app, and I am wondering what cacheVersion actually do. I would expect the API to respond saying nothing has changed and nuxt falling back to using store values, but it doesn't look like it's the case. Could you please clarify how YOU envision caching? There will be days when content changes a lot, but there will be stretches of weeks, where there will be no changes. So, I am trying to think of the best way to optimize the API calls and server response times.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Hey there! The CacheVersion is nothing else than a change of the URL parameter which allows our CDN to access a new version of our server. So in this case the cacheVersion or in short `cv` is basically a timestamp. With Nuxt.js you can define a route that you can define to be called by our webhook to trigger a clearCache which would refresh your timestamp (either flushCache or replace a server side timestamp that you pass as cv). You can also always receive the timestamp of the latest publishing time as described here: We've documented the caching approaches right here: https://www.storyblok.com/docs/api/content-delivery#topics/cache-invalidation
