### ISSUE TITLE
Swicthing between custom apps won't work

### ISSUE THREAD

**Issue by christianzoppi** [storyblok/storyblok#324]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
If I have 2 custom apps in the main sidebar and I'm inside one of the 2, when I click on the other one that won't load. I have to click on one of the core tabs(settings, apps, etc..) and then I need to click again on the custom app I want to open.

**Expected behavior:**
I'd expect the apps to open normally like any other tab.

**Steps to reproduce:**
You can test this in the space 52363, you'll find 2 custom apps at the bottom of the sidebar.

**Comment by onefriendaday** [comment]
You may do not have the latest Storyblok nuxt-auth plugin as this bug has been fixed recently.

**Comment by christianzoppi** [comment]
Thanks for the reply Alex. We are not using nuxt for those applications. Should we use just nuxt?

**Comment by onefriendaday** [comment]
Our nuxt plugin takes over the heavy lifting but you can take a look at the following file where multi-space sessions are implemented: https://github.com/storyblok/nuxt-auth/blob/master/lib/router.js

**Comment by christianzoppi** [comment]
Thanks @onefriendaday we'll have a look at that and change the way we handle that part to make it work properly.
