### ISSUE TITLE
New 'asset' field outputs non-parsable string in GraphQL

### ISSUE THREAD

**Issue by nbsmi** [storyblok/storyblok#325]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* GraphQL

**Current behavior:**
When retrieving one or multiple stories with a new 'asset' component, the GraphQL API returns a string for that field wherein key/value pairs with a '=>' as separator are used, encased in accolades. The non-standard format is not directly parsable into a JSON object, for example. Empty properties have a 'nil' value.

**Expected behavior:**
A JSON object or JSON parsable string, with empty properties having a 'null' value.
EDIT: would be welcome if the protocol is omitted in the 'filename' property, like with asset output in Content Delivery API.

**Steps to reproduce:**
Output can be reproduced by setting up an item with an 'asset' (image) field and using the GraphQL browser to select the item and field: http://gapi-browser.storyblok.com/

**Related code:**
```
Example output from GraphQL browser: "image": "{\"id\"=>1164296, \"alt\"=>\"Alt text\", \"name\"=>\"\", \"focus\"=>nil, \"title\"=>nil, \"filename\"=>\"https://a.storyblok.com/f/83680/771x556/a6f7206126/afbeelding1_41c09e66faa59a848fa783e7c52e7323_2000.png\", \"copyright\"=>nil, \"fieldtype\"=>\"asset\"}"
```

**Comment by onefriendaday** [comment]
Has been fixed: https://www.storyblok.com/cl/asset-field-added-to-graphql-api 

https: is now prepended by default because of security reasons.
