### ISSUE TITLE
problem with search for content types using the display name when in the content item creation dialog

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#330]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

When the user creates a component and uses a display name for the component and searches for it the component isn't being shown in the search results like visible in the example video:
[Bildschirmvideo aufnehmen 2020-06-15 um 11.16.04.zip](https://github.com/storyblok/storyblok/files/4780806/Bildschirmvideo.aufnehmen.2020-06-15.um.11.16.04.zip)

**Expected behavior:**

It should be possible to search for the displayed name also or otherwise the users get confused by not finding the component types in the list.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
