### ISSUE TITLE
selecting mp4 video files doesn't work in new asset field when resticting files to videos

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#333]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

When configuring the new asset field type to accept only videos like in the image below
![Bildschirmfoto 2020-06-17 um 09 55 23](https://user-images.githubusercontent.com/12159917/84900880-181c5080-b081-11ea-8b24-fc14217b9c3a.png)

it doesn't accept already uploaded mp4 files as valid files:
![Bildschirmfoto 2020-06-17 um 09 55 06](https://user-images.githubusercontent.com/12159917/84900835-063aad80-b081-11ea-8273-096fd45ddb3c.png)

But this file type is being accepted on upload.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed
