### ISSUE TITLE
en_gb or en-gb?

### ISSUE THREAD

**Issue by notclickable** [storyblok/storyblok#34]
**The issue occurs while working with:** (check one with "x")   
- [ x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

4-char language codes in the CMS interface are listed with a dash-> en-gb : but in the API they are used with an underscore -> en_gb  -> as in : https://gist.github.com/DominikAngerer/f685f2c988171faef3fb6c2ffff4c78c

Therefore non of my attempts to use the field-level i18n technique .eg. "headline__i18n__en-gb" would work, as I was using the ones listed in the interface - might be worth harmonising these!

**Comment by onefriendaday** [comment]
Thanks for the request. We will extend the documentation.

Both language codes are used. The codes with dash are used in the api as our url convention is to use always dashes in the url. So to make an api request (Example: api.storyblok.com/v1/stories/en-gb/home) you would need to use to use the ones defined in the CMS interface.

As json needs the underscore for keys the dash is replaced with it as documented in the management api docs in the list of language codes:
https://www.storyblok.com/docs/api/management#core-resources/stories/internationalization-for-stories

**Comment by notclickable** [comment]
Ah that makes sense, thanks, just confusing when you are creating a component, the nearest reference is the language codes listed in the CMS.
