### ISSUE TITLE
Webhook failures

### ISSUE THREAD

**Issue by pibemillo** [storyblok/storyblok#342]
It appears that Webhook Logs are being considered as a future feature, which I would like to upvote since it would help resolve my current issue. In the meantime, is there any recommended way to troubleshoot whether my webhook is getting hit successfully when I publish a change in storyblok? 

According to the docs, any response that is not a 2xx will result in an email to the space owner. If I manually post to my webhook with a sample payload containing my space id, it is expected to clear some cache on server which I can validate it. However, I don't see the action taking place when making changes in Storyblok which leads me to ask if there is any additional information available about this. Are email notifications not working properly? Is my webhook url host timing out or not resolving and providing a response code? 

My space ids are the following: 68761, 76728, 68768, 70603.

Any help or suggestions would be greatly appreciated.

Thanks!

**Comment by udlose** [comment]
@DominikAngerer  I am also interested.  Is there any update?

**Comment by udlose** [comment]
After further investigation, I was able to verify that there are at least 2 causes why the webhook call is failing.

Background: My API with the webhook is running in AWS with "WAF and Shield" enabled.  It has several rules that are causing the failures:

1. Geolocation rule had U.S. only and I see that there are webhook POSTS which are blocked that originate from Germany.  So my question is, **what are all geolocations for StoryBlok that I need to whitelist for allowing my webhook to be called without AWS WAF getting in the way**?

2. I see that there is a WAF rule for "GenericRFI_BODY" that is blocking the webhook POST from StoryBlok.  Here is the Request that is blocked:
```
POST [redacted]
Host: [redacted]
Content-Length: 276
Accept: application/json
Accept-Encoding: gzip, deflate
Content-Type: application/json
Webhook-Signature: 
User-Agent: Ruby

{
"action": "published", 
"space_id": [redacted], 
"story_id": [redacted], 
"text": "[Filtered]"
}
```

Do you have any idea what in this POST would cause this to happen?

**Comment by onefriendaday** [comment]
Webhook logs are now available: https://www.storyblok.com/cl/webhook-logs
