### ISSUE TITLE
Dragging and Dropping inline components within Rich Text fields causes bug

### ISSUE THREAD

**Issue by moritzlaube** [storyblok/storyblok#346]
**The issue occurs while working with:** (check one with "x")   
- [ x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
I am using a Rich Text field to edit my blog content. Inside of this component I whitelisted a few other components to use as inline-components (CTA-Link and Quote component in my case). Everything works fine until I try to reposition the inline-component with in the Rich-Text component. When I try that the component vanishes and all that remains is some gibberish.

Please have a look at the animated gif attached to this issue
![2020-06-25 10 26 40](https://user-images.githubusercontent.com/39345259/85686866-a2436500-b6d0-11ea-8f9f-ca1d01b36d2d.gif)
. 

**Expected behavior:**
I'd like to drag and drop the inline components like I can with the "normal" components. 

**Steps to reproduce:**
I am using your CMS interface with Chrome version 83.0.4103.97

**Comment by DominikAngerer** [comment]
Has workaround and is in investigation to improve: https://github.com/storyblok/storyblok/issues/251
