### ISSUE TITLE
Field type plugins do not render in whitelabel editor when hosted on a non-standard port

### ISSUE THREAD

**Issue by mattbab** [storyblok/storyblok#347]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
When self-hosting the Storyblok editor on a non-standard port (not 443), `Plugin` type fields do not render.

The following screenshots are of a Column component who's schema contains a field named "width" of the standard `bootstrap-widths` custom type plugin. 

When editing the content on app.storyblok.com the field renders as expected:

![image](https://user-images.githubusercontent.com/5158326/85738018-5ccd6a80-b6c5-11ea-92ac-3a054ca5f25d.png)

However when viewed in the whitelabel editor hosted locally on port 8443 (HTTPS), it just shows blank:

![image](https://user-images.githubusercontent.com/5158326/85737019-a073a480-b6c4-11ea-85e4-ed85d974c0e6.png)

**Expected behavior:**
The plugins should render as they do in app.storyblok.com or when the domain is not port qualified.

**Steps to reproduce:**

1. Take the markup provided in the [Can I whitelabel Storyblok?](https://www.storyblok.com/faq/can-i-whitelabel-storyblok) post:

```
<!DOCTYPE HTML>
<html>
<head><title>Storyblok - Whitelabel</title></head>
<body>
<link href="//app.storyblok.com/css/index-latest.css" rel="stylesheet" type="text/css" />
<div id="root"></div>
<div id="page-load"><div><div></div></div></div>
<script src="//app.storyblok.com/js/app-latest.js" type="text/javascript"></script>
<style>
.login__logo {
    // Overwrite style with your logo
    background: url(../images/logo.svg) no-repeat;
}
</style>
</body>
</html>
```

Save it locally as index.html. 

2. Serve the file on a non-standard HTTPS port using your web server of choice - I'm using IIS on port 8443 but the web server doesn't matter.
3. Browse to the hosted Storyblok editor, login, and create a component with a plugin type field.
4. Add content including the created component and the field will display a name but the field type editor will not appear.

**Other information:**

Digging into this, I found the problem is caused by the `host` param passed to `https://plugins.storyblok.com/v1/field_types/style-editor/get_html` is simply passing the hostname without the port qualification:

`<iframe class="js-field-type uk-width-1-1" src="https://plugins.storyblok.com/v1/field_types/bootstrap-widths/get_html?uid=3efeb05a-3119-472f-b27e-c66c4c3021cb-grid_widths&amp;protocol=https:&amp;host=localhost">`

Changing this in DevTools to include the port qualification makes the field editor appear as expected:

`<iframe class="js-field-type uk-width-1-1" src="https://plugins.storyblok.com/v1/field_types/bootstrap-widths/get_html?uid=3efeb05a-3119-472f-b27e-c66c4c3021cb-grid_widths&amp;protocol=https:&amp;host=localhost:8443">`

Of course the change isn't persistent so this is a proof of the cause, not a solution or workaround.

~There may be more involved in getting it to work completely. After playing with it a while I see a few Vue warnings in the console similar to `[Vue warn]: Error in created hook: "SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'https//localhost:8443' in a call to 'postMessage'."` though the editor does appear and no new warnings are shown while editing the field.~ **EDIT: This was caused by other changes I had made. There are no known issues with the communication between the plugin frame and the host window as a result of this change**

Please let me know if you need any further detail or if there's a way to control the `host` param to resolve this.

Thanks!

**Comment by onefriendaday** [comment]
We do not support the non-https for the self-hosted version as documented here: https://www.storyblok.com/faq/can-i-whitelabel-storyblok

**Comment by mattbab** [comment]
Thank you but I believe you misunderstood. In my repro instructions, I explicitly am using SSL just on a different port than 443.

**Comment by onefriendaday** [comment]
I see. So you mean you are hosting Storyblok on localhost and not a common domain. Are you able to configure your server to  run on storyblok.localhost.com for example?

**Comment by mattbab** [comment]
Sorry for the late response. We don't host the editor in production or even in staging, our content editors run it locally as it's hosted within our nuxt application - so will nearly always run on https://localhost:3000. By the time the application is deployed to a domain, we'll already have downloaded all of the content and assets to build the static site so it's never intended to run on a domain. 

There are obviously ways to work around this issue but they all require our developers and content editors to change their workflows and since there isn't a note in the documentation about the whitelabel editor not working in this scenario, it seems like a bug. As mentioned in the original bug report, it seems fixing it should be as simple as including the port number in the host query parameter of the field type get_html endpoint. It seems like a small change, but maybe I'm not seeing something you do.
