### ISSUE TITLE
Get ID of existing folder?

### ISSUE THREAD

**Issue by notclickable** [storyblok/storyblok#35]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x ] feature request  
- [x ] question

**Current behavior:**
If I attempt to create a folder, and that folder already exists, I get back the error 422 Unprocessable entity. 

**Expected behavior:**
What I would like to know is what is the ID of that folder, so I can list it as a component's parent_id and put components in it. Is there a way to do this?

**Comment by DominikAngerer** [comment]
Hey there!

Currently you can use the `with_slug` to check for the existence of your current `full_slug` as it will return the whole story object. 

```
Storyblok.get(‘spaces/606/stories/’, {
  “with_slug”: “your/folders/slug”
}).then((response) => {
  console.log(response.data)
}).catch((err) => {
  console.err(err)
})
```

I'll have a discussion with my team about the current behavior and how we can improve that!

**Comment by notclickable** [comment]
Thanks for the speedy response!
