### ISSUE TITLE
Asset Focal Point Moving between edits

### ISSUE THREAD

**Issue by bstrdChronicles** [storyblok/storyblok#353]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
Example: You have two image components, in each is an asset - when you click on the asset name to set the focal Point you can save it no problem. If you now click on another asset and set its focal point, return to the first asset and you can see the focal point is displayed in  the upper right corner. 
After a reload and opening the asset information again the focal point is displayed where it is.

**Expected behavior:**
Not wandeering to the upper right corner between the context of different assets, and not needing to reload the page to get it displayed correctly again ;)

**Steps to reproduce:**
see above

**Comment by onefriendaday** [comment]
We couldn't reproduce this issue. Could you please tell us your browser and what do you mean with image component? Don't you mean an image field?

**Comment by bstrdChronicles** [comment]
@onefriendaday yeah, well sorry - I am talking about the asset field.

Using Chrome 83.0.4103.106

reproducable on environment local or deployed environment
example in space 88054
example story /surveillance/new-york

go into the first or second image component - click the uploaded asset in the asset  field ( called image )

the first time you  click on an asset that has a focus point set  its displayed in the upper right corner:

![image](https://user-images.githubusercontent.com/24302245/86927525-bb69fe00-c133-11ea-8ab5-875de06db148.png)

then you click on the second image and its asset to check the focal point - and there is is correctly displayed as set.

![image](https://user-images.githubusercontent.com/24302245/86927594-cfadfb00-c133-11ea-82f7-f26cfbc980d1.png)

you go back to the first one and see its correctly displayed as set now as well ....

![image](https://user-images.githubusercontent.com/24302245/86927687-eeac8d00-c133-11ea-954e-a67264e3f682.png)

sometimes after a page reload, sometimes after switching between two Image components and their asset fields - I dont quite get what the real trigger is where he loses the ability to display it correctly.

**Comment by onefriendaday** [comment]
Thanks! We deployed a bugfix. Please reload your browser window and try again.

**Comment by bstrdChronicles** [comment]
@onefriendaday cool! Thanks a lot! :)
