### ISSUE TITLE
Field Translation translate base language content

### ISSUE THREAD

**Issue by bstrdChronicles** [storyblok/storyblok#359]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
If a field is translatable and has not been translated yet, it is really weird and exhausting that the content of the main language gets removed from the field the moment you click translate in the language. 

**Expected behavior:**
The content of the main language should be there if you click translate and no translation content was inserted yet into the language translation.
Having the main language content in there as base to work from would not hurt but improve the whole translation process.

**Steps to reproduce:**
Easily reproducable with every field translation.

**Comment by onefriendaday** [comment]
You can use the copy button to copy the existing translation to the field.
![](https://a.storyblok.com/f/85420/340x96/6bb3f5dae9/translate.jpg)

**Comment by bstrdChronicles** [comment]
@onefriendaday how do I get that one ? Cant seem to see that button there

![image](https://user-images.githubusercontent.com/24302245/86925977-cf146500-c131-11ea-882b-958d5ac360be.png)

**Comment by bstrdChronicles** [comment]
@onefriendaday 
oohhhhhh you then have to click on the Fieldname where the carrot down symbol then is visible...
Quite the hidden functionality - thanks :D
