### ISSUE TITLE
[Improve Request] Nestable component groups in the CMS interface

### ISSUE THREAD

**Issue by danielbrooks4p** [storyblok/storyblok#36]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
All component groups are currently treated as top-level groups. Current structure:

Components
--> **Layout** _(Group)_
-->--> Grid _(Component)_
-->--> gridItem _(Sub-component)_
-->--> gridSpacer _(Sub-component)_
--> **Common** _(Group)_
-->--> someComponent1 _(Sub-component)_
-->--> someComponent2 _(Sub-component)_
--> **Helpers** _(Group)_
-->--> someComponent1 _(Sub-component)_

**Requested behavior:**
Would like the ability to nest these groups similar to a file tree in order to reflect the Vue component structure. This gives greater flexibility in whitelisting sub-components within their respective schemas. Requested structure:

Components
--> **Layout** _(Group)_
-->--> Grid _(Component)_
-->--> **Grid** _(Group)_
-->-->--> gridItem _(Sub-component)_
-->-->--> gridSpacer _(Sub-component)_
--> **Common** _(Group)_
-->--> someComponent2 _(Sub-component)_
-->--> **Helpers** _(Group)_
-->-->--> someComponent1 _(Sub-component)_

**Other information:**
Currently, in order to achieve the desired effect, you'd have to set up the Common and Helpers groups to have overlapping components contained within them (see current structure) to avoid having to either individually whitelist components - a nightmare if your component list is large, shared between multiple spaces, or when you deprecate and remove components over time - or whitelist a top-level group containing other components that you do not wish to be whitelisted (someComponent1 vs someComponent2 in the Common and Helpers groups).

Under the proposed feature, an admin could choose to only whitelist for the Grid its own subcomponents and the Helpers sub-components. Conversely whitelisting the Common group would whitelist all components contained within Common AND Helpers because Helpers is nested within it.

This greatly reduces the time overhead in managing and maintaining a clean component directory in Storyblok, and it also reduces the risk of accidental overlap or permission deficit when whitelisting, deprecating, and managing components in a complex instance of Storyblok.

**Comment by onefriendaday** [comment]
Unfortunately this will not be added to Storyblok because of the level of complexity. The recommended way to manage deprecated components is to use the management api.
