### ISSUE TITLE
storyblok CLI sync component groups does not work as expected

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok#366]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* <!-- => CLI

**Current behavior:**
Storyblok sync is still lacking the correct sync of component groups. There seems to be a mismatch between component groups even if the naming is identical. I use component groups to restrict `blok` components and after sync the target space is missing the restricted component group components. 
`storyblok sync —type components —source 123 --target 321`

**Expected behavior:**
Component groups restrictions should work after a sync.

**Steps to reproduce:**
I can reproduce it with every sync: components with a restriction to a specific component group are not correctly handled. 
I am happy to do a screenshare to show the bug.

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue, @dohomi . Could you share with us this screenshare?

**Comment by dohomi** [comment]
@emanuelgsouza sure just write me a DM on Discord or here and I can showcase the issue

**Comment by dohomi** [comment]
@emanuelgsouza the merged PR does not fix my issue
