### ISSUE TITLE
[Feature Request] Search by Component Content

### ISSUE THREAD

**Issue by pjung16** [storyblok/storyblok#37]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**

Search function is only applicable to the whole story and not the individual components/blocks within the story.

**Expected behavior:**

API returns only the components/blocks within a story that satisfy the search term in the GET request if specified (Maybe an extra parameter called filter_blocks can be added? If not specified, API call will work normally and return the whole story.) 

**Related code:**

```
curl https://api.storyblok.com/v1/cdn/stories?token=XXXXXX&search_term=hello&filter_blocks=true
```
This will only return the blocks in the stories that have the word "hello" in them.

**Comment by DominikAngerer** [comment]
Hey there!

A feature like this is currently not planned but was discussed before and was postponed due to missing use-cases from our customers. What would be the use-case you would fulfill with this feature? How would you expect this to behave if you have multiple components on different nesting levels in the same story that match the content? 

Looking forward to your feedback & thanks for the feature request!

Cheers,
Dominik

**Comment by pjung16** [comment]
Hi!

It was going to mainly be used in an FAQ search section. Since our FAQ page is hosted on storyblok, I was hoping there was a feature like this since we wanted users to be able to search for questions and answers. I'm not quite sure how it would work with multiple components in different nesting levels, but perhaps a component_list to only return results that are in that list. In my case, I would only want the component that contains the questions and answers. This would also be applicable to the sub-components as well. 

Thank you!

**Comment by onefriendaday** [comment]
We recommend to use a specialized search engine like Algolia or Swifttype for that and push the component date with a Storyblok Published webhook into there search engine.
