### ISSUE TITLE
GraphQL Schema Incomplete

### ISSUE THREAD

**Issue by ashley-hurkoo** [storyblok/storyblok#376]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [X ] *Other:* 

**Current behavior:**
Retrieving schema via the Apollo cli does not generate the complete Schema.
[schema.json.txt](https://github.com/storyblok/storyblok/files/4953318/schema.json.txt)

**Expected behavior:**
A schema with a full component tree being generated

**Steps to reproduce:**
The items under the Carousel are not retrieved by the GraphQL schema.
![image](https://user-images.githubusercontent.com/49742186/88052911-53d59900-cb9e-11ea-99c7-f606fcb51498.png)

**Comment by vermadev** [comment]
I am facing something very similar. How can we get a resolution on this?

**Comment by onefriendaday** [comment]
Can you tell the space id please?

**Comment by onefriendaday** [comment]
I can see a DashboardComponent which has a carousel field which is a BlockScalar type. This type has no nested type definition by intention. It is like a Richtext/Json field like in other headless CMS as this field can contain any value and be deeply nested.

**Comment by vermadev** [comment]
@onefriendaday when u say by intention u mean done by the developer? If type is changed, can we see the details in schema?

**Comment by ashley-hurkoo** [comment]
@onefriendaday can you recommend how I should be setting this on StoryBlok so that I see it in the graphql schema?  Space ID: #87760

**Comment by onefriendaday** [comment]
> @onefriendaday when u say by intention u mean done by the developer? If type is changed, can we see the details in schema?

I mean that this is how the api works. Only the first level of the content type fields have strict types. The BlockScalar type is like a JSON field and therefore not typed. 

> @onefriendaday can you recommend how I should be setting this on StoryBlok so that I see it in the graphql schema? Space ID: #87760

You can set the checkbox "Act as content type" in the schema configuration if you really want to have the schema of the carousel item. Otherwise you can just get the field by following query 
```
{
  DashboardItems {
    items {
      content {
        carousel
      }
    }
  }
}
```

**Comment by richardtapendium** [comment]
@onefriendaday 

Have tried your suggestion of making the `carousel` and `carousel_items` content types (See below). Still don't seem to be able to drill in any further in GraphQL.

![image](https://user-images.githubusercontent.com/65693691/88124779-3d1c5a00-cc11-11ea-81e1-75bd58d912aa.png)

I'm running this query on space id of `89323`.

```
{
  NewpageItems {
    items {
      content {
        carousel
      }
    }
  }
}
```

Am I doing something wrong?

**Comment by samuells** [comment]
@richardtapendium I checked out your space and I didn't find `Newpage` component. My guess is you are looking for this query:

```
{
  DashboardItems {
    total
    items {
      content {
        carousel
      }
    }
  }
}
``` 

btw if you explore your space using the Draft token in the GAPI Browser `https://gapi-browser.storyblok.com/?token={DraftToken}`, you are able to click on **Explorer** button and see all the stuff accessible with GraphQl

**Comment by ashley-hurkoo** [comment]
@samuells @onefriendaday To give you guys a little bit of context, We are using this in an Android Kotlin app i.e. it is Strongly typed. Apollo provides the ability to download a schema and generates Strongly typed objects & classes at build time that automatically binds those objects when we make graphQL queries via the Apollo Kotlin SDK. Given that all blocks are BlockScalar type means those objects cannot be generated at build time and hence this issue.

Where my understanding is failing me is that, why is a Block not typed? A Block is a defined set of field at the end of the day as per your own definition, why not strictly type them?

![image](https://user-images.githubusercontent.com/49742186/88174968-821fab00-cc68-11ea-8269-3e6edadbc62c.png)

**Comment by onefriendaday** [comment]
It's not strongly typed due the fact that a blocks field can contain any level of complexity. It can contain hundreds of different components on multiple nested levels. So imagine a project where you have very fine graded components like "row", "column", "headline", "paragraph", ..., It would need a huge query to get the data out of a complex blocks field like this. This is why we choose to use a JSON like type for the blocks field. Maybe this discussion here https://github.com/apollographql/apollo-android/issues/752 helps you to find out how to write a custom adapter for the blocks field and apollo.
