### ISSUE TITLE
Asset manager does not add asset to data list in the SEO app

### ISSUE THREAD

**Issue by danielbrooks4p** [storyblok/storyblok#38]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
While using the SEO app in the CMS interface, adding an og:image does not load the image from the asset directory. The asset is not sent to the front-end. No console errors are reported.

**Expected behavior:**
Every other app that uses the asset interface correctly adds the asset to the data list and shows a preview of the image URL. Also, there is no ability to add an external URL link like in other instances of the asset manager.

**Steps to reproduce:**
Install the SEO app into an instance of Storyblok.
Add the plugin to a component schema.
Edit the meta for the component.
Click "Show/Hide advanced"
Click "Select asset" under OG Image
Attempt to add existing asset as OG Image

**Other information:**
This may just be due to the SEO plugin using an out-of-date version of the asset manager. Utilizing the asset manager in any other context does not produce this bug.

**Comment by onefriendaday** [comment]
The SEO plugin has been updated and show the image now.

**Comment by danielbrooks4p** [comment]
@onefriendaday, outstanding! Thank you.

Is there any possibility that this plugin would support adding og:image from an external URL? We host all other images on S3 and it doesn't make sense to make a request to a new domain just for this one image. 

Is that a new feature request, or a related item to this bug?
