### ISSUE TITLE
Access-Control-Allow-Origin headers on CDN served images

### ISSUE THREAD

**Issue by RicLeP** [storyblok/storyblok#380]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* Asset CDN

**Current behavior:**
Images served from the CDN lack an Access-Control-Allow-Origin header. This means browsers block access to the pixel data of the images via JavaScript which is required when using WebGL or libraries like PIXI.js.

**Expected behavior:**
Images should have the header set as so: access-control-allow-origin: *

This would match how Cloudinary serves images and videos giving developers more scope to manipulate them,

**Steps to reproduce:**
Request an image from the CDN and check it’s headers in the browser.

**Comment by onefriendaday** [comment]
You can access the image with the access control headers set by prepending s3.amazonaws.com.

Example: https://s3.amazonaws.com/a.storyblok.com/f/85420/300x200/678a8ce161/300px-johnrogershousemay2020-webp.png

**Comment by RicLeP** [comment]
Hello, the link you provided doesn’t have the  access-control-allow-origin header included, here’s the headers.

![image](https://user-images.githubusercontent.com/19726976/88306376-8dbfb000-cd02-11ea-979a-a5c1c072edc1.png)

I’m not sure if this is of any help? https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

Thanks

**Comment by sever1an** [comment]
@onefriendaday This suggestion will also not work with the image optimization service, which certainly does not live in a static S3 bucket. (img2.storyblok.com)

**Comment by remcoder** [comment]
The offered workaround of prepending `s3.amazonaws.com` doesn't work anymore. 

see this example url that was given above:
https://s3.amazonaws.com/a.storyblok.com/f/85420/300x200/678a8ce161/300px-johnrogershousemay2020-webp.png

Can this issue be reopened?

**Comment by AdrianFahrbach** [comment]
The workaround still works, it just doesn't work with the CDN modifiers (e.g. resizing with `/m/480x480`).
Would still be nice to add this to the documentation though.

**Comment by AdrianFahrbach** [comment]
I think this issue is a duplicate of #580.
[The solution described there](https://github.com/storyblok/storyblok/issues/580#issuecomment-1511525622) is to use `a2.storyblok.com` instead of `a.storyblok.com`.
