### ISSUE TITLE
Visual indicator for workflow stage of stories

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#39]
**The issue occurs while working with:** (check one with "x")   
- [ x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x ] feature request  
- [ ] question

**Current behavior:**

There are three colors for showing if the story hasn't been published now (light grey), has been published but also has been modified (light blue) and has been published (blue)
**Expected behavior:**

As in some cases it is useful to be able see if there are still stories in the workflow stage Drafting / Reviewing / Ready to Publish but not published yet or have been modified and been published before it would be a help to have a ring outside of the already existing indicator to see in what stage the story actually is.
Another variation could be a colored dot in the middle to indicate the stage or two overlapping dots.
![ring](https://user-images.githubusercontent.com/12159917/60963502-5b096c00-a2e7-11e9-880e-c9794bb06216.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Users can now see the workflow status in the list view:

![](https://a.storyblok.com/f/51376/946x368/356b23f6fd/visual-indicator.jpg)
