### ISSUE TITLE
Remove Filename input on replace asset option

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#395]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Replace Assets App* 

**Current behavior:**
When using the replace assets app and clicking on a file to upload the option to rename the asset appears.
After entering a new name or leaving it as is the name in the assets manager doesn't change so it seems that the option isn't functional at this point.
[Bildschirmvideo aufnehmen 2020-08-03 um 08.02.26.zip](https://github.com/storyblok/storyblok/files/5015556/Bildschirmvideo.aufnehmen.2020-08-03.um.08.02.26.zip)

**Comment by onefriendaday** [comment]
Has been fixed
