### ISSUE TITLE
Story settings: Save story-date with hour, mintues and seconds currently not possible

### ISSUE THREAD

**Issue by PhilippLupo** [storyblok/storyblok#4]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   
- [ ] *api.storyblok.com*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  

**Current behavior:**
Saving the date within the story settings with hour, minutes and seconds is not possible, allthough you can select this data.

**Expected behavior:**
Saving the date withing the story settings with hour, minutes and seconds should be possible.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Hey Philipp,

We've investigated your issue and see that you're trying to set the Story `sort_by_date` using a self-written plugin - nice work. Sadly the field `sort_by_date` will only save the date into our database. If you want to sort your stories according to a field in your root component you will be able to achieve this like you already did it with the `filter_by` functionality. Stay tuned :)

Br,
Dominik

**Comment by onefriendaday** [comment]
Hi Philip, you can now filter by component values with a point annotation.
Example: /v1/cdn/stories?token=XXX&sort_by=content.my_sortby_datetime%3Aasc
