### ISSUE TITLE
Custom Language / Locale indication in the top menu bar

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#40]
**The issue occurs while working with:** (check one with "x")   
- [ x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x ] feature request  
- [ ] question

**Current behavior:**

Custom Languages doesn't show up in the selected language in the top bar
**Expected behavior:**

When using a customized language / locale it would be useful to see the selection in the top bar in the editor view.
![local](https://user-images.githubusercontent.com/12159917/61119558-7bfdc880-a471-11e9-95ab-578c5d724186.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed. Thanks for the report!
