### ISSUE TITLE
Schema type Link -> Email field is not queryable via the Graphql API

### ISSUE THREAD

**Issue by ffriedl89** [storyblok/storyblok#409]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* *gapi.storyblok.com/v1/api* 

**Current behavior:**
When using a Link field and enabling the email field - the email itself cannot be queried with the GraphQl API. 

**Expected behavior:**
I can query the email field using the GraphQL api.

**Steps to reproduce:**

Add a field type "Link" to a Story's schema. Check the "Enable email field" checkbox in the configuration. Switch the type to Email in the editor and enter any email address e.g. "test@example.com". 
Then use the graphql api endpoint and query for the link field. 
E.g. with a query like 
```
query getEmail($id: ID!) {
  PageItem(id: $id) {
    id
    content {
      email {
        email
      }
    }
  }
}

```
You cannot query for that field due to the following error. 
```
{
  "errors": [
    {
      "message": "Field 'email' doesn't exist on type 'Link'",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "fields": [
        "query",
        "PageItem",
        "content",
        "email",
        "email"
      ]
    }
  ]
}
```
Checking the REST API gave me the information for the email field.
```
...
"email": {
        "id": "",
        "url": "",
        "email": "test@example.com",
        "linktype": "email",
        "fieldtype": "multilink",
        "cached_url": ""
      },
...
```
The fields id, url and cached_url are also empty on the GraphQL query if I query for those fields respectively which makes total sense.  

**Other information:**
Really love the capabilities of storyblok. Using it for the first time and I am amazed! 
Keep it up 🔥

**Comment by onefriendaday** [comment]
A bugfix has been released.
