### ISSUE TITLE
add option to restrict the Link Field Type to only use internal Links or external URLs

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#412]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
At the moment the link field allows by default that the editor can choose between an internal link and an URL. This can be a problem for the developer if he wants that the editors use only one of both in the content.

**Describe the solution you'd like**
New setting flags could be added like disallow external urls or internal links.

This feature request is based on the forum thread:
https://forum.storyblok.com/t/restrict-the-link-field-type-to-only-use-internal-link/337

**Comment by SebbeJohansson** [comment]
I too would like this to be a thing. Insane to think that nothing has happened since 2020.

**Comment by stefanobartoletti** [comment]
I also would like to see this feature to be effective. Any chances that this will be addressed on the near future?

**Comment by natmira** [comment]
Also would like to see this feature

**Comment by GhayoorUlHaq** [comment]
Indeed, that would be a valuable addition. Currently, an alternative for exclusively utilizing external links (URL) is to employ a Text Field.

**Comment by EMurrell** [comment]
I too would really like to see this feature

**Comment by strelok** [comment]
yeah.. why we can't modify this LINK field type :( 
It's so obvious that people want to modify link 'type'.
We really need to add custom types but we can't :(

**Comment by dogfrogfog** [comment]
i assume a `text field` with the url pattern regexp is the way to go right now 🙂

**Comment by strelok** [comment]
> i assume a `text field` with the url pattern regexp is the way to go right now 🙂

We are using richtext and there seems to be only one option, using default 'link' if you really need a usable linking.. 
So we are using some 'prefixes' inside a regular WWW link text field.. but it's so ugly and content managers has to check all the time correct syntax of those 'prefixes' etc

**Comment by alvarosabu** [comment]
Hi all, it was brought to my attention the status of this issue. By checking the description it seems to be a feature request on the Storyblok Product itself and not related to the CLI package (this repo). This issue was probably opened way before we had a workflow for the feature request

For product-related requests please use https://support.storyblok.com/hc/en-us. I will close this since is not related to Open Source but the product itself. I already pinged the support team to take a look if it's included on the Product Feature request or if should we create a new one.

Thanks
