### ISSUE TITLE
Assets Management refinement --> removing assets permananently using the frontend

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#42]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

 The user can upload assets via the frontend but not delete them using the same.
**Expected behavior:**

 For organization and usability reasons editors rely on being able to remove assets directly in the frontend without the need to consult a developer removing the unnecessary assets if bigger portions of the content changes or content changes frequently.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
When assets are moved to the trash bin the access will get removed and as soon the CDN cache gots refreshed they are not accessible which is like a permanent deletion. For restoring purposes we need to keep the references.
