### ISSUE TITLE
Incoporation of the native assets management with cloudinary when assets are already uploaded

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#43]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual stand of the behavior is that when the user decides to choose cloudinary to organize assets he can't access already uploaded assets through the assets manager anymore. The cloudinary app overwrites the access to all assets, even files.
**Expected behavior:**

A switch to be able to access -->already available<-- assets uploaded to storyblok and to be able to use cloudinary when the app has been installed. 
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by Slackman2015** [comment]
The cloudinary app overwrites the access to all assets, even files.

**Comment by onefriendaday** [comment]
The user can still access the assets via the sidebar at "Assets". I think a switch would confuse the users too much.
