### ISSUE TITLE
add possibility to close the Cloudinary app without the need to reload the browser window or to choose an asset

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#433]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Cloudinary App* 

**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to close the Cloudinary app by forcing the actual browser window to reload:
[Bildschirmvideo aufnehmen 2020-09-01 um 06.55.23.zip](https://github.com/storyblok/storyblok/files/5155491/Bildschirmvideo.aufnehmen.2020-09-01.um.06.55.23.zip)

**Describe the solution you'd like**
It would be a very helpful addition to be able to close the Cloudinary app without the need to reload the complete browser window or to be forced to choose an asset.

**Comment by onefriendaday** [comment]
The modal now includes a close button.
