### ISSUE TITLE
Extention of upload capabilities of the assets manager --> directories

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#44]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The user takes an asset or more during marking them in the "file upload" window and clicks on the open button. He has to create manually the directory or directories before he uploads the files which can be a time consuming task when the project has several directories that need to be created and change frequently.
**Expected behavior:**

The user chooses one directory or several in the "file upload" window and when clicking on open, the "assets manager" creates the folder(s) itself and uploads the content into the automatically created folder(s).
In the case that a directory already exists the user can choose to overwrite (assets with same name but different size etc gets deleted into the trashbin, this adds some security in the case of user errors), replace (deletes the content but files remain in the trashbin) or merge (just adds new content without touching the existing) the whole directory with the new (content).
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
I think this is technically not possible. The file upload window can not modified by us as they are operating system specific and folders can not be used in the file upload dialog.
