### ISSUE TITLE
minimum and maximum settings stay active in the background when changing from multi to single option field type

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#448]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
When creating a multi option field and setting a min and max for it and saving it then in the next step changing the type to a single option field the UI will show an error complaining about the not reached minimum of 1 even when it when it was set to 1 as the minimum as a multi option field:

![Unbenannt35](https://user-images.githubusercontent.com/12159917/93326975-0f5a2880-f7f0-11ea-81ea-02e33139424e.png)

**Comment by onefriendaday** [comment]
Has been fixed

**Comment by dsteinbach** [comment]
Thanks!
