### ISSUE TITLE
Fast field duplication inside of the scheme editor

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#45]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The user has to go into the "scheme editor", type a name/key in the name field and click add. This is a repeating work process for all fields even for fields of the same type and configuration. Each element has to be configured individually even when they have the same configuration.
**Expected behavior:**

For faster duplication there could be a button in front of the field element what creates a copy of the actual original with all settings and an appendix added to the name the like testbox1, textbox2... or with an underscore. This is an adaptation of the repeating field concept of WP expanded to all field type to make field duplication easier.
![Unbenannt](https://user-images.githubusercontent.com/12159917/61310765-53583480-a7cb-11e9-9349-3158587cb7e0.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
We think that the field creation is fast enough for the average user. You can write a small console script to duplicate fields with the management api.
