### ISSUE TITLE
Whitelist option for the dimensions app

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#46]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The user can create a multi tree structure for the internationalization utilizing the dimensions app. The root of the tree structure starts also in the root of the space what can bring some caveats with it for example that editor can overwrite accidentally other directories or merge the content so to say it can cause some confusion.
**Expected behavior:**

A whitelist option could limit the count of directories (improves clarity), reduces the chance to modify the wrong directory and saves time in the long run when many directories are placed into the root of the space.
Furthermore it should be possible to restrict access to the whitelist in respect of the different user roles.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
It's already possible to restrict access in user roles. When a user has not access to a specific folder via the "Folder-Permissions" he can not overwrite or change stories in that directory.

**Comment by Slackman2015** [comment]
The idea is basically good but lacks the option for the user to be able to modify other content when those stories and directories aren't whitelisted. The stated solution in this feature request expands the possibility to use the dimensions app only on allowed directories (when the white list has been used) which makes it easier to work with it and still be able to continue working normally without being blocked by those restrictions to not overwrite content in other directories.

**Comment by onefriendaday** [comment]
For the average user the Folder-Permissions are enough. We can reopen this issue if more users are having this problem.
