### ISSUE TITLE
`Parent` object isn't in API and GraphQL result

### ISSUE THREAD

**Issue by MKlblangenois** [storyblok/storyblok#460]
**The issue occurs while working with:**
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other: https://gapi-browser.storyblok.com/*

**Current behavior:**
When I try to get the parent of my story, I just got the `parent_id` and not `parent object` like in the [documentation](https://www.storyblok.com/docs/api/management#core-resources/stories/the-story-object)

**Steps to reproduce:**
When I reach `/spaces/:my_space_id/stories/`, I got this result :

![API result](https://i.ibb.co/HTqK4Cg/Capture-d-e-cran-2020-09-25-a-17-52-35.png)

We can see that `parent_id` is good but there's no `parent object`

Same result in GraphQL playground
![GraphQL result](https://i.ibb.co/5xsGBnz/Capture-d-e-cran-2020-09-25-a-18-00-53.png)

**Comment by onefriendaday** [comment]
This information is only available in the single story endpoint: spaces/:my_space_id/stories/:id
