### ISSUE TITLE
Define Required Asset Fields

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#466]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**

As an enterprise customer I need to make sure that my copyright information are always present at assets that I share globally.

**Describe the solution you'd like**

I would like to be able to define that some or all fields of an asset (Alt, Copyright, Title/Caption) should be able to be marked as requiered on space level. After uploading an image, the overlay should open and a marketer should have to add the information required. Configuration of those fields should be in the space settings, either by checking a checkbox or multi select options of a field.

**Describe alternatives you've considered**

An alternative that was consider is to add a copyright field as required to the component itself, but that would mean that I would have to repeat the copyright information multiple times & also update on multiple places rather than directly on the asset.

**Comment by onefriendaday** [comment]
https://www.storyblok.com/cl/required-asset-fields
