### ISSUE TITLE
Tiny MCE Plugin doesn't scale to max width in form only mode

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#47]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

The tinymce WYSIWYG plugin doesn't scale in the width direction in the form only mode.
![Unbenannt](https://user-images.githubusercontent.com/12159917/61451773-954ebb00-a930-11e9-897f-cf3acdb513ca.png)

**Expected behavior:**
The plugin should be able to use the available width in the form only mode to fit the overall appearance of the frontend.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Fixed
