### ISSUE TITLE
Asset information (alt, copyright etc.) doesn't update in API until reselecting asset in component fields

### ISSUE THREAD

**Issue by philippgerbig** [storyblok/storyblok#481]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   

**Current behavior:**
If I choose an image from the assets library in a field, the alt text of the image will not be updated in the api response until I choose the same image again in the component field. Publishing and everything else doesn't help. I have to deselect the image in my component and select it again.

**Expected behavior:**
Changed alt, title and copyright information in the asset library should change after saving the asset in the api response.

**Steps to reproduce:**
Add asset to your library, choose it in some content element, change asset alt text afterwards, have a look in draft/published json.

**Comment by onefriendaday** [comment]
This information is duplicated to the content item so it can be overwritten locally by the user. Therefore the information in the asset manager is meant to be only a template.

**Comment by philippgerbig** [comment]
Oh, ok. I thought editing this by clicking on the assets name would edit in the asset library. Ok, so the story has its own duplicate... Thanks for clarifying.
