### ISSUE TITLE
Error message for required field takes wrong field name (doesn't use display name)

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#49]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

When marking a field as required and a setting a name in "display name" isn't being used in the error message when one doesn't fill it when clicking on save.
![Unbenannt](https://user-images.githubusercontent.com/12159917/61461270-c508bd80-a946-11e9-883f-55ce87d8bb2c.png)

**Expected behavior:**

 The users expectation is that the error message uses the actually shown name of the field.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been fixed.
