### ISSUE TITLE
Documentation for storyblok-latest.js

### ISSUE THREAD

**Issue by talbet** [storyblok/storyblok#5]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com*   
- [x] *api.storyblok.com*   
- [ ] *Other*

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  

**Current behavior:**
The `storyblok-latest.js` file is referenced in several tutorials, but there is no documentation around it use or api.

**Expected behavior:**
It would be excellent to have more details about the use of this script, in particular:

- Is it published on NPM, and can it be bundled rather than required.
- Is it possible to use this library to request data with a public key to get the live version of a page
- Is there a mechanism to detect if the library has been loaded in an iFrame (i.e. in the Storyblok backend)

Storyblok is very promising and has been great to use, great work!

**Comment by DominikAngerer** [comment]
Hey @talbet - thanks for your feedback.

We've updated our documentation for the [storyblok-latest.js](https://www.storyblok.com/docs/Guides/storyblok-latest-js#storyblokisineditor-and-pingeditor) - you find it right here: https://www.storyblok.com/docs/Guides/storyblok-latest-js

1. The storyblok-latest.js is currently not on NPM 
2. Currently the AccessToken is the privateToken (which is also read only) https://www.storyblok.com/docs/Guides/storyblok-latest-js#storyblokisineditor-and-pingeditor
3. Yes - Using this method you can detect if you're in the Storyblok editor or not (https://www.storyblok.com/docs/Guides/storyblok-latest-js#storyblokisineditor-and-pingeditor)

Hope we got your points covered - happy to hear you like Storyblok!
