### ISSUE TITLE
Allow anchors in internal links

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#50]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
There is no way to specify an anchor id, when using internal links

**Expected behavior:**
It would be great if it were possible to specify #anchor after selecting the internal link.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
@onefriendaday additional to https://www.storyblok.com/features#link-selection-browser?

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/anchor-option-for-internal-link

**Comment by hesamjs** [comment]
Is it also possible to add anchor option for links within richtext?

**Comment by venux92** [comment]
It will actually be great to be able to set an id on an element and then be able to link to that anchor. (within richtext)

**Comment by mckelvey-jack-AND** [comment]
IS there an update on being able to link to the anchor from within the rich text?
