### ISSUE TITLE
Thumbnail Preview for images in "Block" content type

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#52]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Unable to distinguish between images in a "Block" type – no thumbnail preview is provided in overview. Impossible to manage groups of images, rendering "Block" type unhelpful for slideshows / pages with mixed media. 

<img width="1552" alt="Screenshot 2019-07-28 at 15 26 43" src="https://user-images.githubusercontent.com/12583581/62009511-eb550700-b157-11e9-9236-415cdd471eb8.png">

**Expected behavior:**
Thumbnail preview for each image. 

![Screenshot 2019-07-28 at 15 26 43](https://user-images.githubusercontent.com/12583581/62009514-f019bb00-b157-11e9-9e42-d3bf65e7d90b.jpg)

**Comment by DominikAngerer** [comment]
connected to: https://www.storyblok.com/features#multiple-values-for-block-preview

**Comment by simonhrogers** [comment]
Hey Dominik – is the above link an internal thing? I’m unable to see

**Comment by DominikAngerer** [comment]
Now Available: https://mobile.twitter.com/storyblok/status/1160833061556314118
