### ISSUE TITLE
Responsive Images feature returns 500 error for many images

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#53]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Many images fail to load (seemingly at random) when loading a page of images which calls different sizes of images to be resized by Storyblok. Server sometimes very slow to respond with images which are not yet cached / resized... Storyblok very quick when no resize operations are asked for.

https://aoc-architects.netlify.com/

<img width="1552" alt="Screenshot 2019-07-28 at 23 41 06" src="https://user-images.githubusercontent.com/12583581/62013891-7272a100-b191-11e9-8962-7766f548541e.png">

**Expected behavior:**
No 500 errors, quicker more reliable resizing.

**Other information:**

**Comment by onefriendaday** [comment]
Thanks for the bug report. The problem has been fixed and images should load again.
