### ISSUE TITLE
Filtering stories with `version=published` doesn't include stories in subfolders

### ISSUE THREAD

**Issue by Philipp-M** [storyblok/storyblok#538]
**The issue occurs while working with:** (check one with "x")   
- [x] *api.storyblok.com (CMS - Content Delivery API)*

**Current behavior:**
When requesting stories that should be published e.g. like this:
```sh
curl 'https://api.storyblok.com/v1/cdn/stories/?token=<token>&version=published'
```

Only stories at the root are retrieved.
E.g. /sub-folder/story
is not provided by the api, although the story is published.

when omitting the version query filter, all is working as expected

**Expected behavior:**

Provide all stories that are published with this query filter.

**Steps to reproduce:**

Create a sub folder and a story and publish it.
then try this:
```sh
curl 'https://api.storyblok.com/v1/cdn/stories/?token=<token>&version=published'
```

**Comment by onefriendaday** [comment]
It seems that you may access a cached version. We recommend to add the "cv" parameter to the url as documented here: https://www.storyblok.com/docs/api/content-delivery#topics/cache-invalidation

**Comment by Philipp-M** [comment]
This was indeed the problem, thanks!
