### ISSUE TITLE
Updating datasource unlinks all references to it?

### ISSUE THREAD

**Issue by Johngeorgesample** [storyblok/storyblok#545]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**
I'm attempting to use a datasource for some text that lives in a few components. Ideally, changing the datasource's value would update every reference to it. However, it appears that updating the datasource automatically unlinks any component that was using it.

Is this expected behavior? If so, is there a setting that would keep the connection between component and datasource even after the value is changed?

**Comment by onefriendaday** [comment]
There is no setting to enable this functionality. As alternative you can use a multi-options or option field with stories as source or use the migration cli to update the values in the content.
