### ISSUE TITLE
Cut/copy component from component config view

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#55]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
If you want to copy/cut a component in the GUI, you click on the component in question, then you have to navigate up the tree using breadcrumbs, then find the component in the bloks list and copy/cut it.

**Expected behavior:**
Click on a component in the GUI, copy/cut from the sidebar without any extra navigation.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Already available above the breakcrumb itself.

**Comment by hypeJunction** [comment]
Doh. Didn't see it.
