### ISSUE TITLE
No default values field for Multi-Options

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#56]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Unable to select default fields for a Multi-Options field type. 

**Expected behavior:**
You can for single option and this works great! I really need this functionality for the Multi-Options field as well, it seems like it would be very straightforward to add? I really need to be able to define all values to be selected by default.

**Comment by DominikAngerer** [comment]
You can use the Array syntax Like:

["val1", "val2", ... ]

to achieve that. A select all in default is not planned.

**Comment by simonhrogers** [comment]
Hey Dominik – I don’t have the field at all – please see screenshot.
<img width="451" alt="Screenshot 2019-08-06 at 00 30 41" src="https://user-images.githubusercontent.com/12583581/62501192-821d6580-b7e1-11e9-9e54-75d0476f9bd7.png">

**Comment by simonhrogers** [comment]
Additionally, it would be very helpful if a minimum could be set, e.g. minimum 2 options. But I appreciate this may be less essential.

**Comment by DominikAngerer** [comment]
@simonhrogers could you elaborate your use-case for the min option for us over here: https://github.com/storyblok/storyblok/issues/57 created a new ticket to handle that separately.

**Comment by DominikAngerer** [comment]
Now available.
