### ISSUE TITLE
add possiblity to the new table field to create joined cells like it is possible in HTML

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#574]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Describe the solution you'd like**
It would be a very useful addition to be able to create joined cells directly inside of the table plugin which would make the table field much more flexible and allow to change the table directly from the CMS side.

**Comment by wireless25** [comment]
I came across this issue because I also need to be able to join cells in a table. This is a requirement for my project, which makes it impossible to use the table field. Is there any progress on this? Is it on the roadmap, so I can estimate whether it is worth implementing ourselves?

**Comment by alvarosabu** [comment]
@wireless25 I wrongly referred to the CLI repo in my previous comment, I'm clarifying internally if this repo is still valid.
