### ISSUE TITLE
Markdown Lists – selecting block of text, could each new paragraph be made a list?

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#58]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
When selected a block of text in the markdown field, on pressing the "list" button I would hope for each new paragraph / line to be made a list item.

Selecting block of text:
<img width="334" alt="markdown-list-before" src="https://user-images.githubusercontent.com/12583581/62537589-afe9c500-b848-11e9-9c1a-6fa2ea00b550.png">

Applying the list, only one paragraph is made a list:
<img width="347" alt="markdown-list-after" src="https://user-images.githubusercontent.com/12583581/62537590-b2e4b580-b848-11e9-80ad-1d01f03fd133.png">

**Expected behavior:**
Ideally, all paragraphs could be made their own list:
<img width="330" alt="markdown-list-expected" src="https://user-images.githubusercontent.com/12583581/62537631-cf80ed80-b848-11e9-9f37-ae5a75925471.png">

**Comment by onefriendaday** [comment]
Got released: https://www.storyblok.com/cl/markdown-field-transform-paragraphs-to-a-list
