### ISSUE TITLE
Asset Folder Sorting (Alphabetically/Manually)

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#59]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
They are sorted by date of creation, which clients have commented is unhelpful – creation date seems like an arbitrary decision. 

**Expected behavior:**
Even just alphabetical would be amazing, but sorting as per other elements of the site welcome too.

![Screenshot 2019-08-07 at 12 44 42](https://user-images.githubusercontent.com/12583581/62620398-26ea9080-b911-11e9-88e5-8c5c128adbaa.png)

**Comment by onefriendaday** [comment]
Asset folders are now sorted by the name.
