### ISSUE TITLE
Navigation from block back into project is troublesome

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#60]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**

Within a story, I scroll down to my block content:

![Screenshot 2019-08-07 at 12 47 29](https://user-images.githubusercontent.com/12583581/62620578-99f40700-b911-11e9-9e82-7ce5893cd274.png)

I click into a block and change some information:

![Screenshot 2019-08-07 at 12 47 42](https://user-images.githubusercontent.com/12583581/62620580-99f40700-b911-11e9-8414-90c3df227bc2.png)

I click back to the project, but the page doesn’t remember my scroll position within the UI, so I have to scroll all the way down again. 

![Screenshot 2019-08-07 at 12 47 54](https://user-images.githubusercontent.com/12583581/62620582-99f40700-b911-11e9-91ed-3bcb86600372.png)

Uploading 15 images and some text to this block section, I have to scroll back down the page almost 20 times – feels repetitive and jumping back to the top feels unintuitive. 

**Expected behavior:**
Remembering position on project edit panel after editing a block element.

**Comment by onefriendaday** [comment]
Maybe this new feature helps you do better identify the blocks in the sidebar:
https://www.storyblok.com/cl/custom-block-preview
