### ISSUE TITLE
Rich Text / Markdown - Customise Toolbar Options (Bug)

### ISSUE THREAD

**Issue by tomSawkins** [storyblok/storyblok#61]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Rich text editor has an option to customize the toolbar options. However trying to set these options will remove the toolbar entirely when editing a story. 

It also has every option selected when going back in to edit the component schema after saving

Before Saving:
<img width="401" alt="Screen Shot 2019-08-12 at 4 51 47 pm" src="https://user-images.githubusercontent.com/3917484/62849090-8d145080-bd21-11e9-8d86-a25f6b6cdbf3.png">

After Saving:
<img width="397" alt="Screen Shot 2019-08-12 at 4 52 00 pm" src="https://user-images.githubusercontent.com/3917484/62849089-8c7bba00-bd21-11e9-906e-ca5bcded1fb4.png">

**Expected behavior:**
Save selected options & restrict the toolbar to those options

**Steps to reproduce:**
Add a field using the `Markdown` type and try and customise the toolbar.

**Related code:**

N/A

**Other information:**
Based on the api request from the ui on save it doesn't look like the options are being recorded in the schema
```
schema: {
    body: {
       can_sync: true
       customize_toolbar: true
       display_name: "Content"
       pos: 2
       required: false
       rich_markdown: true
       toolbar: true
       translatable: false
       type: "markdown"
   }
}
```

**Comment by onefriendaday** [comment]
Thanks for the bug report!

We deployed a hotfix. After reloading your Browser window the bug should went away.
