### ISSUE TITLE
Command Line Interface - 

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#62]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The user can push components (schema data) between spaces with the CLI (command line interface). At the moment it isn't possible to copy the content itself between spaces.
**Expected behavior:**

To make the life of developers easier a function to copy parts of the content like complete stories can help saving time and is a good addition to the shared components concept of the CLI.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
Coping content is a completely separated task as it is often bound to tasks in between the transfer. We've introduced this demo which uses our Management API directly: https://github.com/onefriendaday/storyblok-folder-sync-example 

It gives the developer the flexibility to transform data, if needed, without downloading an CLI but also be able to version the changes they made.
