### ISSUE TITLE
Link - Configurable Link options (ui feature)

### ISSUE THREAD

**Issue by tomSawkins** [storyblok/storyblok#63]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
When making use of the `Link` type there are 2 options when filling the field out to be either an `Internal link` or `Url` the later being just a free text field

It's not currently possible to restrict within the component schema that there is **only** the internal link option available when editing content

**Expected behavior:**
Have the ability to restrict the link options in the schema to be only internal, url or both in order to restrict content authors

**Other information:**
<img width="320" alt="Screen Shot 2019-08-13 at 1 34 48 pm" src="https://user-images.githubusercontent.com/3917484/62913376-29486100-bdcf-11e9-898b-dd79ddd74e50.png">
<img width="402" alt="Screen Shot 2019-08-13 at 1 35 29 pm" src="https://user-images.githubusercontent.com/3917484/62913407-411fe500-bdcf-11e9-87c6-9338a697c342.png">

**Comment by DominikAngerer** [comment]
I've added a link to our internal ticket for that feature. A link selection browser rebuild is already planned: https://www.storyblok.com/features#roadmap
