### ISSUE TITLE
Soft new line in markdown-html

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#65]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
When using `markdown-html` field there is no way to add a soft new line (i.e. `<br /`>). It's being stripped in the resulting HTML. You can only add new paragraphs.

**Expected behavior:**
Resulting HTML preserves new lines

**Steps to reproduce:**
Type in the text into the editor and separate two lines with a single new line. Both lines will appear in the same paragraph.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by simonhrogers** [comment]
I am using Marked to parse the markdown and soft line breaks are detected as long as you flag like so:

```
    parseMarkdown(markdown) {
      marked.setOptions({
        renderer: new marked.Renderer(),
        breaks: true
      });
      return marked(markdown)
    }
```

So unless I’ve misunderstood I believe this is already supported?

**Comment by DominikAngerer** [comment]
Hey @simonhrogers. Thats correct - its the task of the render process to determine if breaks are added or not. However the markdown-html plugin (non native) does that part already and allows to directly access HTML rather than the plain markdown - so a setting in that plugin will be the update option.
