### ISSUE TITLE
V2 JS Bridge styling issue

### ISSUE THREAD

**Issue by BJvdA** [storyblok/storyblok#653]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
The new V2 JS Bridge adds a min-height style rule to hoverable elements in the visual editor, overriding our styling and causing layout to shift extreme amounts on hover, making it unusable.

**Expected behavior:**

Styles should not be overridden by the JS Bridge.

**Steps to reproduce:**

Especially noticeable if you add min-height: 100vh to a section and then hover over it in the visual editor preview.

**Related code:** 

```
.storyblok--outlined .storyblok__outline {
	min-height: 5px;
	outline: 1px dashed #b6babf
}
```

**Comment by onefriendaday** [comment]
Has been fixed
