### ISSUE TITLE
Export App for fetching all Assets

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#66]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual way of backing Assets up is through S3 bucket and through the use of the management.
**Expected behavior:**

Although these given methods are good and flexible in some cases it can be an advantage to be able to backup assets with an app to solve the problem fast without the need to do further steps else than installing the app and choose the folders/assets for download.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
You can use the Management API to download your assets. This starter script can be extended: https://github.com/DominikAngerer/storyblok-asset-download
