### ISSUE TITLE
Prevent default on clicks

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#67]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
We have certain non-anchor components that initiate navigation using `$router.push`. It seems that the preview mode doesn't prevent default on clicks.

**Expected behavior:**
Clicks only highlight the component and don't propagate into the component.

**Steps to reproduce:**
Create a custom component with a click handler.

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by hypeJunction** [comment]
I do use nuxt. I have added this code and it has no effect.

**Comment by onefriendaday** [comment]
You may add global navigation guards: https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards
