### ISSUE TITLE
Would it be possible to resize images in advance?

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#68]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Question:**
Would it be possible to resize images in advance? 
Would this be beneficial? It seems like it would.

**Current behavior:**
Images are resized on request – resulting in a 3-4 second delay while assets are processed on the server 

**Ideal behavior:**
It would be amazing if you could define sizes that all assets are formatted in upon upload and stored permanently by Storyblok.  
 
For example I currently do: 250, 500, 750, 1000, 1500, 2000 and 2500. It would be amazing if these were stored statically, as Storyblok serves the original files incredibly quickly – but resizes seem to need to happen again every couple of hours for previously generated files – making me wonder if Storyblok does not store the dynamically generated sizes for very long? 

I don’t know if this is something you could offer easily or not – but I think it would be an amazing feature?

**Comment by onefriendaday** [comment]
Storyblok stores the generated files up to one year. Can you give me an example url?

**Comment by simonhrogers** [comment]
Oh wow! I shouldn't be having any problems then I guess

Referring to the domain here:
https://aoc-architects.netlify.com/

For e.g. https://img2.storyblok.com/2000x0/f/59379/2500x2483/cf9ebc0b60/aoc-gladstones-library-00.jpg

I noticed images were loading much quicker when no transforms took place (even at their original size of 2500px or more)

**Comment by simonhrogers** [comment]
Hey @onefriendaday – just wondering if you got anywhere with this? Sometimes Storyblok seems blazing fast and then moments like right now; some images are being sent to resize (which have been done before) and still not returned after 10s, with Chrome giving an asset not found error. Do you have any idea what could be going on?

e.g.
https://aoc-architects.netlify.com/projects/james-cook-the-voyages

**Comment by onefriendaday** [comment]
Storyblok's image service has been further optimized and the delay should not happen anymore.
