### ISSUE TITLE
Allow custom component labels

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#69]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Feedback from the client using Storyblok now: it is really hard to tell multiple components from one another in the list, i.e. in the sidebar you see a component name and some random string that was parsed from whatever field that happens to be first in line. It would be easier for editors to provide custom names for each component. For example, in our setup we have Page Section as the top level wrapper, and you may have 10 of them on the page, so you have to go in to see if that's the one you want to edit. 

**Expected behavior:**
Allow editors to optionally provide custom labels for each component that would appear in the sidebar instead of component name with random content string.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Our solution for this problem is to use a custom preview template:
https://www.storyblok.com/docs/schema-configuration#topic-preview

Would that help you?

**Comment by hypeJunction** [comment]
That might. Will give it a try tomorrow
