### ISSUE TITLE
Fallback language is ignored for linked story

### ISSUE THREAD

**Issue by stonys** [storyblok/storyblok#697]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
When I fetch story with component that has etc `section_link` field of type stories (resolve relations are also defined for that field), `fallback_lang` parameter is ignored and default language for that linked story is returned.

**Expected behavior:**
`fallback_lang` parameter could be respected. Any linked stories that doesn't have direct translation could return translation of the language defined via `fallback_lang` parameter.

**Steps to reproduce:**
Available languages are: English (default), Spanish, Spanish (Mexico)
Translation strategy: field translation
Story folders: Pages, Sections
Fallaback language for Spanish (Mexico) language: Spanish

- Create story "Section A" in "Sections" folder, with some fields. Add Spanish only translation.
- Create story "Page A" in folder Pages with component that has field `section_link` witch links to "Section A" story.
- Switch "Page A" language to Spanish (Mexico).

When retrieving "Page A" for Spanish (Mexico) language, "Section A" is returned with default English translation, not with Spanish translation, as defined via `fallback_lang` parameter.

**Related code:**

**Other information:**

**Comment by tlehwalder** [comment]
Are there any updates on this topic?
We have the same problem, fallback_lang is ignored and the default value gets returned.

**Comment by tlehwalder** [comment]
Support was able to help us.
In our case we sent in the request language='fr-CH' with fallback_lang='fr-FR'.
Because of how the language is stored internally, the fallback_lang value must be sent with underscore; in our case fallback_lang='fr_FR'.

**Comment by stonyscn** [comment]
Ok, this issue makes more sense now. I will check if using underscore solves it for me too. Will  Thanks for sharing @tlehwalder

**Comment by VojislavVlasic** [comment]
Hello @tlehwalder and @stonyscn , can we close this?

**Comment by tlehwalder** [comment]
Hi @VojislavVlasic ,
If it's up to me, yes.
But I think it would be useful to include the info somewhere in the documentation, if that's not already the case.

**Comment by VojislavVlasic** [comment]
Thank you!
