### ISSUE TITLE
API: List of stories should return total number of pages and current page

### ISSUE THREAD

**Issue by zash80** [storyblok/storyblok#7]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com*   
- [x] *api.storyblok.com*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  

**Current behavior:**
The API to list stories does not show the current page neither the number of total pages.

**Expected behavior:**
As the API to list stories allow to define stories per per page and a page it also should return number of pages and the currently selected page.

**Steps to reproduce:**

**Related code:**

**Other information:**

**Comment by onefriendaday** [comment]
You can access the totals and per page values in the header of the response.

**Comment by DominikAngerer** [comment]
Hey there! You can find the total number of stories in the header of that request „Total“ - therefore you can calculate the total pages - since you request it already with a certain page index you would already know your current page.

Thanks for your feature request!

**Comment by zash80** [comment]
Thanks for fast response. Currently I using Storyblok JavaScript Bridge - storyblok.getAll() - I may have to switch using the API directly.

**Comment by onefriendaday** [comment]
You're right. With getAll of the bridge you could not receive the headers. We extended that function with the xhr object and you can use it now like this:

~~~
storyblok.getAll({slug: '/'}, (data, xhrResponse) => {
  console.log(xhrResponse.getResponseHeader("Total"))
})
~~~

**Comment by zash80** [comment]
Sounds good!
