### ISSUE TITLE
Internal links in markdown should mirror Internal Link field type behavior

### ISSUE THREAD

**Issue by frameshft** [storyblok/storyblok#70]
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Current behavior:**
Internal links in markdown fields aren't updated if the linked entry's slug has been changed

**Expected behavior:**
Internal links in markdown fields should behave the same way as an Internal Link field type. (If the linked entry slug has been changed the link should be updated)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Unfortunately this can not be done with the Markdown field. We recommend you to switch to the new "Richtext" field.
