### ISSUE TITLE
[ISSUE: resolve_links with nested stories]

### ISSUE THREAD

**Issue by jbruxelle** [storyblok/storyblok#706]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Steps to reproduce:**

*Context :*

` • Frontend : Svelte Kit`

` • Queries : GraphQL`

` • Stories : `
        
```
* page : {
    header (a single option field restricted to /global stories),
    body (bloks),
    ... 
  }
```
```
* global/header : {
    navigation (component ): {
        links: (bloks restricted to link component) : {
            title: (Text),
            path: (Link (native))
        }
    }		
}
```

___
___

**THE QUERY** *(let's go with const params here)*

```
{
  PageItem(id: "en/home", resolve_links: "url") {
    content {
      header(language: "en") {
        content
      }
      component
      body
      metadata
    }
    name
  }
}
```

**Current behavior:**
```
RESULT :

    {
        ...
            "content": [
              {
                "_uid": "87becaa2-491d-4abb-9c83-2bb1ca3beb9a",
                "links": [
                  {
                    "_uid": "67c8701e-f2e4-49a1-b5b2-9783d907bfc7",
                    "path": {
                      "id": "1358422e-cc8c-498d-bfe6-f7262e5ecf21",
                      "url": "",
                      "linktype": "story",
                      "fieldtype": "multilink",
                      "cached_url": "/en/accueil",
                      "prep": true
                    },
                    "title": "Home",
                    "component": "link",
                    "_editable": "<!--#storyblok#{\"name\": \"link\", \"space\": \"123366\", \"uid\": \"67c8701e-f2e4-49a1-b5b2-9783d907bfc7\", \"id\": \"68887278\"}-->"
                  }
                ],
                "component": "navigation",
                "_editable": "<!--#storyblok#{\"name\": \"navigation\", \"space\": \"123366\", \"uid\": \"87becaa2-491d-4abb-9c83-2bb1ca3beb9a\", \"id\": \"68887278\"}-->"
              }
            ],
            "component": "header",
            "_editable": "<!--#storyblok#{\"name\": \"header\", \"space\": \"123366\", \"uid\": \"d5f1f4d7-ce87-435a-8554-0273be13a0ed\", \"id\": \"68887278\"}-->"
          }
        },
    ...
}
```

**Expected behavior:**
```diff
EXPECTED :

{
    ...
            "content": [
              {
                "_uid": "87becaa2-491d-4abb-9c83-2bb1ca3beb9a",
                "links": [
                  {
                    "_uid": "67c8701e-f2e4-49a1-b5b2-9783d907bfc7",
                    "path": {
                      "id": "1358422e-cc8c-498d-bfe6-f7262e5ecf21",
                      "url": "",
                      "linktype": "story",
                      "fieldtype": "multilink",
                      "cached_url": "/en/accueil",
                      "prep": true,
                      "story": {
                        "name": "Accueil",
                        "id": 67284872,
                        "uuid": "1358422e-cc8c-498d-bfe6-f7262e5ecf21",
                        "slug": "accueil",
                        "full_slug": "en/home",
                        "url": "en/home"
                      }
                    },
                    "title": "Home",
                    "component": "link",
                    "_editable": "<!--#storyblok#{\"name\": \"link\", \"space\": \"123366\", \"uid\": \"67c8701e-f2e4-49a1-b5b2-9783d907bfc7\", \"id\": \"68887278\"}-->"
                  }
                ],
                "component": "navigation",
                "_editable": "<!--#storyblok#{\"name\": \"navigation\", \"space\": \"123366\", \"uid\": \"87becaa2-491d-4abb-9c83-2bb1ca3beb9a\", \"id\": \"68887278\"}-->"
              }
            ]
    ...
}         
```

**Other information:**

Similar to #694 but with nested stories.

**However, works when querying HeaderItems**

```
{
  HeaderItems(resolve_links: "url", starts_with: "en/*") {
    items {
      content {
        component
        content
      }
    }
  }
}
```

**Comment by bekir-arkulpa** [comment]
Same problem, links get resolved until a certain nesting, afterwards it just stops working and returns the normal link object without the story added,

**Comment by VojislavVlasic** [comment]
Hello everyone,
Our API resolves relations 2 levels deep and links 1 level deep.
If I'm understanding properly what you wrote, this is matching your case, would that be correct?

**Comment by bekir-arkulpa** [comment]
> Hello everyone, Our API resolves relations 2 levels deep and links 1 level deep. If I'm understanding properly what you wrote, this is matching your case, would that be correct?

This does not solve the issues we are facing, it means that comple Applications would not be suitable to use with Storyblok as the relations are resolved only to a limited amount which is really low (1 and 2).
Is there no way this can be increased ? if not this really limits Storyblok to be used for only Simple Use cases and not complex ones.
Why was this issue closed without any kind of properly answer about what can be done ?

**Comment by VojislavVlasic** [comment]
Hello @bekir-arkulpa , hope you're doing well.
Relations and links are resolved to the limited amount, if you need to go deeper we're expecting our users to implement that logic on their end.
We're not planning on increasing these at the moment, having said that you can submit a Feature Request.
You can also reach out to our support team and they might be able to help you with your implementation.

**Comment by bekir-arkulpa** [comment]
Hey @VojislavVlasic ,
Thanks for your answer, now everything is clear.

**Comment by VojislavVlasic** [comment]
@bekir-arkulpa you're welcome, I'm wishing you an awesome day ahead.

**Comment by thomascallahan** [comment]
@VojislavVlasic @bekir-arkulpa Several comments -- it may not be as simple as a depth limit.

First, the "resolve_..." options are poorly documented. I did a LOT of trial and error to get it working using the draft data, and the only thing that really explained it was a post documenting changes to the feature over time. The API docs didn't really explain it well until I had already figured out how it worked. And then everything failed when I tried to use published data.

Second, the actual API documentation does not mention this 2-level limit for resolve_links, only for resolve_relations.

Third, that limit only seems to apply to the published data set -- I don't think a limit is applied at all with draft data, which seriously complicated troubleshooting this. Only once I found the missing "links" field in the raw API response when using the published data set was I able to google this issue with specific enough terms to find this issue.

Fourth, this limit does not seem to apply equally depending on what value you pass for resolve_links. If I pass "url", I don't get resolved links even just two levels deep. If I pass "links" or "story", I do get them. Maybe this isn't a depth limit problem after all, and the real issue is that resolve_links=url doesn't work at all with published data? Fortunately in my case I can probably modify my code to work with the results from link instead of url.

Anyway, very confusing issue. This is my second project using Storyblok (doing both simultaneously, so it's really my first) and overall it's been a great experience, but this was super frustrating.

**Comment by thomascallahan** [comment]
@VojislavVlasic The documentation says this limit applies to resolve_relations. If it applies to resolve_links too, that should be stated. 

Also the limit does not appear to apply to draft data, only published. Super frustrating to find the limit only after trying to build based on published data -- now I will probably have to rebuild part of my site to retrieve the missing data.

Also, a limit of 1 or 2 is nowhere near deep enough. Nowhere in my site is there a story that has links that need resolving as a direct child, and in only one place is it at 2 deep.

**Comment by zipme** [comment]
I think we should reopen this one, link resolution is super buggy

**Comment by unckleg** [comment]
I agree, let's reopen. The same issue is with nested resolve_relation.

**Comment by mediabeastnz** [comment]
Yeah i've tried using the GraphQL API and seem to be having trouble getting nested relations/links.

For example this is a simple query to get global call to actions which inside them have a link field that should resolve.

```gql
{
    ContentNode(
      id: "home",
      resolve_relations: "call_to_action_block.call_to_action",
      resolve_links: "url"
    ) {
      uuid
      name
      content
    }
}
```

**Comment by purecopy** [comment]
Is there any progress on this issue?

**Comment by fm-engage** [comment]
I'm beyond shocked that this is even a topic of discussion, this is such a basic functionality that I can't understand how someone could build even a normal website with such limitation

**Comment by aviv-djordje-stojiljkovic** [comment]
> I'm beyond shocked that this is even a topic of discussion, this is such a basic functionality that I can't understand how someone could build even a normal website with such limitation

I feel you bro. This is shame!!
