### ISSUE TITLE
Stop Stripping new lines Markdown 

### ISSUE THREAD

**Issue by tomSawkins** [storyblok/storyblok#71]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
When using the Markdown type you are able to enter multiple line breaks between content. However on save any extra line breaks between content are stripped out.

**Expected behavior:**
Don't strip extra line breaks between content

**Steps to reproduce:**
- Add some content into the Markdown editing field
- Press enter 2 times add more content
- Save content & reload

<img width="324" alt="Screen Shot 2019-08-20 at 2 53 23 pm" src="https://user-images.githubusercontent.com/3917484/63318646-85286200-c35a-11e9-8716-c52835032d91.png">

<img width="324" alt="Screen Shot 2019-08-20 at 2 53 47 pm" src="https://user-images.githubusercontent.com/3917484/63318645-85286200-c35a-11e9-899a-7096dec768f4.png">

**Comment by onefriendaday** [comment]
The configuration is already deployed. There is also another alternative now: https://www.storyblok.com/cl/richtext-field
