### ISSUE TITLE
Field Level Translation: Locale Sorting

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#72]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Locales are not sortable in the settings to define the specific order of them without having to manually replace the locales for each of them.

**Expected behavior:**
Drag & Drop possibility or position attribute to define the order independently of the order they were entered.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/sortable-languages

**Comment by coremyslo** [comment]
is this feature active at the moment?
