### ISSUE TITLE
Sync command: stories status not synced 

### ISSUE THREAD

**Issue by Axel29** [storyblok/storyblok#721]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**
Stories are created as draft.

**Expected behavior:**
Stories status is the same on the target space as the source space.

**Steps to reproduce:**
1. Run the `storyblok sync --type stories,folders --source XXXXX --target YYYYY`
2. Compare the source and target stories statuses

**Comment by ademarCardoso** [comment]
This issue are fixed in [this PR](https://github.com/storyblok/storyblok/pull/847), you could see the changes in the new version of the CLI.

Sorry for the time to respond.
