### ISSUE TITLE
Add new user via email

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#73]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Trying to add user a by email, it says No user with this email. 

**Expected behavior:**
Send an invitation to the email address and automatically add them to the space, when they sign up.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
https://www.storyblok.com/cl/lookahead-and-collaborator-invite
