### ISSUE TITLE
Ability to order numbers in API queries greater than 32 bit

### ISSUE THREAD

**Issue by mattatcubix** [storyblok/storyblok#739]
**The feature would affect:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
Ordering API responses by a number field is limited to 32 bit integers. It's not possible to sort a number larger than 2,147,483,647.

**Describe the solution you'd like**
Ability to order by larger numbers.

**Comment by sebgie** [comment]
Hey, thank you for creating this feature request. We are working on a new feedback platform at [feedback.storyblok.com](http://feedback.storyblok.com/) and have transferred this request to https://feedback.storyblok.com/b/feature-requests/ability-to-order-numbers-in-api-queries-greater-than-32-bit. Feel free to add more context there.
