### ISSUE TITLE
Rich text editor uses <b> not <strong>

### ISSUE THREAD

**Issue by Kainkainkain** [storyblok/storyblok#759]
Sorry - I can't find any other feed back channel other than Sales chat. 
Storybloks rich text editor uses `<b>` not `<strong> `and `<i>` not `<em>`. In the mid-2000's web developers pushed towards semantic web coding and most users prefer` <strong>` and `<em>` instead of `<b>` and `<i>`.  
The HTML5 specification states that the` <b>` and `<i>` tags must be used as a last option when there isn’t another more appropriate tag.
https://www.w3docs.com/snippets/html/what-is-the-difference-between-b-and-strong-i-and-em-tags.html

**Comment by sebgie** [comment]
Hey, thank you for creating this feature request. We are working on a new feedback platform at feedback.storyblok.com and have transferred this request to https://feedback.storyblok.com/b/feature-requests/rich-text-editor-uses-b-not-strong/. Feel free to add more context there.
