### ISSUE TITLE
Populating the space next to an Entry's name

### ISSUE THREAD

**Issue by cn-d** [storyblok/storyblok#76]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [ ] feature request  
- [x] question

**Current behavior:**

It would be very useful for me to populate the space to left of an entry's name with content/meta data from the entry in order to better distinguish from similar entries. Particularly in cases where the folder structure is not appropriate to group entries. Is it possible to this currently? If not, is this something on the horizon?

<img width="1227" alt="Screenshot 2019-08-31 at 13 11 40" src="https://user-images.githubusercontent.com/8442750/64063856-08b34000-cbf2-11e9-9d22-6b0187027cd6.png">

**Comment by DominikAngerer** [comment]
Hey @cn-d! Definitely, we've that part already on our list to customize. You can find it on our public roadmap as "customizeable list views".
