### ISSUE TITLE
Multi-option selectors from stories do not sort data alphabetically

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#77]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Multi-option selectors which take data from stories do not sort this data alphabetically in the check-box list.

![Screenshot 2019-09-02 at 18 17 37](https://user-images.githubusercontent.com/12583581/64128411-5c6a8880-cdae-11e9-9005-39aaf0989248.png)
^ Not sorted alphabetically, very frustrating for users

**Expected behavior:**
Story data should be displayed alphabetically to make it easy to find options.

**Comment by DominikAngerer** [comment]
will be discussed in #82
