### ISSUE TITLE
SVG Images served without Dimensions in CDN Image URL

### ISSUE THREAD

**Issue by sa-slesch** [storyblok/storyblok#773]
**The issue occurs while working with:** 
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface* 
- [X] *Other: Storyblok CDN* 

**Current behavior:**
Usually the Storyblok CDN includes the image dimensions in the Image URL e.g. 
//a.storyblok.com/f/...`/1000x1000/`.../....png

but for SVG Images it's missing:
//a.storyblok.com/f/...`/x/`.../....svg

**Expected behavior:**
Serve SVG Image dimensions in the Image URL e.g.
//a.storyblok.com/f/...`/120x90/`.../....svg

**Steps to reproduce:**
Upload a SVG Image

**Other information:**
<img width="270" alt="png - correct" src="https://user-images.githubusercontent.com/80514297/159700862-646016c6-0fcc-4717-bf86-3a7ab3af28b7.png">
<img width="242" alt="svg - wrong" src="https://user-images.githubusercontent.com/80514297/159700875-c3d7c040-5222-4682-b2d3-1110ac896244.png">

**Comment by sa-slesch** [comment]
Yes, SVGs are infinitely scalable but still have a ratio.

**Comment by Schinkentanz** [comment]
Hey guys, this is what we using to get the dimensions of a SVG image. Maybe you could adapt this?
https://github.com/image-size/image-size/blob/main/lib/types/svg.ts

**Comment by simonmumenthaler** [comment]
@hecktarzuli 
Storyblok allows to set a FocusPoint which is then absolute corresponding to the width/height attributes of the svg - this is the same behaviour as for the images.
So it actually is an inconsistency that the size is not defined in the URL as it is for images and can therefore be considered as a bug.

Example why it should be there:
If we use SSR and want to specify the final size of the SVG with html attributes on a wrapping div or similar (so we can prevent layout shifts) it's necessary to actually fetch the svg on server side only to know the size. this is s**t as we actually want to fetch the SVG in client only.

**Comment by simonmumenthaler** [comment]
It would basically make sense to provide the `width` and `height` or at least the `ratio` in the asset object. So it wouldn't be necessary to parse it from the url (which is a bit cumbersome imo).

`width` / `height` could be set to null when not defined in the svg.

**Comment by TiagoJeronimo** [comment]
Hello 👋  I'm wondering if there's any progress on this as I'm currently suffering from the same problem. 
(i.e., I'm using SVGs with dimensions specified, but I'm not getting the dimensions in the Image URL).

I noticed that the [FAQ - Access image dimensions of assets in JavaScript](https://www.storyblok.com/faq/image-dimensions-assets-js) uses a `.svg`. I'm not sure if this was updated recently or if this example also has the same problem :)

**Comment by simonmumenthaler** [comment]
@TiagoJeronimo afaik nothing changed - but this screenshot might show that it's actually a bug.

Also interesting:
When opening an `svg` in the Assets View the storyblok UI shows the dimensions:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/37636934/203712770-c023e114-e870-4c57-8dbc-2470e42bb1b0.png">

Dear Storyblok (@thiagosaife @lisilinhart), please fix this or at least give us a sign of life.

**Comment by lisilinhart** [comment]
Hi @simonmumenthaler, I will check with our internal bug system if this is reported

**Comment by VojislavVlasic** [comment]
Hello everyone, we've taken care of this.
svg images that are newly uploaded will have dimensions.
Thank you for your suggestions.
