### ISSUE TITLE
Possibility to select the Folders/Components to merge when using the Dimensions-App

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#78]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

**Expected behavior:**

A fast and easy way to select the parts to merge when working with multi tree structures before merging the structures so the work with it gets easier and the tool itself more flexible.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
You can now select which parts of your entry to be merged using the field settings itself: https://www.storyblok.com/cl/force-overwriting-dimensions
