### ISSUE TITLE
Unable to overwrite assets

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#79]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Uploading a new version of the same image (e.g. edited) – I have to manually relink all previously used versions of this image as the new one does not replace the old – if I wanted for this image to be overwritten, this is a very tiring procedure. It’s a common occurrence to need to do this and I would argue the current behaviour is definitely not the expected behaviour. 

**Expected behavior:**
Automatically overwrite + update the old (identically named) image – or at least provide a dialogue which asks which you would like to do.

**Comment by DominikAngerer** [comment]
https://www.storyblok.com/apps/replace_asset

Replacing assets is already possible. As invalidations are costly in a CDN world its available as an App :)

**Comment by simonhrogers** [comment]
OK thanks Dominik!

I’m not sure I understand why it would cost you more – versus the client deleting and uploading a new asset in it’s place which _seems_ (to someone uninformed like me) that it would still involve all the same transformations; but with a much less efficient workflow. 

The replace feature is a standard behaviour in Storyblok’s competitors – which unfortunately my client will know and tell me all of this too, so am just wondering how you would explain this to them as the jump in cost between Basic / Advanced is not something they will be too happy about.
