### ISSUE TITLE
TinyMCE loading incorrectly after saving/loading child blocks. 

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#8]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  

**Current behavior:**
This happens I think after we save the page and move between blocks hierarchies. 

_No style formats_
![image](https://user-images.githubusercontent.com/14123790/35201806-3218ce34-ff83-11e7-8c2e-e1efbe4a0144.png)

_Style format position is goes haywire_
![image](https://user-images.githubusercontent.com/14123790/35201875-b9558dce-ff83-11e7-807b-757ba084d650.png)

**Expected behavior:**
On page reload it loads properly. 
![image](https://user-images.githubusercontent.com/14123790/35201819-447ed67c-ff83-11e7-9f75-8f15e6340a7b.png)

**Steps to reproduce:**
1. Load page
2. Edit an existing child block.
3. Add a new block. 
4. Save.
5. Go back to the root block
6. Error should occur 80% of the time. 

I suspect this is TinyMCE vue component loading too many times in the DOM. All in all, the TinyMCE isn't working very well at the moment with the StoryBlok app and needs some integration work to be done. 

**Related code:**
Almost the same code as storyblok's tinymce plugin provided by Alexander, just added a few tinymce settings and styles.
Plugin link: http://app.storyblok.com/#!/me/plugins/103

Let me know if you need more info.

**Comment by onefriendaday** [comment]
The official TinyMCE plugin has been updated to fix this issue:
https://github.com/storyblok/fieldtype-tinymce/commit/cd3fccfe9dc531573f1671456b5033626241026d

The update is using the 'plugin:destroyed' hook to clean up the tiny instances with window.tinymce.remove()
