### ISSUE TITLE
Close the Content list item action modal in an intuitive way 

### ISSUE THREAD

**Issue by cn-d** [storyblok/storyblok#80]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x ] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
This seems like a bug, although an edge case. When on the content list page, if I click on the 3 dots in an item but decide I don't want to click on any of the actions in the modal that opens; I am not able close the modal in an intuitive way. I had to click on 'Content' in the side panel to return to the content list. In my view, an intuitive way would be closing the modal when blurring off the modal into blank space.

<img width="978" alt="Screenshot 2019-09-03 at 22 02 40" src="https://user-images.githubusercontent.com/8442750/64209423-610b6b80-ce98-11e9-8496-7e63678cf173.png">

**Comment by onefriendaday** [comment]
You can click again on the three dots to close the modal.
