### ISSUE TITLE
Clicking on a component doesn't select it

### ISSUE THREAD

**Issue by hypeJunction** [storyblok/storyblok#81]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
On our production site with Cloudflare, clicking on the component doesn't select it.
Console logs an error:  `Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://bodyologymassagecourses.co.uk') does not match the recipient window's origin ('http://app.storyblok.com').`. 

Not sure if we should be changing CORS policy somewhere.

**Expected behavior:**
Clicking on the component, selects it in the sidebar.

**Comment by onefriendaday** [comment]
Usually there are other reasons that the selection doesn't work.

Could you please check following conditions:

- The Storyblok js bridge gets included on the site and is initialized. Maybe calling Storyblok.init() helps
- The draft version and NOT the published version of the content is loaded
- The v-editable (if you use Vue.js) or other helpers are wrapping the editable html nodes

**Comment by hypeJunction** [comment]
Everything works if we disable CloudFlare, so there is something we need to do about CORS in CloudFlare. Not sure what exactly needs to be defined, as I am not that familiar with Storyblok internals.

**Comment by onefriendaday** [comment]
I doubt this has something to do with CORS. It could also be that cloudflare does a redirect. Could you check that?
