### ISSUE TITLE
Sorting feature for entries in Single + Multi-Options Fields

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#82]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual sorting order is random.
**Expected behavior:**

For easier work with the single and multi-options fields it would help to be able to choose the sorting order manually for different data like the slug alphabetically, publication date, etc
This request extends a preceding request https://github.com/storyblok/storyblok/issues/77
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
The default sort order is the position defined in the content browser. The user can use the search box to search for specific content.
