### ISSUE TITLE
V2 Admin UI: does not save "Sort by" option in content tree

### ISSUE THREAD

**Issue by klausfischer** [storyblok/storyblok#823]
Hey Storyblok Team,

congrats to the launch of V2 🎉

**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
If I'm in the _Content_ tab of app.storyblok.com and choose a sorting option for the content tree (e.g. _Name (asc)_), this sorting criteria will be reset to _Default_ after visiting another tab or viewing a story.

**Expected behavior:**
app.storyblok should remember my chosen sorting criteria like in the V1 admin.

**Steps to reproduce:**
- Visit app.storyblok.com
- Login & select a space
- Click _Content_ in the left sidebar
- In the search bar on top of the content tree select _Sort by_ and choose **any other** sorting criteria than _Default_
- Click on a story or on another tab in the left sidebar
- Go back to _Content_ (viewing the content tree)
- Voilà you're back in _Default_ sorting :)
- V1 UI was kind enough to remember the selected sorting criteria

Is this a bug or a conscious choice for V2? Would be nice if you can check this and provide some indications about next steps.

Thanks!

**Comment by klausfischer** [comment]
Hi @christianzoppi, any news on that? 

Can you maybe ask your fellow devs and give an update here in the ticket, if it's confirmed as a bug?

Thanks!

**Comment by LucaPuccinelli** [comment]
Hello there,
I can confirm that the bug has been fixed and published.
Kind regards.
