### ISSUE TITLE
Add "resolve_relations" capabilities in custom field type objects

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#83]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Relations have to be resolved manually by fetching them with an additional call which can make a code more complicated and error prone causing longer development and debugging times.
**Expected behavior:**

The code could be smaller, faster and easier to maintain if the "resolve_relations" parameter would be available in the plugins area too.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Unfortunately this functionality can not be to the api at the moment. We recommend you to use the standard "Option" or "Multi-Option" field if you want to use resolve_relations.
