### ISSUE TITLE
Add possibility to restrict "Delete" function in the asset manager for user roles on root level

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#84]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The actual way to restrict a user from deleting assets is to create a custom role, an empty directory and use the white "Asset Folder Permissions" list in which the empty folder gets added.
**Expected behavior:**

With a dedicated checkbox for custom user roles restricting the access to the delete function will make it easier to create role profiles for special cases.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by Slackman2015** [comment]
Addition: add restriction for file upload for custom user roles

**Comment by onefriendaday** [comment]
We think that asset folder organisation usually is not dangerous for the live project as the assets are linked in the content and not the folders. For now we will focus on better access management in the content area.
