### ISSUE TITLE
Add possibility to move multiple stories in the interface

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#85]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

In the front end it isn't possible to move more than one story at once.
**Expected behavior:**

It would be a great time saver to be able to move more than one story with the front end to make the life of editors easier.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been solved
