### ISSUE TITLE
Is it possible to change schema of a block dynamically based on user input ?

### ISSUE THREAD

**Issue by siddharth-joshi-9** [storyblok/storyblok#86]
Explanation: 
I have a single-option field in my block with following options
a. one
b. two

In this case is it possible to show one more field if user selects 'one', and another text field if the user selects 'two'

Thanks in advance

**Comment by DominikAngerer** [comment]
Hey there! Conditional fields are available through custom field types. You can find the starter kit for this right here: https://www.storyblok.com/faq/can-i-create-conditional-fields-or-logic

Our plugin/custom field type cookbook can be found here: https://www.storyblok.com/docs/plugins/introduction

**Comment by siddharth-joshi-9** [comment]
Thanks @DominikAngerer for a quick response, The documentations were a huge help !
