### ISSUE TITLE
forum.storyblok.com does not exist

### ISSUE THREAD

**Issue by david-bezero** [storyblok/storyblok#860]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [x] *Other:* https://www.storyblok.com/trust-center/service-support 

**Current behavior:**
> For general questions regarding integrations, frameworks or common problems we have set up a forum: [Storyblok Community Forum](https://forum.storyblok.com/)

linked page fails with: DNS_PROBE_FINISHED_NXDOMAIN

**Expected behavior:**
Link works, or is not present

**Steps to reproduce:**
Go to "Trust Center" link in footer of main storyblok.com page, click "Service & Support" in the "SaaS Support & Services" section, then click "Storyblok Community Forum"

**Comment by christianzoppi** [comment]
Thanks @david-bezero for reporting this! The broken link has been fixed :-)
