### ISSUE TITLE
Filter unused assets

### ISSUE THREAD

**Issue by RaphaelBronsveld** [storyblok/storyblok#868]
Hi there,

Is it possible to filter for unused assets in Storyblok? I haven't found an option to filter for unused assets and delete these.

I'm looking for functionality to make it possible to delete unused assets. Clicking an asset shows the references, so it might be possible to delete unused assets in 1 bulk action.

Thanks in advance.

**Comment by bmwasonga** [comment]
Hi,  consider this script: 
[unused images crawler ](https://github.com/onefriendaday/unused-images-crawler-storyblok)

After it has run successfully, you should be able to have all unused assets in one folder where you can now easily review and bulk delete at will.
