### ISSUE TITLE
"Storyplok" in the app plan comparison modal title

### ISSUE THREAD

**Issue by Tenga** [storyblok/storyblok#869]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

**Current behavior:**

Within the CMS, in the plan comparison modal, the modal title states "Storyplok plan comparison"

**Expected behavior:**

That `p` in `Storyplok` should be mirrored vertically so it looks like this `b`, so it says `Storyblok`

**Steps to reproduce:**

- Open CMS interface
- Click on "Settings" on the left menu
- Click on "Subscription" on the "Settings" page
- Click "Show Plan Comparison" at the bottom of the page
- Observe the modal title

**Other information:**

![image](https://user-images.githubusercontent.com/419948/203638785-91d2cd49-a07a-4fcf-b793-8e63a7e48205.png)

**Comment by lisilinhart** [comment]
Thanks @Tenga, this issue should be fixed tomorrow
