### ISSUE TITLE
Update SEO image to allow external assets

### ISSUE THREAD

**Issue by danielbrooks4p** [storyblok/storyblok#87]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
When adding an image asset with the SEO plugin, you must use the built-in asset manager.

**Expected behavior:**
All other image-based field schemas allow the user to supply an external URL for an image asset (i.e. images hosted on a CDN or S3 bucket). This image field should also allow for this.

**Other information:**
This causes one image for each story to have to be loaded from a new domain. As far as SEO goes, the fewer domains you're requesting your assets from, the better. This update would allow Storyblok users to keep their requested domain count low and manage all their assets in one place - outside Storyblok if they so choose.

**Comment by DominikAngerer** [comment]
Adding a new field to your content with either a new plugin or a text field will allow such a behavior.
