### ISSUE TITLE
random position numbers when creating new items

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#88]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment when a new story is added to a folder and the the link API is being used to create menus the new items are getting a random position numbers even when any order has been chosen before.
**Expected behavior:**

To make it easier to work with the links API and less error prone the new items should get a position number oriented on the items in the folders which would save time too.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
In the links api you can sort the items by the position attribute.
