### ISSUE TITLE
storyblok-cli on npm is still getting around 20 downloads per week. Is there a way to delete it or show a better message to people?

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok#885]
Hi! I noticed that the storyblok-cli page on npm is still getting steady amount of downloads, which means that people are finding it and trying to use it.

The descriptions shows the correct command `npm i storyblok -g` but the side bar does not.
![image](https://user-images.githubusercontent.com/5083273/212120895-ce8b501e-6c7f-467a-bf1a-d16a41b76338.png)

This means that people are still downloading the WRONG package being specified on the right instead of the correct one here:
https://www.npmjs.com/package/storyblok

My suggestion would be to remove it or more clearly show that it is the wrong package.

**Comment by bmwasonga** [comment]
This was resolved
