### ISSUE TITLE
Automatic permanent redirects after changed slug (301)

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok#889]
**The feature would affect:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
We would like to have a way to turn on automatic redirects from changed slugs. Right now if we change a slug, the old slug results in 404 which kills the SEO.

**Describe the solution you'd like**
A way to automatically redirect the changed slugs.

**Describe alternatives you've considered**
We have considered storing a list of changed slugs somewhere, but there are multiple issues with this.

**Additional context**
Other people who have requested this:
https://discord.com/channels/700316478792138842/700327749306286091/985813648054296577

General information about this:
https://kontent.ai/blog/how-to-handle-url-redirects-with-headless-cms/
https://discourse.webflow.com/t/new-page-title-and-slug-automatically-redirected-to-404-with-old-slug/114067
https://aioseo.com/how-to-avoid-404-errors-when-updating-your-wordpress-site/
https://wordpress.stackexchange.com/questions/108039/a-change-in-url-slug-in-database-returns-404-how-can-i-do-auto-redirect
https://discourse.webflow.com/t/how-to-set-up-a-301-redirect-when-changing-cms-collections-slug/211778

Let me know if you need any additonal infomration.

**Comment by samuells** [comment]
Hey @SebbeJohansson,

I agree that this is a tricky topic. We believe that the responsibility for redirects lies with the hosting system. As a headless CMS, our role is to deliver the content and potentially define the URLs. However, our slugs deliver JSON and not final pages. Even we rely on our hosting provider in the case of redirects. 😏

You may also want to check the redirects configuration if you are using Vercel or Netlify.

- [https://docs.netlify.com/routing/redirects/](https://docs.netlify.com/routing/redirects/)
- [https://vercel.com/guides/does-vercel-support-permanent-redirects](https://vercel.com/guides/does-vercel-support-permanent-redirects)

You can keep a list of redirects in Storyblok as a special Story or Datasource.

However, I can see some edge cases where it could be useful to have this feature within the CMS. I will take this into our internal feature evaluation process and discuss it with all stakeholders. Please keep an eye on our roadmap to see all upcoming features.

Thank you for all the feature requests you have sent.

**Comment by SebbeJohansson** [comment]
@samuells thanks for taking a look and giving a thorough thought to it!
I think for our use case (given that our hosting method does not give us any help with this) is to store redirects as a datasource in storyblok and reference that when looking at routes.

I'll have to do some research on how viable that is.
