### ISSUE TITLE
Custom ratio for the image editor when cropping parts of the image

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#89]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

At the moment there are 4 options for a user: Original, 16:9, 2:3 and 1:1
**Expected behavior:**

In some cases the user needs to be able to choose an own ratio to get the result he desires. An example is this advanced Vue Cropper https://norserium.github.io/vue-advanced-cropper/
The user can choose which area gets cropped and the remaining area can be chosen manually.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/custom-image-ratio

**Comment by joshcawthorne** [comment]
Are there any plans to integrate cropping functionality into the newer asset field?
