### ISSUE TITLE
Live editing is causing us to hit our monthly api limit without having any actual visitors.

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok#892]
**The feature would affect:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

This is more of a feature request for how storyblok as a service and the business works, and GitHub might not be the correct forum for this. Let me know if I need to email/chat instead!

**Is your feature request related to a problem? Please describe.**
Right now we are at 3,083,356 million requests for our monthly count which has a limit of 3,000,000. This is **WITHOUT** any actual customer traffic and only our editors. We are planning to upgrade to Enterprise Plus, but i have a feeling that might not be enough either!

**Describe the solution you'd like**
I think it would make more sense that the live editor doesn't count to the API limit or at least have different counts for published and for draft requests. 

**Describe alternatives you've considered**
We have considered turning off the live editor, which is not acceptable.

**Comment by samuells** [comment]
Hey @SebbeJohansson, could you please contact us through your Customer Success Manager or Account Executive? If you don't have either of those, you can reach us through the live chat on [[storyblok.com](http://storyblok.com/)](http://storyblok.com/). Your case sounds unique and we'll need more detailed information to assist you.

Please let them know that Samuel Snopko recommended this approach on GitHub.

Cheers and thank you!

**Comment by SebbeJohansson** [comment]
@samuells just some context, this issue was created after taking to those options!
We now know:
1. It was the requests resulting in 404 that was causing this.
2. A bug in our system was fetching a 404 page (/null) on every single page load (even if the slug existed).

So after limiting our storyblok integration to only fetch from our blog routes for now (we know that this is our main focus for now) and stopping the source of the /null fetches, our usage is now acceptable.

I do still feel like 404s shouldn't count the same as slug fetches that actually return data, but that's more of a contract discussion and a business model discussion on your side.

Thanks for going through all of my issues btw!

**Comment by samuells** [comment]
Thank you for reminding me of the idea of a default 404 story. I think there is a different perspective where we could provide a default 404 page for cases when a story that does not exist is requested. I will include it in our evaluation process. Again, thank you.
