### ISSUE TITLE
Allow for preview button without visual editor being turned on

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok#893]
**The feature would affect:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
We are hitting our api request limit because of the editor. We need to disable the editor, but we cant preview at all with it turned off.

**Describe the solution you'd like**
My suggestion is to change so that switching of visual editor still allows for the preview button. Without the preview button the whole editor is completely useless since the content team cant see the page in draft mode.
![image](https://user-images.githubusercontent.com/5083273/214250987-b3beb30e-7ce7-45a6-89df-785fb44214ec.png)
It could make sense to allow for a toggle to disable the preview button.

**Describe alternatives you've considered**
We have considered disabling it and only edit without seeing anything and also disabling visual editor in specific folders. No alternative we have come up with or been suggested has been acceptable.

**Additional context**

**Comment by N3uRaL4Ca5t** [comment]
Bang bang niners lost 🙁 good game though

**Comment by samuells** [comment]
Thank you for submitting your feature request. It has been included in our internal feature request process, and we will carefully evaluate it. We will keep you updated on our progress through our roadmap (https://www.storyblok.com/roadmap).
