### ISSUE TITLE
Limit what domains and/or IPs a token works on with the content delivery api

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok#896]
**The feature would affect:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
We have no way of limiting the usage of a token which means that someone could theoretically grab it and misuse it.

**Describe the solution you'd like**
A setting in the interface for tokens to add what domains and/or IPs that a token can be used on.

**Describe alternatives you've considered**
Considered doing an API middleware on the server in our application which would limit the risk, but doesn't solve it completely.

**Additional context**

**Comment by samuells** [comment]
Thank you for submitting your feature request. I understand your point of view, and we will carefully consider it internally. We will keep you updated on any progress regarding the feature through our roadmap ([https://www.storyblok.com/roadmap](https://www.storyblok.com/roadmap)).

Thank you again!
