### ISSUE TITLE
Required Field

### ISSUE THREAD

**Issue by pxwee5** [storyblok/storyblok#9]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com*   

**I'm submitting a ...**  (check one with "x")  
- [x] feature request  

**Current behavior:**
Currently there are no settings to make a field "required" in storyblok

**Expected behavior:**
Create a checkbox to enable "required" verification on components. Ideally, the verification should accept mixed data, so that it could support regex as well.

**Comment by onefriendaday** [comment]
Hi @pxwee5 !

Thank you for your feature request. Following a screenshot how the validation looks like in a first draft. The validation will happen when clicking the save button which will show a list of all required fields with links to the components. Would that help you?

![Alt text](https://monosnap.com/file/pVuyPJTef50azuXWU8KSbxlP8mKvHC.png)

**Comment by onefriendaday** [comment]
The new feature has been deployed and the required checkbox as well as the regex field is available in the schema configuration now.

**Comment by pxwee5** [comment]
Not sure if this feature has created this bug. But here's a screenshot of me trying to make a root page. 
![image](https://user-images.githubusercontent.com/14123790/35370156-f30e8150-01f0-11e8-9330-aa2e3281ed06.png)

Does this work in the root? Or does it only work with folders?

**Comment by onefriendaday** [comment]
The starting_page works only for folders because a story must have a slug. The reason behind this is that /v1/stories is a reserved endpoint for listing multiple stories and to get a single story there is the endpoint /v1/stories/:slug|:id
