### ISSUE TITLE
Visual indicator when someone is already editing a story

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#90]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

In the case that two or more people are up to edit the content of a story and already finished their work a window appears with the question for copying the own text over to the new version of the of the from another one modified text or if on would like to overwrite the newer version.
**Expected behavior:**

A visual indicator would help to coordinate the work on big projects as it isn't possible to foresee if another teammate already works on the same story and could over write the new just written content.
Additionally an information who actually works on the story would be the key to be able to communicate with the colleague. Something like the e-mail address would help out in this case.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/showing-editing-users
