### ISSUE TITLE
I'll open a feature request

### ISSUE THREAD

**Issue by renatasfarago** [storyblok/storyblok#900]
**The feature would affect:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [x] *a.storyblok.com (CMS - Image Service)*
- [x] *Other* 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by renatasfarago** [comment]
Hakuna Matata!

**Comment by samuells** [comment]
Dear Renata,

Thank you for your message! Your words brought a smile to our faces and brightened our day. We appreciate your kindness and the time you took to reach out to us.

We hope you have a fantastic day and continue to bring joy wherever you go!

Best regards,
your Storyblok Product Team 😇
