### ISSUE TITLE
Hide and Show Toggle for Components

### ISSUE THREAD

**Issue by orhancelik1** [storyblok/storyblok#901]
**The feature would affect:** (check one with "x")   
- [ x ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [x] *Other* 

**Is your feature request related to a problem? Please describe.**
When working with big projects that contain lot of components and modules it is a bit painful when we cannot toggle hide some component, We have to remove them or copy them then add again. It should work like comment out some codes. Cutting and pasting not good option right now.

**Describe the solution you'd like**
Just adding toggle hide and show button would be enough. Its like commentting code or component.
![image](https://user-images.githubusercontent.com/51966088/219366501-4cbb9b8b-12d4-42dc-babf-9166919ad0a4.png)
For example this page i just want to see Price Module and hide others to increase load time and maybe hide from Live site. Currently i cant do this and this easy to add but important feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by samuells** [comment]
Dear @orhancelik1 ,

Thank you for taking the time to share your feedback with us. We appreciate your suggestion, but at this time, we do not have any plans to implement this feature. However, we will take note of your request and keep it in mind for future updates.

We have added a "Block search" feature to Visual Editor v2 that could help with your scenario. Check the picture. ☺️

Thank you again for your feedback.

Best regards,
Samuel

![image](https://user-images.githubusercontent.com/5185019/226141623-0b30b762-96f7-4926-b161-9178aecd62f5.png)

**Comment by orhancelik1** [comment]
You are amazing! Thank you so much for this great useful feature.

19 Mar 2023 Paz 00:47 tarihinde Samuel Snopko ***@***.***>
şunu yazdı:
