### ISSUE TITLE
Tiresome time picker upsets users 

### ISSUE THREAD

**Issue by nintra** [storyblok/storyblok#904]
**The feature would affect:** (check one with "x")   
- [ x ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
It's frustrating if you use a date/time picker and the time picker always starts at 23:59. It is far away from common time slots and because of the minute picker starts at minute 59, it's tedious to select a time with full hour. e.g. 14:00 

**Describe the solution you'd like**
Would it be possible to start at a more common time, maybe 12:00?
Could the minute picker be scrollable in both directions so that you easily access minutes that are now far away: 
59 → 00
00 → 45

**Describe alternatives you've considered**
Because this is an import core field, there is no workaround for me.

**Comment by bmwasonga** [comment]
Hello @nintra 
This issue duplicates Issue [903](https://github.com/storyblok/storyblok/issues/904)
We shall let you know as soon as this is done. 

I have captured the details from the two

**Comment by samuells** [comment]
Hello @nintra,

Thank you so much for submitting your feature request. We have moved it into our internal pipeline and will evaluate it carefully.

Would you mind keeping an eye on our roadmap ([https://www.storyblok.com/roadmap](https://www.storyblok.com/roadmap)) for any upcoming updates?

Thank you again!
