### ISSUE TITLE
Multiple webhooks

### ISSUE THREAD

**Issue by kb1995** [storyblok/storyblok#906]
**The feature would affect:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *a.storyblok.com (CMS - Image Service)*
- [ ] *Other* 

**Is your feature request related to a problem? Please describe.**
Currently, we can only have one webhook for "Story published & unpublished". For websites, this will usually be a webhook to trigger a rebuild of the website. I suggest having the ability to add multiple webhooks, eg for Next.js revalidation on demand, zapier integration, etc. 

**Describe the solution you'd like**
Ability to add multiple webhooks within `/settings?tab=webhooks`

**Describe alternatives you've considered**
No alternatives for now.

**Additional context**

**Comment by bmwasonga** [comment]
Hello there, 
Have a look at our activities app here: 

https://www.storyblok.com/cl/tasks-app

Let me know if this provides a solution to the enhancement that you requested.

**Comment by kb1995** [comment]
Hey @bmwasonga - I haven't but they look very useful. Not in the scenario I described though since I want them to be triggered at every document publish (like a normal webhook) and I don't want to change the workflow for my editors.

**Comment by samuells** [comment]
Hey @kb1995, the task app mentioned by Ben is a great tool. You might also be interested in our webhooks for workflows and more. Check out this link for more information: [https://www.storyblok.com/docs/guide/in-depth/webhooks](https://www.storyblok.com/docs/guide/in-depth/webhooks).

We are currently working on upgrading our workflows and actively improving the webhooks infrastructure. Stay tuned and keep an eye on our roadmap for updates. 😇
