### ISSUE TITLE
JS Bridge not returning _editable field (Bug)

### ISSUE THREAD

**Issue by Ashwin-RXP** [storyblok/storyblok#91]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Content sent throught the JS Bridge when editing it the UI doesn't have the field `_editable` which it previously did. This is cause issues when adding new blocks the new elements are not being highlighted & can't be clicked in the ui

**Expected behavior:**
`_editable` should be returned, ie the JS Bridge should be returning content as though it's being requested through the API in `draft` mode

**Steps to reproduce:**
Setup JS Bridge, Make an edit to a story and inspect the returned content of the story. It won't have the `_editable` field present for any of the components within the story

**Comment by onefriendaday** [comment]
We just checked and everything is working as expected so maybe you have not implemented the event listener correctly on your side.

Are you passing the content through the addComments function?

~~~
window.storyblok.on('input', (event) => {
  reactComponent.setState({pageContent: window.storyblok.addComments(event.story.content, event.story.id)})
})
~~~

**Comment by CarsonF** [comment]
I have a similar issue. The `_editable` field isn't returned with bloks _inside_ of rich text fields.
I did just try passing the story content through the addComments function, which I wasn't doing previously either. But it didn't change the content at all.

**Comment by DominikAngerer** [comment]
Adding `window.storyblok.addComments(event.story.content, event.story.id)` will only have an effect if the draft version is loaded, otherwise the `_editable` field won't be in the response from our API.
