### ISSUE TITLE
Add filter option "contains" in API filter_query

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#92]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The search values need to match exactly what is being searched for.
**Expected behavior:**

In the case that for example in a search function the user searches for a special component type "post" and later different similar types with specialization like post-technical are getting added to the CMS and wants to search for all post types but doesn't know exactly the type names the "contains" search could make it easy to find all types. Another example is the search in the content for keywords like household even when only house had been entered.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by dohomi** [comment]
This feature would be highly needed. I personally think that a Regex or simplified version with "*" should be supported inside of `in`, `in_array`and all the other filter options. Usecase:
All stories except stories starts with slug "demo"
```
filter_query:{
  'full_slug':{
   'not_in': 'demo*'
  }
}
```

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/new-date-queries
