### ISSUE TITLE
Add option for component type in token permissions app

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#93]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

It is possible to restrict the access to certain stories and folders by adding the allowed items to a white list with the app under the following link https://www.storyblok.com/apps/token_permissions
In the case that specific components types shouldn't be accessible it isn't possible to restrict the access to them yet.
**Expected behavior:**

With being able to filter the components on a per token basis makes them practically "hidden" inside of the stories and opens new possibilities for the developers to plan when and who they want to get access to the content.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Unfortunately this feature will not come into the core as it may lead to confusion for the developers. But you can create a proxy and select only the components you want to be accessable.
