### ISSUE TITLE
Add OR / AND / XOR to the filter_query for condition connections

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#94]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Currently it isn't possible to connect conditions like -->curl "https://api.storyblok.com/v1/cdn/stories/?filter_query[featured][in]"or"[path][in]=true&starts_with=products/&token=ask9soUkv02QqbZgmZdeDAtt" <--
**Expected behavior:**

Being able to use logical connectors in filter_query would decrease the count of calls to the API and make it much more flexible. The code could be shorter also and faster.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by Slackman2015** [comment]
Additionally to the already opened feature request there is the need to be able to check if fields are empty or not. This comes handy when looking for stories without or with tags, empty fields for example name fields in the content of a story etc.

**Comment by dohomi** [comment]
much needed feature 👍

**Comment by marcinkrawczyk-ef** [comment]
Yup, would be nice to have that there :)

**Comment by onefriendaday** [comment]
The feature of empty field checks has been deployed https://www.storyblok.com/cl/check-for-empty-values

To build OR queries you can use the parameter `filter_query_v2`. `filter_query` will soon be aliased to `filter_query_v2` once we completed all tests.
~~~
Storyblok.get('cdn/stories', {
  filter_query_v2: {
    __or: {
      {color: {in: 'red'}},
      {background: {in: 'blue'}}
    },
    {component: {in: 'article'}}
  }
})
~~~
You may ask yourself why we used `__or` as a keyword? Because this way the query is backwards compatible with existing implementations and the keyword is a valid json key.

We are happy to hear your feedback.

**Comment by cewald** [comment]
> ```
> Storyblok.get('cdn/stories', {
>   filter_query_v2: {
>     __or: {
>       {color: {in: 'red'}},
>       {background: {in: 'blue'}}
>     },
>     {component: {in: 'article'}}
>   }
> })
> ```

This should as following to be valid javascript:
```js
Storyblok.get('cdn/stories', {
  filter_query_v2: {
    __or: [
      { color: { in: 'red' } },
      { background: { in: 'blue' } }
    ],
    component: { in: 'article' }
  }
})
```

Thanks for this feature :)

**Comment by guanacone** [comment]
Is this also possible in graphql?
