### ISSUE TITLE
Add a search field for single and multi opions fields

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#95]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

When working with the single and multi options fields and a high data count finding specific data can be a time consuming task because the user needs to search by looking all entries through.
**Expected behavior:**

With a search field right above the entries the user could find the desired entries much quicker.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
We encourage you here to develop a custom field type plugin and submit it in the app store.
