### ISSUE TITLE
Add slug filter parameter to datasources endpoint

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#97]
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently only available with the `search` parameter.

**Expected behavior:**
An option to use the `slug` as filter on lists and/or allow datasources/:slug.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment]
Has been released: https://www.storyblok.com/cl/find-datasource-by-slug
