### ISSUE TITLE
Replaced images are ”not found”

### ISSUE THREAD

**Issue by simonhrogers** [storyblok/storyblok#98]
**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
Image replace app returns "image not found" for replaced image in block (image not replaced, only new image exists in assets folder)

**Expected behavior:**
Image should be replaced. 

![Screenshot 2019-09-27 at 14 58 20](https://user-images.githubusercontent.com/12583581/65775041-4e9eed80-e137-11e9-8103-d731a9b9a866.png)
![Screenshot 2019-09-27 at 14 58 26](https://user-images.githubusercontent.com/12583581/65775042-4f378400-e137-11e9-8fa1-cd8f9102512d.png)

**Comment by onefriendaday** [comment]
Hi!

The image you are trying to access is lying in the trashbin of your asset manager.
