### ISSUE TITLE
Translatable folder and story names

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok#99]
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

The field-level translation function makes it possible to define different languages and enter translations for those language targets on field level.

**Expected behavior:**

With the possibility to translate the field "name" of the story it would make the task of translating the content more complete and easier to work with when building multi language web apps.
Additionally: Translatable folder names would be a great help too.
For getting the translated name of the folder it could help to generate the slug with the translated name when the starts_with=en/* parameter is being set instead of the default name.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by DominikAngerer** [comment]
:+1: from customer:

## URL Structuring: 
- Field Level Translations
- Translated URL

Possible Solution for preview already exists: https://www.storyblok.com/apps/advanced-paths however the structuring of the content itself would be done using a field in the story for one entry, the folder itself on the other hand would still need a translation option.

```
 Language            Folder names/slug
      v                 v    v
/{country}/help/{category}/{subcategory}/
```

**Comment by onefriendaday** [comment]
Now available via this app: https://www.storyblok.com/apps/translatable-slugs
